export interface ApplicationProductsSettings {
    setDefaultQty1: boolean;
    allowMultiUnits: boolean;
    allowMultirate: boolean;
    batchCriteria: string;
    loadCustomerLastRate: boolean;
    loadDummyProducts: boolean;
    marginRoundTo: number;
    focusToQtyAfterBarcode: boolean;
    stockTransferNegativeStock: string;
    allowMannualProductSelectionInSales: boolean;
    useProductImages: boolean;
    productImagePath: string;
    maintainSchemes: boolean;
    weighingScaleBarcodeType: string;
    pPOsPriceCategory: number;
    showRateBeforeTax: boolean;
    stopScanningOnWrongBarcode: boolean;
    allowOnlyScanProductMarkedAsWeighingScaleItems: boolean;
    loadListedProductPrices: boolean;
    advancedProductSearching: boolean;
    blockQtyChangeOptionInPOS: boolean;
    enableGoogleTranslationOfProductName: boolean;
    setQty1ForWeighingScaleItem_ValueMode: boolean;
    allowUpdateSalesPriceFromPurchase: boolean;
    usePopupWindowForItemSearch: boolean;
    enableMultiWarehouseBilling: boolean;
    enableSupplierWiseItemCode: boolean;
    includeSearchItemAlias_ItemName2: boolean;
    lastSystemGeneratedBarcode: number;
    lastSystemGeneratedBarcodetrue: boolean;
    stopScanningOnWrongBarcodeInSales: boolean;
    enableOrderMangment: boolean;
    enableImportPurchase: boolean;
    excludeSchemeProductAmountFromPrivilegeCard: boolean;
    showPurchaseCostChangeWarning: boolean;
    listBarcodeItemsInItemLookup: boolean;
    showHSNCodeWarning: string;
    giftOnBilling: boolean;
    setProductQtyLimitinSales: boolean;
    enableQtySlabOffer: boolean;
    giftOnBillingAs: string;
    enableMultiFOC: boolean;
    lPPriceLessThanSellingPrice: string;
    mRPLessThanSalesPrice: string;
    zeroMultiRateValidate: string;
    allowUpdateMultiRateinPurchase: boolean;
  }

export  const ApplicationProductsSettingsInitialState: ApplicationProductsSettings = {
    setDefaultQty1: true,
    lastSystemGeneratedBarcodetrue: false,
    allowMultiUnits: true,
    allowMultirate: false,
    batchCriteria: "NB",
    loadCustomerLastRate: false,
    loadDummyProducts: false,
    marginRoundTo: 0,
    focusToQtyAfterBarcode: true,
    stockTransferNegativeStock: "Warn",
    allowMannualProductSelectionInSales: true,
    useProductImages: false,
    enableOrderMangment: false,
    enableImportPurchase: false,
    productImagePath: " ",
    maintainSchemes: false,
    weighingScaleBarcodeType: "Standard. No Check Digit",
    pPOsPriceCategory: 1,
    showRateBeforeTax: false,
    stopScanningOnWrongBarcode: false,
    allowOnlyScanProductMarkedAsWeighingScaleItems: false,
    loadListedProductPrices: false,
    advancedProductSearching: false,
    blockQtyChangeOptionInPOS: false,
    enableGoogleTranslationOfProductName: true,
    setQty1ForWeighingScaleItem_ValueMode: true,
    allowUpdateSalesPriceFromPurchase: false,
    usePopupWindowForItemSearch: false,
    enableMultiWarehouseBilling: false,
    enableSupplierWiseItemCode: false,
    includeSearchItemAlias_ItemName2: true,
    lastSystemGeneratedBarcode: 1000000000001,
    stopScanningOnWrongBarcodeInSales: false,
    excludeSchemeProductAmountFromPrivilegeCard: false,
    showPurchaseCostChangeWarning: false,
    listBarcodeItemsInItemLookup: false,
    showHSNCodeWarning: "Warn",
    giftOnBilling: false,
    setProductQtyLimitinSales: false,
    enableQtySlabOffer: false,
    giftOnBillingAs: "Products",
    enableMultiFOC: false,
    lPPriceLessThanSellingPrice: "Warn",
    mRPLessThanSalesPrice: "Warn",
    zeroMultiRateValidate: "Warn",
    allowUpdateMultiRateinPurchase: false,
  };