export interface ApplicationGstSettings {
    purchaseNormalType: boolean;
    purchaseInterstateType: boolean;
    purchaseForm62: boolean;
    outputFormType: string;
    defaultFormTypeForPOS: string;
    inputCSTAccount: string;
    defaultPrefixForPOS: string;
    outputCSTAccount: string;
    defaultSRFormTypeForPOS: string;
    inputCessAccount: string;
    defaultSRPrefixForPOS: string;
    outputCessAccount: string;
    inputSGSTAccount: string;
    outputSGSTAccount: string;
    inputSGSTLedgerID: string;
    inputAddCessAccount: string;
    outputSGSTLedgerID: string;
    outputAddCessAccount: string;
    inputCGSTAccount: string;
    expensesTaxAccount: string;
    outputCGSTAccount: string;
    incomeTaxAccount: string;
    inputIGSTAccount: string;
    enableEWB: boolean;
    outputIGSTAccount: string;
    enableEInvoiceIndia: boolean;
    outputTCSPaidAccount: string;
    einvoiceProvider: string;
    outputTCSPayableAccount: string;
    eInvoiceAuthToken: string;
    inputCalamityCessAccount: string;
    eInvoiceOwnerID: string;
    outputSalesCalamityCessAccount: string;
    considerSalesPriceasCalamityIncluded: boolean;
    enableKarnatakaTaxReportFormat: boolean;
    showPrevForms: boolean;
}

export const ApplicationGstSettingsInitialState: ApplicationGstSettings = {
    purchaseNormalType: false,
    purchaseInterstateType: false,
    purchaseForm62: false,
    outputFormType: '',
    defaultFormTypeForPOS: '',
    inputCSTAccount: '',
    defaultPrefixForPOS: '',
    outputCSTAccount: '',
    defaultSRFormTypeForPOS: '',
    inputCessAccount: '',
    defaultSRPrefixForPOS: '',
    outputCessAccount: '',
    inputSGSTLedgerID: '',
    inputAddCessAccount: '',
    outputSGSTLedgerID: '',
    inputSGSTAccount: '',
    outputSGSTAccount: '',
    outputAddCessAccount: '',
    inputCGSTAccount: '',
    expensesTaxAccount: '',
    outputCGSTAccount: '',
    incomeTaxAccount: '',
    inputIGSTAccount: '',
    enableEWB: false,
    outputIGSTAccount: '',
    enableEInvoiceIndia: false,
    outputTCSPaidAccount: '',
    einvoiceProvider: '',
    outputTCSPayableAccount: '',
    eInvoiceAuthToken: '',
    inputCalamityCessAccount: '',
    eInvoiceOwnerID: '',
    outputSalesCalamityCessAccount: '',
    considerSalesPriceasCalamityIncluded: false,
    enableKarnatakaTaxReportFormat: false,
    showPrevForms: false,
};