export enum TransactionTitles {
  CashPayment = "cash_payment",
  CashReceipt = "cash_receipt",
  CashPaymentEstimate = "cash_payment_estimate",
  CashReceiptEstimate = "cash_receipt_estimate",
  BankPayment = "bank_payment",
  BankReceipt = "bank_receipt",
  ChequePayment = "cheque_payment",
  ChequeReceipt = "cheque_receipt",
  OpeningBalance = "opening_balance",
  JournalEntry = "journal_entry",
  MultiJournalEntry = "multi_journal_entry",
  JournalEntrySpecial = "journal_entry_special",
  DebitNote = "debit_note",
  CreditNote = "credit_note",
  TaxOnExpensePayment = "tax_on_expense_payment",
  BankReconciliation = "bank_reconciliation",
  PostDatedCheques = "post_dated_cheques",
  //inventory
  SalesInvoice = "sales_invoice",
  SalesInvoiceVAT = "VAT_sales_invoice",
  SalesReturn = "sales_return",
  SalesReturnVAT = "sales_return/credit_note(VAT)",
  SalesQuotation = "sales_quotation",
  SalesOrder = "sales_order",
  GoodsRequest = "goods_request",

  PurchaseInvoice = "purchase_invoice",
  PurchaseInvoiceVAT = "VAT_purchase_invoice",
  PurchaseEstimate = "purchase_estimate",
  PurchaseImport = "purchase_import",
  PurchaseReturn = "purchase_return",
  PurchaseReturnVAT = "purchase_return_VAT",
  PurchaseOrder = "purchase_order",
  RequestForSalesQuotation = "request_for_sales_quotation",
  PurchaseQuotation = "purchase_quotation",
  PurchaseOrderTransist = "purchase_order_transist",
  GoodsDelivery = "goods_delivery",
  GoodsDeliveryReturn = "goods_delivery_return",
  GoodsReceipt = "goods_receipt",
  GoodsReceiptReturn = "goods_receipt_return",
}
export enum TransactionListTitles {
  CashPayment = "cash_payments",
  CashReceipt = "cash_receipts",
  CashPaymentEstimate = "cash_payment_estimates",
  CashReceiptEstimate = "cash_receipt_estimates",
  BankPayment = "bank_payments",
  BankReceipt = "bank_receipts",
  ChequePayment = "cheque_payments",
  ChequeReceipt = "cheque_receipts",
  OpeningBalance = "opening_balances",
  JournalEntry = "journal_entries",
  MultiJournalEntry = "multi_journal_entries",
  JournalEntrySpecial = "journal_entry_specials",
  DebitNote = "debit_notes",
  CreditNote = "credit_notes",
  TaxOnExpensePayment = "tax_on_expense_payments",
  BankReconciliation = "bank_reconciliations",
  PostDatedCheques = "post_dated_cheques",
  //inventory
  SalesInvoices = "sales_invoices",
  SalesInvoicesVAT = "VAT_sales_invoices",
  SalesReturns = "sales_returns",
  SalesReturnsVAT = "sales_returns/credit_note(VAT)",
  SalesQuotations = "sales_quotations",
  SalesOrders = "sales_orders",
  GoodsRequests = "goods_requests",

  PurchaseInvoices = "purchase_invoices",
  PurchaseInvoicesVAT = "vat_purchase_invoices",
  PurchaseEstimates = "purchase_estimates",
  PurchaseImports = "purchase_imports",
  PurchaseReturns = "purchase_returns",
  PurchaseReturnsVAT = "purchase_returns_vat",
  PurchaseOrders = "purchase_orders",
  RequestForSalesQuotations = "request_for_sales_quotations",
  PurchaseQuotations = "purchase_quotations",
  PurchaseOrderTransists = "purchase_order_transists",
  GoodsDeliveries = "goods_deliveries",
  GoodsDeliveryReturns = "goods_delivery_returns",
  GoodsReceipts = "goods_receipts",
  GoodsReceiptReturns = "goods_receipt_returns",
}
