import VoucherType from "../../../enums/voucher-types";
import { UserAction } from "../../../helpers/user-right-helper";
import { Countries, UserModel, } from "../../../redux/slices/user-session/reducer";
import { TransactionListTitles, TransactionTitles } from "./transaction-titles";
import {
  Wallet,
  FileText,
  Receipt,
  Scale,
  NotebookPen,
  TextSelect,
  HandCoins,
  TrendingUp,
  TrendingDown,
  Banknote,
  FileSpreadsheet,
  FileSignature,
  Ship,
  ClipboardList,
  FileSearch,
  RotateCcw,
  Undo2,
  ArrowDownToLine,
  FileBadge,
  FileCheck,
  PackageCheck,
  PackageSearch,
  ReceiptText,
  ScrollText,
  ShoppingCart,
  Landmark,
  BadgeDollarSign,
  PackageOpen,
  PackagePlus,
  Package,
  PackageMinus,
  FileOutput,
  FileInput,
  ClipboardCheck,
  Wrench,
  Replace,
  FolderOpen,
  ArrowRightLeft,
  AlertTriangle,
  TrendingUpDown,
  Send,
  Download,
  ArrowUpFromLine,
  ClipboardSignature,
  ScanSearch,
} from "lucide-react";
import { TbReceipt2 } from "react-icons/tb";
import { TbReceipt } from "react-icons/tb";

export enum TransactionBase {
  Accounts = "accounts/transactions",
  Purchase = "purchase/transactions",
  Sales = "sales/transactions",
  StockJournal = "stockJournal/transactions",
  Goods = "goods/transactions",
  OtherTransactions = "otherTransactions/transactions",
}

export interface TransactionRoute {
  formCode: string;
  transactionBase: TransactionBase;
  action: UserAction;
  voucherType: string;
  transactionType: string;
  formType: string;
  title: string;
  listTitle: string;
  drCr: string;
  shortKey?: string;
  shortKeyList?: string;
  isPOS?: boolean
  icon?: any; // Changed to React.ElementType to accept Lucide icons
  visibleFn?: (userSession: UserModel) => boolean;
}

export const transactionRoutes: TransactionRoute[] = [
  {
    transactionBase: TransactionBase.Accounts,
    formCode: "CP",
    action: UserAction.Show,
    voucherType: VoucherType.CashPayment,
    transactionType: "CashPayment",
    formType: "",
    title: TransactionTitles.CashPayment,
    listTitle: TransactionListTitles.CashPayment,
    drCr: "Dr",
    shortKey: "ctrl+alt+c",
    icon: Wallet,
  },
  {
    transactionBase: TransactionBase.Accounts,
    formCode: "CR",
    action: UserAction.Show,
    voucherType: VoucherType.CashReceipt,
    transactionType: "CashReceipt",
    formType: "",
    title: TransactionTitles.CashReceipt,
    listTitle: TransactionListTitles.CashReceipt,
    drCr: "Cr",
    shortKey: "ctrl+alt+r",
    icon: HandCoins,
  },
  {
    transactionBase: TransactionBase.Accounts,
    formCode: "BP",
    action: UserAction.Show,
    voucherType: VoucherType.BankPayment,
    transactionType: "BankPayment",
    formType: "",
    title: TransactionTitles.BankPayment,
    listTitle: TransactionListTitles.BankPayment,
    drCr: "Dr",
    shortKey: "ctrl+alt+b",
    icon: Landmark,
  },
  {
    transactionBase: TransactionBase.Accounts,
    formCode: "BR",
    action: UserAction.Show,
    voucherType: VoucherType.BankReceipt,
    transactionType: "BankReceipt",
    formType: "",
    title: TransactionTitles.BankReceipt,
    listTitle: TransactionListTitles.BankReceipt,
    drCr: "Cr",
    shortKey: "ctrl+alt+k",
    icon: Banknote,
  },
  {
    transactionBase: TransactionBase.Accounts,
    formCode: "CQP",
    action: UserAction.Show,
    voucherType: VoucherType.ChequePayment,
    transactionType: "ChequePayment",
    formType: "",
    title: TransactionTitles.ChequePayment,
    listTitle: TransactionListTitles.ChequePayment,
    drCr: "Dr",
    visibleFn: (userSession: UserModel) => userSession.countryId == Countries.India,
    icon: TbReceipt2,
  },
  {
    transactionBase: TransactionBase.Accounts,
    formCode: "CQR",
    action: UserAction.Show,
    voucherType: VoucherType.ChequeReceipt,
    transactionType: "ChequeReceipt",
    formType: "",
    title: TransactionTitles.ChequeReceipt,
    listTitle: TransactionListTitles.ChequeReceipt,
    drCr: "Cr",
    visibleFn: (userSession: UserModel) => userSession.countryId == Countries.India,
    icon: TbReceipt,
  },
  {
    transactionBase: TransactionBase.Accounts,
    formCode: "OB",
    action: UserAction.Show,
    voucherType: VoucherType.OpeningBalance,
    transactionType: "OpeningBalance",
    formType: "",
    title: TransactionTitles.OpeningBalance,
    listTitle: TransactionListTitles.OpeningBalance,
    drCr: "",
    shortKey: "ctrl+alt+o",
    icon: Scale,
  },
  {
    transactionBase: TransactionBase.Accounts,
    formCode: "JV",
    action: UserAction.Show,
    voucherType: VoucherType.JournalVoucher,
    transactionType: "JournalEntry",
    formType: "",
    title: TransactionTitles.JournalEntry,
    listTitle: TransactionListTitles.JournalEntry,
    drCr: "",
    shortKey: "ctrl+alt+j",
    icon: NotebookPen,
  },
  {
    transactionBase: TransactionBase.Accounts,
    formCode: "MJV",
    action: UserAction.Show,
    voucherType: VoucherType.MultiJournal,
    transactionType: "MultiJournalEntry",
    formType: "",
    title: TransactionTitles.MultiJournalEntry,
    listTitle: TransactionListTitles.MultiJournalEntry,
    drCr: "",
    shortKey: "ctrl+alt+m",
    icon: TextSelect,
  },
  {
    transactionBase: TransactionBase.Accounts,
    formCode: "DN",
    action: UserAction.Show,
    voucherType: VoucherType.DebitNote,
    transactionType: "DebitNote",
    formType: "",
    title: TransactionTitles.DebitNote,
    listTitle: TransactionListTitles.DebitNote,
    drCr: "Dr",
    shortKey: "ctrl+alt+d",
    icon: TrendingDown,
  },
  {
    transactionBase: TransactionBase.Accounts,
    formCode: "CN",
    action: UserAction.Show,
    voucherType: VoucherType.CreditNote,
    transactionType: "CreditNote",
    formType: "",
    title: TransactionTitles.CreditNote,
    listTitle: TransactionListTitles.CreditNote,
    drCr: "Cr",
    shortKey: "ctrl+alt+n",
    icon: TrendingUp,
  },
  {
    transactionBase: TransactionBase.Accounts,
    formCode: "TXP",
    action: UserAction.Show,
    voucherType: VoucherType.TaxOnExpensePayment,
    transactionType: "TXPayment",
    formType: "VAT",
    title: TransactionTitles.TaxOnExpensePayment,
    drCr: "Dr",
    listTitle: TransactionListTitles.TaxOnExpensePayment,
    visibleFn: (userSession: UserModel) => userSession.countryId == Countries.Saudi,
    icon: BadgeDollarSign,
  },
  //#region inventory
  {
    transactionBase: TransactionBase.Sales,
    formCode: "SI",
    action: UserAction.Show,
    voucherType: VoucherType.SalesInvoice,
    transactionType: "SalesInvoice",
    formType: "",
    title: TransactionTitles.SalesInvoice,
    drCr: "Cr",
    listTitle: TransactionListTitles.SalesInvoices,
    icon: FileText,
  },
  {
    transactionBase: TransactionBase.Sales,
    formCode: "SI",
    action: UserAction.Show,
    voucherType: VoucherType.SalesInvoice,
    transactionType: "SalesInvoiceVAT",
    formType: "VAT",
    title: TransactionTitles.SalesInvoiceVAT,
    drCr: "Cr",
    listTitle: TransactionListTitles.SalesInvoicesVAT,
    visibleFn: (userSession: UserModel) => userSession.countryId !== Countries.Saudi,
    icon: ReceiptText,
  },
  {
    transactionBase: TransactionBase.Sales,
    formCode: "SR",
    action: UserAction.Show,
    voucherType: VoucherType.SalesReturn,
    transactionType: "SalesReturn",
    formType: "",
    title: TransactionTitles.SalesReturn,
    drCr: "Dr",
    listTitle: TransactionListTitles.SalesReturns,
    icon: Undo2,
  },
  {
    transactionBase: TransactionBase.Sales,
    formCode: "SR",
    action: UserAction.Show,
    voucherType: VoucherType.SalesReturn,
    transactionType: "SalesReturnVAT",
    formType: "VAT",
    title: TransactionTitles.SalesReturnVAT,
    drCr: "Dr",
    listTitle: TransactionListTitles.SalesReturnsVAT,
    visibleFn: (userSession: UserModel) => userSession.countryId !== Countries.Saudi,
    icon: RotateCcw,
  },
  {
    transactionBase: TransactionBase.Sales,
    formCode: "SQ",
    action: UserAction.Show,
    voucherType: VoucherType.SalesQuotation,
    transactionType: "SalesQuotation",
    formType: "",
    title: TransactionTitles.SalesQuotation,
    drCr: "Cr",
    listTitle: TransactionListTitles.SalesQuotations,
    icon: FileSignature,
  },
  {
    transactionBase: TransactionBase.Sales,
    formCode: "SO",
    action: UserAction.Show,
    voucherType: VoucherType.SalesOrder,
    transactionType: "SalesOrder",
    formType: "",
    title: TransactionTitles.SalesOrder,
    drCr: "Cr",
    listTitle: TransactionListTitles.SalesOrders,
    icon: ShoppingCart,
  },
  {
    transactionBase: TransactionBase.Goods,
    formCode: "GR",
    action: UserAction.Show,
    voucherType: VoucherType.GoodRequest,
    transactionType: "GoodsRequest",
    formType: "",
    title: TransactionTitles.GoodsRequest, // so
    drCr: "Cr",
    listTitle: TransactionListTitles.GoodsRequests,
    icon: PackageSearch,
  },
  {
    transactionBase: TransactionBase.Purchase,
    formCode: "PI",
    action: UserAction.Show,
    voucherType: VoucherType.PurchaseInvoice,
    transactionType: "Purchase",
    formType: "",
    title: TransactionTitles.PurchaseInvoice,
    drCr: "Dr",
    listTitle: TransactionListTitles.PurchaseInvoices,
    // visibleFn: (userSession: UserModel) => userSession.countryId !== Countries.Saudi,
    icon: FileBadge,
  },
  {
    transactionBase: TransactionBase.Purchase,
    formCode: "PI",
    action: UserAction.Show,
    voucherType: VoucherType.PurchaseInvoice,
    transactionType: "PurchaseInvoiceVAT",
    formType: "VAT",
    title: TransactionTitles.PurchaseInvoiceVAT,
    drCr: "Dr",
    listTitle: TransactionListTitles.PurchaseInvoicesVAT,
    visibleFn: (userSession: UserModel) => userSession.countryId !== Countries.Saudi,
    icon: FileSpreadsheet,
  },
  {
    transactionBase: TransactionBase.Purchase,
    formCode: "PE",
    action: UserAction.Show,
    voucherType: VoucherType.PurchaseEstimate,
    transactionType: "PurchaseEstimate",
    formType: "",
    title: TransactionTitles.PurchaseEstimate,
    drCr: "Dr",
    listTitle: TransactionListTitles.PurchaseEstimates,
    icon: ScrollText,
  },
  {
    transactionBase: TransactionBase.Purchase,
    formCode: "PI",
    action: UserAction.Show,
    voucherType: VoucherType.PurchaseInvoice,
    transactionType: "PurchaseImport",
    formType: "Import",
    title: TransactionTitles.PurchaseImport,
    drCr: "Dr",
    listTitle: TransactionListTitles.PurchaseImports,
    icon: Ship,
  },
  {
    transactionBase: TransactionBase.Purchase,
    formCode: "PR",
    action: UserAction.Show,
    voucherType: VoucherType.PurchaseReturn,
    transactionType: "PurchaseReturn",
    formType: "",
    title: TransactionTitles.PurchaseReturn,
    drCr: "Cr",
    listTitle: TransactionListTitles.PurchaseReturns,
    icon: ArrowDownToLine,
  },
  {
    transactionBase: TransactionBase.Purchase,
    formCode: "PR",
    action: UserAction.Show,
    voucherType: VoucherType.PurchaseReturn,
    transactionType: "PurchaseReturnVAT",
    formType: "VAT",
    title: TransactionTitles.PurchaseReturnVAT,
    drCr: "Cr",
    listTitle: TransactionListTitles.PurchaseReturnsVAT,
    visibleFn: (userSession: UserModel) => userSession.countryId !== Countries.Saudi,
    icon: FileCheck,
  },
  {
    transactionBase: TransactionBase.Purchase,
    formCode: "PO",
    action: UserAction.Show,
    voucherType: VoucherType.PurchaseOrder,
    transactionType: "PurchaseOrder",
    formType: "",
    title: TransactionTitles.PurchaseOrder,
    drCr: "Dr",
    listTitle: TransactionListTitles.PurchaseOrders,
    icon: ClipboardList,
  },
  // request for sales
  {
    transactionBase: TransactionBase.Sales,
    formCode: "RFQ",
    action: UserAction.Show,
    voucherType: VoucherType.RequestForQuotation,
    transactionType: "RequestForQuotation",
    formType: "",
    title: TransactionTitles.RequestForSalesQuotation, //so
    drCr: "Cr",
    listTitle: TransactionListTitles.RequestForSalesQuotations,
    icon: ClipboardSignature,
  },
   // Created for pos - need to change later
  {
    transactionBase: TransactionBase.Sales,
    formCode: "RFQ",
    isPOS: true,
    action: UserAction.Show,
    voucherType: VoucherType.SalesInvoice,
    transactionType: "SalesInvoice",
    formType: "",
    title: "POS",
    drCr: "Cr",
    listTitle: TransactionListTitles.SalesInvoices,
    icon: HandCoins,
  },
  {
    transactionBase: TransactionBase.Purchase,
    formCode: "PQ",
    action: UserAction.Show,
    voucherType: VoucherType.PurchaseQuotation,
    transactionType: "PurchaseQuotation",
    formType: "",
    title: TransactionTitles.PurchaseQuotation,
    drCr: "Dr",
    listTitle: TransactionListTitles.PurchaseQuotations,
    icon: FileSearch,
  },
  // {
  //   transactionBase: TransactionBase.Purchase,
  //   formCode: "POT",
  //   action: UserAction.Show,
  //   voucherType: VoucherType.PurchaseOrderTransist,
  //   transactionType: "PurchaseOrderTransist",
  //   formType: "",
  //   title: TransactionTitles.PurchaseReturn,
  //   drCr: "Dr",
  //   listTitle: TransactionListTitles.PurchaseReturns,
  //   icon: Truck,
  // },
  {
    transactionBase: TransactionBase.Goods,
    formCode: "GD",
    action: UserAction.Show,
    voucherType: VoucherType.GoodsDeliveryNote,
    transactionType: "GoodsDelivery",
    formType: "",
    title: TransactionTitles.GoodsDelivery,
    drCr: "Cr",
    listTitle: TransactionListTitles.GoodsDeliveries,
    icon: Send,
  },
  {
    transactionBase: TransactionBase.Goods,
    formCode: "DR",
    action: UserAction.Show,
    voucherType: VoucherType.GoodsDeliveryReturn,
    transactionType: "GoodsDeliveryReturn",
    formType: "",
    title: TransactionTitles.GoodsDeliveryReturn, //GRR
    drCr: "Cr",
    listTitle: TransactionListTitles.GoodsDeliveryReturns,
    icon: ArrowUpFromLine,
  },
  {
    transactionBase: TransactionBase.Goods,
    formCode: "GRN",
    action: UserAction.Show,
    voucherType: VoucherType.GoodsReceiptNote,
    transactionType: "GoodsReceipt",
    formType: "",
    title: TransactionTitles.GoodsReceipt,
    drCr: "Dr",
    listTitle: TransactionListTitles.GoodsReceipts,
    icon: Download,
  },
  {
    transactionBase: TransactionBase.Goods,
    formCode: "GRR",
    action: UserAction.Show,
    voucherType: VoucherType.GoodsReceiptReturn,
    transactionType: "GoodsReceiptReturn",
    formType: "",
    title: TransactionTitles.GoodsReceiptReturn, //GDR
    drCr: "Cr",
    listTitle: TransactionListTitles.GoodsReceiptReturns,
    icon: PackageCheck,
  },
  {
    transactionBase: TransactionBase.OtherTransactions,
    formCode: "SRV",
    action: UserAction.Show,
    voucherType: VoucherType.ServiceInventory,
    transactionType: "ServiceInventory",
    formType: "",
    title: TransactionTitles.Service,
    drCr: "Dr",
    listTitle: TransactionListTitles.Services,
    icon: Wrench,
  },
  {
    transactionBase: TransactionBase.OtherTransactions,
    formCode: "SUB",
    action: UserAction.Show,
    voucherType: VoucherType.DamageExpirySubstitute,
    transactionType: "Substitute",
    formType: "",
    title: TransactionTitles.Substitute,
    drCr: "Dr",
    listTitle: TransactionListTitles.Substitutes,
    icon: Replace,
  },
  //#region stock journal
  {
    transactionBase: TransactionBase.StockJournal,
    formCode: "OS",
    action: UserAction.Show,
    voucherType: VoucherType.OpeningStock,
    transactionType: "OpeningStock",
    formType: "",
    title: TransactionTitles.OpeningStock,
    drCr: "Dr",
    listTitle: TransactionListTitles.OpeningStocks,
    icon: FolderOpen,
  },
  {
    transactionBase: TransactionBase.StockJournal,
    formCode: "ST",
    action: UserAction.Show,
    voucherType: VoucherType.StockTransfer,
    transactionType: "StockTransfer",
    formType: "",
    title: TransactionTitles.StockTransfer,
    drCr: "Dr",
    listTitle: TransactionListTitles.StockTransfers,
    icon: ArrowRightLeft,
  },
  {
    transactionBase: TransactionBase.StockJournal,
    formCode: "DMG",
    action: UserAction.Show,
    voucherType: VoucherType.DamageEntry,
    transactionType: "DamageEntry",
    formType: "",
    title: TransactionTitles.DamageEntry,
    drCr: "Dr",
    listTitle: TransactionListTitles.DamageEntries,
    icon: AlertTriangle,
  },
  {
    transactionBase: TransactionBase.StockJournal,
    formCode: "EX",
    action: UserAction.Show,
    voucherType: VoucherType.ExcessStock,
    transactionType: "ExcessStock",
    formType: "",
    title: TransactionTitles.ExcessStockAddStock,
    drCr: "Dr",
    listTitle: TransactionListTitles.ExcessStocksAddStocks,
    icon: PackagePlus,
  },
  {
    transactionBase: TransactionBase.StockJournal,
    formCode: "SH",
    action: UserAction.Show,
    voucherType: VoucherType.ShortageStock,
    transactionType: "ShortageStock",
    formType: "",
    title: TransactionTitles.ShortageStockLessStock,
    drCr: "Dr",
    listTitle: TransactionListTitles.ShortageStocksLessStocks,
    icon: PackageMinus,
  },
  //check
  {
    transactionBase: TransactionBase.StockJournal,
    formCode: "SA",
    action: UserAction.Show,
    voucherType: VoucherType.StockAdjuster,
    transactionType: "StockAdjuster",
    formType: "",
    title: TransactionTitles.StockAdjuster,
    drCr: "Dr",
    listTitle: TransactionListTitles.StockAdjusters,
    icon: TrendingUpDown,
  },
  {
    transactionBase: TransactionBase.StockJournal,
    formCode: "BTO",
    action: UserAction.Show,
    voucherType: VoucherType.BranchTransferOut,
    transactionType: "BranchTransferOut",
    formType: "",
    title: TransactionTitles.BranchTransferOut,
    drCr: "Dr",
    listTitle: TransactionListTitles.BranchTransferOuts,
    icon: FileOutput,
  },
  {
    transactionBase: TransactionBase.StockJournal,
    formCode: "BTI",
    action: UserAction.Show,
    voucherType: VoucherType.BranchTransferIn,
    transactionType: "BranchTransferIn",
    formType: "",
    title: TransactionTitles.BranchTransferIn,
    drCr: "Dr",
    listTitle: TransactionListTitles.BranchTransferIns,
    icon: FileInput,
  },
  //check
  {
    transactionBase: TransactionBase.StockJournal,
    formCode: "SI",
    action: UserAction.Show,
    voucherType: VoucherType.SalesInvoice,
    transactionType: "StockTransferToBranch",
    formType: "BT",
    title: TransactionTitles.StockTransferToBranch,
    drCr: "Dr",
    listTitle: TransactionListTitles.StockTransfersToBranch,
    icon: PackageOpen,
  },
  {
    transactionBase: TransactionBase.StockJournal,
    formCode: "PI",
    action: UserAction.Show,
    voucherType: VoucherType.PurchaseInvoice,
    transactionType: "StockTransferFromBranch",
    formType: "BT",
    title: TransactionTitles.StockTransferFromBranch,
    drCr: "Dr",
    listTitle: TransactionListTitles.StockTransfersFromBranch,
    icon: Package,
  },
  {
    transactionBase: TransactionBase.StockJournal,
    formCode: "ILR",
    action: UserAction.Show,
    voucherType: VoucherType.ItemLoadRequest,
    transactionType: "ItemLoadRequest",
    formType: "",
    title: TransactionTitles.ItemLoadRequest,
    drCr: "Dr",
    listTitle: TransactionListTitles.ItemLoadRequests,
    icon: ClipboardCheck,
  },
  {
    transactionBase: TransactionBase.StockJournal,
    formCode: "SC",
    action: UserAction.Show,
    voucherType: VoucherType.StockCount,
    transactionType: "StockCount",
    formType: "",
    title: TransactionTitles.StockCount,
    drCr: "Dr",
    listTitle: TransactionListTitles.StockCounts,
    icon: ScanSearch,
  },
  //#endregion stock journal
  {
    transactionBase: TransactionBase.OtherTransactions,
    formCode: "SVI",
    action: UserAction.Show,
    voucherType: VoucherType.ServiceInvoice,
    transactionType: "ServiceInvoice",
    formType: "VAT",
    title: TransactionTitles.ServiceInvoice,
    drCr: "Cr",
    listTitle: TransactionListTitles.ServiceInvoices,
    icon: Receipt,
  },
  // 3 pending post transaction ,sales view ,packing slip
  //#endregion Inventory
];

export const exludedRoutes = [
  { title: TransactionTitles.ChequePayment, countries: [Countries.Saudi] },
  { title: TransactionTitles.ChequeReceipt, countries: [Countries.Saudi] },
  { title: TransactionTitles.TaxOnExpensePayment, countries: [Countries.India], },
  { title: TransactionTitles.PurchaseInvoiceVAT, countries: [Countries.India] },
  { title: TransactionTitles.PurchaseReturnVAT, countries: [Countries.India] },
];

export const isChooseVoucherEnabled = (title: string, userSession: UserModel) =>
  [
    { title: TransactionTitles.CashPayment, countries: [Countries.Saudi] },
    { title: TransactionTitles.CashReceipt, countries: [Countries.Saudi] },
    { title: TransactionTitles.BankPayment, countries: [Countries.Saudi] },
    { title: TransactionTitles.BankReceipt, countries: [Countries.Saudi] },
    { title: TransactionTitles.OpeningBalance, countries: [Countries.Saudi] },
    { title: TransactionTitles.JournalEntry, countries: [Countries.Saudi] },
    { title: TransactionTitles.DebitNote, countries: [Countries.Saudi] },
    { title: TransactionTitles.CreditNote, countries: [Countries.Saudi] },
    { title: TransactionTitles.PurchaseInvoice, countries: [Countries.India] },
    { title: TransactionTitles.PurchaseReturn, countries: [Countries.India] },
    { title: TransactionTitles.PurchaseOrder, countries: [Countries.India] },
    { title: TransactionTitles.PurchaseEstimate, countries: [Countries.India] },
    { title: TransactionTitles.PurchaseQuotation, countries: [Countries.India], },
    //{ title: TransactionTitles.PurchaseImport, countries: [Countries.India] },
    { title: TransactionTitles.PurchaseReturn, countries: [Countries.Saudi] },
    { title: TransactionTitles.MultiJournalEntry, countries: [Countries.Saudi], },
  ].find(
    (x) => userSession.countryId != undefined && x.title == title && (x.countries == undefined || (x.countries != undefined && x.countries.find((x) => x == userSession.countryId) != undefined))
  );