export enum TransactionTitles {
  CashPayment = "cash_payment",
  CashReceipt = "cash_receipt",
  CashPaymentEstimate = "cash_payment_estimate",
  CashReceiptEstimate = "cash_receipt_estimate",
  BankPayment = "bank_payment",
  BankReceipt = "bank_receipt",
  ChequePayment = "cheque_payment",
  ChequeReceipt = "cheque_receipt",
  OpeningBalance = "opening_balance",
  JournalEntry = "journal_entry",
  MultiJournalEntry = "multi_journal_entry",
  JournalEntrySpecial = "journal_entry_special",
  DebitNote = "debit_note",
  CreditNote = "credit_note",
  TaxOnExpensePayment = "tax_on_expense_payment",
  BankReconciliation = "bank_reconciliation",
  PostDatedCheques = "post_dated_cheques",

  PurchaseInvoice = "purchase_invoice",
}
export enum TransactionListTitles {
  CashPayment = "cash_payments",
  CashReceipt = "cash_receipts",
  CashPaymentEstimate = "cash_payment_estimates",
  CashReceiptEstimate = "cash_receipt_estimates",
  BankPayment = "bank_payments",
  BankReceipt = "bank_receipts",
  ChequePayment = "cheque_payments",
  ChequeReceipt = "cheque_receipts",
  OpeningBalance = "opening_balances",
  JournalEntry = "journal_entries",
  MultiJournalEntry = "multi_journal_entries",
  JournalEntrySpecial = "journal_entry_specials",
  DebitNote = "debit_notes",
  CreditNote = "credit_notes",
  TaxOnExpensePayment = "tax_on_expense_payments",
  BankReconciliation = "bank_reconciliations",
  PostDatedCheques = "post_dated_cheques",

  PurchaseInvoices = "purchase_invoices",
}