export const initialEmployee = {
  data: {
    employeeID: 0,
    employeeCode: "",
    employeeName: "",
    shortName: "",
    gender: "",
    designationID: 0,
    accLedgerID: 0,
    doj: "",
    probotion_Period: 0,
    isActive: false,
    isNameChanged: false,
    address1: "",
    address2: "",
    address3: "",
    stateName: "",
    pin: "",
    phone: "",
    mobile: "",
    email: "",
    nationality: "",
    bloodGroup: "",
    passportNo: "",
    passportExpDate: "",
    visaDetails: "",
    visaExpDate: "",
    dob: "",
    isResign: false,
    resignDate: "",
    qualification: "",
    notes: "",
    remarks: "",
    windowsEmpImage: "",
    wageType: "",
    wageAmt: 0,
    cl: 0,
    da: 0,
    pf: 0,
    incentivePerc: 0,
    otAmount: 0,
    totalWorkingHrs: 0,
    costCentreID: 0,
    salesTarget: 0,
    designationName: "",
    costCentre: "",
  },
  validations: {
    employeeID: "",
    employeeCode: "",
    employeeName: "",
    shortName: "",
    gender: "",
    designationID: "",
    accLedgerID: "",
    doj: "",
    probotion_Period: "",
    isActive: "",
    isNameChanged: "",
    address1: "",
    address2: "",
    address3: "",
    stateName: "",
    pin: "",
    phone: "",
    mobile: "",
    email: "",
    nationality: "",
    bloodGroup: "",
    passportNo: "",
    passportExpDate: "",
    visaDetails: "",
    visaExpDate: "",
    dob: "",
    isResign: "",
    resignDate: "",
    qualification: "",
    notes: "",
    remarks: "",
    windowsEmpImage: "",
    wageType: "",
    wageAmt: "",
    cl: "",
    da: "",
    pf: "",
    incentivePerc: "",
    otAmount: "",
    totalWorkingHrs: "",
    costCentreID: "",
    salesTarget: "",
    designationName: "",
    costCentre: "",
  },
};
export interface Employee {
  employeeID: number;
  employeeCode: string;
  employeeName: string;
  shortName: string;
  gender: string;
  designationID: number;
  accLedgerID: number;
  doj: string;
  probotion_Period: number;
  isActive: boolean;
  isNameChanged: boolean;
  address1: string;
  address2: string;
  address3: string;
  stateName: string;
  pin: string;
  phone: string;
  mobile: string;
  email: string;
  nationality: string;
  bloodGroup: string;
  passportNo: string;
  passportExpDate: string;
  visaDetails: string;
  visaExpDate: string;
  dob: string;
  isResign: boolean;
  resignDate: string;
  qualification: string;
  notes: string;
  remarks: string;
  windowsEmpImage: string;
  wageType: string;
  wageAmt: number;
  cl: number;
  da: number;
  pf: number;
  incentivePerc: number;
  otAmount: number;
  totalWorkingHrs: number;
  costCentreID: number;
  salesTarget: number;
  designationName: string;
  costCentre: string;
}

