// purchaser
// warehouse
// round
// purchaser
// warning
// success
// error
//net_value
// item_used_for_service_report
// free_of_cost_reports_of
// fast_moving_products
// purchase_period
// unsold_product_report
// selected_range
// lpo_report
// routewise_sales_collection_report
// inventory_status_report
// stock_journal_reports
// customer_visit_reports
// discount_report_collection
// collection_discount_report
// discount_report_inventory
// customer_visit_total_visit
// customer_visit_last_visit
// fast_moving_products
// unsoled_products
// lpo_report
// routewise_sales_collection
// inventory_status
// void_report
// stock_journal_reports
// sales_other_reports