import moment from "moment";
import { Dispatch } from "react";
import { AnyAction } from "redux";
import { inputBox } from "../../../../redux/slices/app/types";
import { TemplateState } from "../../../InvoiceDesigner/Designer/interfaces";
import { TransactionMaster, TransactionValidationsData, TransactionDetail, TransactionMaster3, FormElementState, TransactionFormState, SummaryItems, TransactionData, BarcodeLabel, ProductDisplayDto, EmployeeType, TransactionDetails2 } from "./transaction-types";
import { generateUniqueKey } from "../../../../utilities/Utils";


// Initial object with default values
export const initialTransactionMasterValidations: TransactionValidationsData = {
  master: {},
  // master3: {},
  details: [],
  attachments: []
};
export const TransactionMaster3InitialData: TransactionMaster3 = {
  totSchemeDiscount: 0.0,
  totSGST: 0.0,
  totCGST: 0.0,
  totIGST: 0.0,
  totCess: 0.0,
  totAdditionalCess: 0.0,
  totCalamityCess: 0.0,
  totTCS: 0.0,
  totTDS: 0.0,
  shipLegalName: "",
  shipTradeName: "",
  shipGstIn: "",
  shipPinCode: 0,
  shipAddress1: "0",
  shipAddress2: "0",
  shipLocation: "0",
  shipStateCode: 0,
  invTransactionMasterID: 0,
  branchID: 0
}
export const initialInventoryTotals: SummaryItems = {
  qty: 0,
  gross: 0,
  netValue: 0,
  discount: 0,
  vatAmount: 0,
  cst: 0,
  total: 0,
  profit: 0,
  grossFc: 0,
  totalAddExpense: 0,
  nosQty: 0,
  pCode: '',
  barCode: '',
  margin: 0,
  salesPrice: '',
  cgst: 0,
  sgst: 0,
  igst: 0,
  cessAmt: 0,
  additionalCess: 0
};
export const initialTransactionDetails2: TransactionDetails2 = {
  invTransactionDetailID: 0,
  branchID: 0,
  cessPerc: 0,
  cessAmt: 0,
  sgstPerc: 0,
  sgst: 0,
  cgstPerc: 0,
  cgst: 0,
  igstPerc: 0,
  igst: 0,
  calamityCessPerc: 0,
  calamityCess: 0,
  additionalCessPerc: 0,
  additionalCess: 0,
};
export const TransactionMasterInitialData: TransactionMaster = {
  invTransactionMasterID: 0,
  branchID: 0,
  financialYearID: 0,
  counterID: 0,
  employeeID: 0,
  createdUserID: 0,
  inventoryLedgerID: 0,
  ledgerID: 0,
  partyName: "",
  displayName: "",
  referalAgentID: 0,
  tableId: 0,
  seatNumber: "",
  tokenNumber: "",
  kotMasterID: 0,
  noOfGuests: 0,
  deviceCode: "",
  address1: "",
  address2: "",
  address3: "",
  address4: "",
  voucherPrefix: "",
  voucherNumber: 0,
  transactionDate: new Date().toISOString(),
  remarks: "",
  fromWarehouseID: 0,
  toWarehouseID: 0,
  voucherType: "",
  voucherForm: "",
  orderNumber: 0,
  orderDate: new Date().toISOString(),
  quotationNumber: "",
  quotationDate: new Date().toISOString(),
  dueDate: new Date().toISOString(),
  deliveryNoteNumber: "",
  deliveryDate: new Date().toISOString(),
  purchaseInvoiceNumber: "",
  purchaseInvoiceDate: new Date().toISOString(),
  despatchDocumentNumber: "",
  despatchDate: new Date().toISOString(),
  vehicleID: 0,
  driverID: 0,
  salesManID: 0,
  deliveryManID: 0,
  totalGross: 0,
  totalDiscount: 0,
  billDiscount: 0,
  grandTotal: 0,
  grandTotalFc: 0,
  totalProfit: 0,
  roundAmount: 0,
  cashReceived: 0,
  cashReturned: 0,
  srAmount: 0,
  salesManIncentive: 0,
  advanceAmt: 0,
  shortageAmount: 0,
  adjustmentAmount: 0,
  stockUpdate: true,
  accUpdate: true,
  gatePassNo: "",
  vatAmount: 0,
  isLocked: false,
  counterShiftID: 0,
  priceCategoryID: 0,
  refBranchID: 0,
  refInvTransactionMasterID: 0,
  isPosted: true,
  privCardID: 0,
  privAddAmount: 0.0,
  privRedeem: 0.0,
  orderCardNo: 0,
  isInvoiced: true,
  mannualInvoiceNumber: "",
  inout: "",
  cashAmt: 0.0,
  bankAmt: 0.0,
  creditAmt: 0.0,
  currencyID: 1,
  exchangeRate: 1.0,
  costCentreID: 0,
  cashrOrCredit: "",
  couponAmt: 0.0,
  projectID: 0,
  // currencyID:0,
  labelDesignID: 0,
  customerType: "",
  taxOnDiscount: 0.0,
  draftTransactionMasterID: 0,
  randomKey: 0,
  tableNo: "",
  employeeName: "",
  deliveryMan: "",
  pdtVerified: "",
  pdtRemarks: "0",
  counterName: "",
  creditCardDetails: "",
  cashTip: 0.0,
  cardTip: 0.0,
  notes1: "",
  notes2: "",
  // referenceDate: new Date().toISOString(),
  // referenceNumber: "",
  particulars: "",
  lb: true,
  hasCashPaid: false,
  hasroundOff: false,
  supplyType: "",
  prevTransDate: "",
  oldLedgerID: 0,
  dueDays: 0,
  gRNMasterID: 0,
  master3: TransactionMaster3InitialData
}
export const initialTransactionDetailData: TransactionDetail = {
  slNo: "",
  pCode: '',
  mrp: 0,
  barCode: '',
  productBatchID: 0,
  product: '',
  productID: 0,
  brand: '',
  brandID: 0,
  qty: 0,
  free: 0,
  unit: '',
  unitID: 0,
  unitPrice: 0,
  gross: 0,
  discPerc: 0,
  discount: 0,
  netValue: 0,
  total: 0,
  stock: 0,
  manualBarcode: '',
  stockDetails: '',
  margin: 0,
  salesPrice: 0,
  lpr: 0,
  lpc: 0,
  stickerQty: 0,
  profit: 0,
  size: '',
  vatPerc: 0,
  vatAmount: 0,
  cst: 0,
  cstPerc: 0,
  cost: 0,
  batchNo: '',
  mfdDate: '', // Use new Date() if you prefer Date type
  expDate: '',
  expDays: 0,
  bd: '',
  btnPrintBarcode: '',
  barcodePrinted: false,
  batchCreated: false,
  removeCol: false,
  productDescription: '',
  serial: '',
  minSalePrice: 0,
  additionalExpense: 0,
  unitPriceFC: 0,
  colour: '',
  warranty: '',
  nosQty: 0,
  totalAddExpense: 0,
  grossConvert: 0,
  grossFC: 0,
  unitID2: 0,
  unit2Qty: 0,
  unit2SalesRate: 0,
  unit2MRP: 0,
  unit2MBarcode: '',
  unit2StickerQty: 0,
  unitID3: 0,
  unit3Qty: 0,
  unit3SalesRate: 0,
  unit3MRP: 0,
  unit3MBarcode: '',
  unit3StickerQty: 0,
  tagQty: 0,
  barcodeTagPrinted: false,
  barcodeUnit2Printed: false,
  barcodeUnit3Printed: false,
  location: '',
  grTransDetailsID: 0,
  arabicName: '',
  supplierReferenceProductCode: '',
  poTransDetailsID: 0,
  ratePlusTax: 0,
  warehouseID: 0,
  sortOrder: 0,
  profitPercentage: 0,
  schemeDiscount: 0,
  memo: '',
  memoEditor: '',
  rowNumber: 0,
  actualSalesPrice: 0,
  unit2: '',
  unit3: '',
  btnPrintBarcodeStd: '',
  poTransDetailsIDTag: 0,
  warehouseName: "",
  unitPriceTag: 0,
  unitDecimalPoint: 0,
  multiFactor: 0,
  details2: initialTransactionDetails2,
  hsnCode: ""
};
export const transactionInitialData: TransactionData = {
  master: TransactionMasterInitialData, details: Array.from({ length: 30 }, (_, index) => ({
    ...initialTransactionDetailData,
    slNo: generateUniqueKey()
  })),
  attachments: [],
  masterValidations: initialTransactionMasterValidations,
  invAccTransactions: []
};

export const initialFormElements: { [key: string]: FormElementState } = {
  voucherPrefix: { visible: true, disabled: true, label: "prefix" },
  voucherNumber: { visible: true, disabled: false, label: "voucher_number" },
  voucherNumberUpDownBtns: { visible: true, disabled: false, label: "voucher_number" },
  btnDown: { visible: true, disabled: false, label: "" },
  transactionDate: {
    visible: true,
    disabled: false,
    label: "transaction_date",
  },
  referenceNumber: {
    visible: true,
    disabled: false,
    label: "reference_number",
  }, employee: { visible: true, disabled: false, label: "purchaser" },
  pnlMasters: { visible: true, disabled: false, label: "" },
  partyCode: { visible: true, disabled: false, label: "code" },
  ledgerID: { visible: true, disabled: false, label: "party" },
  invoiceValue: { visible: true, disabled: false, label: "invoice_value" },
  dxGrid: { visible: true, disabled: false, label: "" },
  referenceDate: { visible: true, disabled: false, label: "reference_date" },
  btnBarcode: { visible: true, disabled: false, label: "barcode" },
  btnDelete: { visible: true, disabled: true, label: "delete" },
  btnEdit: { visible: true, disabled: true, label: "edit" },
  btnError: { visible: false, disabled: false, label: "error" },
  btnGRNPrint: { visible: true, disabled: false, label: "grn_print" },
  btnPrint: { visible: true, disabled: false, label: "print" },
  btnProductSummary: { visible: true, disabled: false, label: "product_sumary" },
  btnSave: { visible: true, disabled: true, label: "save" },
  btnSet: { visible: false, disabled: false, label: "set" },
  btnSize: { visible: false, disabled: false, label: "size" },
  btnbrowse: { visible: true, disabled: true, label: "browse" },
  cbBrand: { visible: true, disabled: false, label: "brand" },
  cbColour: { visible: false, disabled: false, label: "color" },
  cbCostCentre: { visible: false, disabled: false, label: "cost_centre" },
  cbDummyCode: { visible: false, disabled: false, label: "dummy_code" },
  cbEmployee: { visible: true, disabled: false, label: "purchaser", employeeType: EmployeeType.All},
  cbDebitAccount: { visible: true, disabled: false, label: "" },
  chkDebitAccount: { visible: true, disabled: false, label: "debit_account" },
  chkTaxNumber: { visible: true, disabled: false, label: "" },
  cbProject: { visible: true, disabled: false, label: "project" },
  cbCurrency: { visible: true, disabled: false, label: "currency" },
  cbWarehouse: { visible: false, disabled: false, label: "warehouse" },
  cbWarranty: { visible: false, disabled: false, label: "warranty" },
  chkDummyBillWithInventory: { visible: false, disabled: false, label: "dummy_bill_with_inventory" },
  chkIsLocked: { visible: false, disabled: false, label: "is_locked" },
  chkRound: { visible: true, disabled: false, label: "round" },
  chkSelectDebitAccount: { visible: true, disabled: true, label: "select_debit_account" },
  chkTemporaryVATNumber: { visible: true, disabled: false, label: "temporary_vat_number" },
  dgvInventory: { visible: true, disabled: false, label: "" },
  dgvProduct: { visible: false, disabled: false, label: "", params: "" },
  dgvProductBatches: { visible: false, disabled: false, label: "", params: "" },
  productSearchPopupWindow: { visible: false, disabled: false, label: "product_search_popup_window", data: { searchCriteria: 'Code', searchText: "", voucherType: "", warehouseId: 0, inSearch: false } },
  lblPosted: { visible: false, disabled: false, label: "posted" },
  lblTotFC: { visible: false, disabled: false, label: "tot_fc" },
  lblWarehouse: { visible: false, disabled: false, label: "warehouse" },
  lblproductName: { visible: true, disabled: false, label: "product_name" },
  linklblpath: { visible: true, disabled: true, label: "path" },
  pnlAmountSummary: { visible: true, disabled: false, label: "amount_summary" },
  pnlBatch: { visible: false, disabled: false, label: "batch" },
  pnlBatchUnitDetails: { visible: false, disabled: false, label: "batch_unit_details" },
  pnlGRN: { visible: false, disabled: false, label: "grn" },
  pnlImport: { visible: false, disabled: false, label: "import" },
  pnlLoadVoucher: { visible: false, disabled: false, label: "load_voucher" },
  pnlMore: { visible: false, disabled: false, label: "more" },
  pnlProductBatches: { visible: false, disabled: false, label: "product_batches" },
  pnlProductInfo: { visible: false, disabled: false, label: "product_info" },
  pnlSearch: { visible: false, disabled: false, label: "search" },
  pnlSettings: { visible: false, disabled: false, label: "settings" },
  pnlSize: { visible: false, disabled: false, label: "size" },
  // productCombo: { visible: true, disabled: false, label: "product_combo" },
  progressBar1: { visible: false, disabled: false, label: "progressbar1" },
  //saveButton1: { visible: false, disabled: true, label: "save_button1" },
  txtData: { visible: true, disabled: false, label: "txt_data" },
  txtDespatchNo: { visible: true, disabled: false, label: "despatch_no" },
  txtFilePath: { visible: true, disabled: true, label: "file_path" },
  txtFindBarcode: { visible: false, disabled: false, label: "find_barcode" },
  printOnSave: { visible: false, disabled: false, label: "print_on_save" },
  lnkUnlockVoucher: { visible: false, disabled: false, label: "Unlock" },
  asasa: { visible: true, disabled: false, label: "dfdf" },
  cbWarehouseID: { visible: true, disabled: false, label: "warehouse" },
  remarks: { visible: true, disabled: false, label: "remarks" },
  lb: { visible: true, disabled: false, label: "lb" },
  priceCategory: { visible: true, disabled: false, label: "price_category" },
  adjustmentAmount: { visible: true, disabled: false, label: "add_amount_or_jv" },
  roundOff: { visible: true, disabled: false, label: "round_off" },
  totTCS: { visible: true, disabled: false, label: "tot_tcs" },
  grandTotalFc: { visible: false, disabled: false, label: "grand_total_fc" },
  netAmount: { visible: true, disabled: false, label: "net_value" },
  billDiscount: { visible: true, disabled: false, label: "bill_discount" },
  exchangeRate: { visible: true, disabled: false, label: "exchange_rate" },
  hasCashPaid: { visible: true, disabled: false, label: "cash_paid" },
  isLocked: { visible: true, disabled: false, label: "lb" },
  autoCalculation: { visible: true, disabled: false, label: "auto_calculation" },
  supplyType: { visible: true, disabled: false, label: "supply_type" },
  totTax: { visible: true, disabled: false, label: "tot_tax" },
  grandTotal: { visible: true, disabled: false, label: "grand_total" },
  netTotal: { visible: true, disabled: false, label: "net_total" },
  chkVat: { visible: true, disabled: false, label: "#_vat" },
  cbVatAccount: { visible: true, disabled: false, label: "" },
  inSearch: { visible: true, disabled: false, label: "in_search" },
  cbLabelDesign: { visible: true, disabled: false, label: "label_design" },
  orderStatus: { visible: false, disabled: false, label: "order_status" },
  orderApprovalStatus: { visible: false, disabled: false, label: "" },

};
export const TransactionFormStateInitialData: TransactionFormState = {
  formCode: "",
  isEntryControl: false,
  isEdit: false,
  dtLedgerCodes: [],
  showSaveDialog: false,
  isInvoker: false,
  title: "",
  rowProcessing: false,
  transactionProcessing: false,
  transactionLoading: true,
  transaction: transactionInitialData,
  printOnSave: false,
  printPreview: false,
  printCheque: false,
  amountInWords: 'Zero Only',
  openUnsavedPrompt: false,
  priceCategory: "",
  summary: initialInventoryTotals,
  remarks: "",
  userConfig: {
    clearDetailsAfterSaveAccounts: true,
    keepNarrationForJV: true,
    mnuShowConfirmationForEditOnAccounts: true,
    maximizeBillwiseScreenInitially: true,
    alignment: "center",
    presetCostenterId: 0,
    counterAssignedCashLedgerId: 0,
    maxWidth: "",
    outerPageBg: "",
    innerPageBg: "",
    useBarcode: false,
    resizeGrid: false,
    showProductInfoPopup: false,
    showPurchaserOnly: false,
    useSupplierProductCode: false,
    enableItemCodeSearchInNameColumn: false,
    holdSameCode: false,
    printPreview: false,
    duplicationMessage: false,
    setDefaultQuantity: false,
    inputBoxStyle: {
      inputStyle: "normal",
      inputSize: "sm",
      checkButtonInputSize: "sm",
      inputHeight: 0,
      fontSize: 14,
      fontWeight: 400,
      labelFontSize: 14,
      otherLabelFontSize: 14,
      inputBgColor: "255, 255, 255",
      borderColor: "128, 128, 128",
      buttonFocusBg: "89, 137, 232",
      selectColor: "255, 255, 255",
      fontColor: "128, 128, 128",
      labelColor: "128, 128, 128",
      borderFocus: "128, 128, 128",
      borderRadius: 4,
      adjustA: 0,
      adjustB: 0,
      adjustC: 0,
      adjustD: 0,
      marginTop: 8,
      marginBottom: 6,
      focusForeColor: "128, 128, 128",
      focusBgColor: "255, 255, 255",
      bold: true
    },
  },
  unlocking: false,
  total: 0,
  isRowEdit: false,
  // formElements: initialFormElements
  ledgerDataLoading: false,
  ledgerData: undefined,
  ledgerBalanceLoading: false,
  ledgerBalance: 0,
  groupName: undefined,
  formElements: initialFormElements,
  saving: false,
  store: undefined,
  templatesData: [],
  transactionType: "",
  prev: "",
  showPartySelection: false,
  customerType: "",
  partyId: "",
  foreignCurrency: false,
  enableDebitAccount: false,
  inSearch: false,
  enableTaxNumber: false,
  netTotal: 0,
  netAmount: 0,
  loadData: {
    formType: undefined,
    vPrefix: undefined,
    vNumber: undefined
  },
  isProductSummaryOpen: false,
  isPartyWiseSummaryOpen: false,
  isFormStateDetailOpen: false,
  selectedRow: undefined,
  userRightsFormCode: "",
  isPostedTransaction: false,
  isInv: false,
  summaryConfig: [
    {
      column: "qty",
      summaryType: "sum",
      valueFormat: "decimal",
    },
    {
      column: "gross",
      summaryType: "sum",
      valueFormat: "currency",
    },
    {
      column: "netValue",
      summaryType: "sum",
      valueFormat: "currency",
    },
    {
      column: "discount",
      summaryType: "sum",
      valueFormat: "currency",
    },
    {
      column: "vatAmount",
      summaryType: "sum",
      valueFormat: "currency",
    },
    {
      column: "cst",
      summaryType: "sum",
      valueFormat: "currency",
    },
    {
      column: "total",
      summaryType: "sum",
      valueFormat: "currency",
    },
    {
      column: "profit",
      summaryType: "sum",
      valueFormat: "currency",
    },
    {
      column: "grossFC",
      summaryType: "sum",
      valueFormat: "currency",
    },
    {
      column: "totalAddExpense",
      summaryType: "sum",
      valueFormat: "currency",
    },
    {
      column: "nosQty",
      summaryType: "sum",
      valueFormat: "decimal",
    },
    {
      column: "pCode",
      summaryType: "count",
      valueFormat: "decimal",
    },
    {
      column: "barCode",
      summaryType: "count",
      valueFormat: "decimal",
    },
    {
      column: "margin",
      summaryType: "sum",
      valueFormat: "currency",
    },
    {
      column: "salesPrice",
      summaryType: "sum",
      valueFormat: "currency",
    },

    {
      column: "details2.cessPerc",
      summaryType: "sum",
      valueFormat: "currency",
    },
    {
      column: "details2.cessAmt",
      summaryType: "sum",
      valueFormat: "currency",
    },
    {
      column: "details2.sgstPerc",
      summaryType: "sum",
      valueFormat: "currency",
    },
    {
      column: "details2.sgst",
      summaryType: "sum",
      valueFormat: "currency",
    },

    {
      column: "details2.cgstPerc",
      summaryType: "sum",
      valueFormat: "currency",
    },
    {
      column: "details2.cgst",
      summaryType: "sum",
      valueFormat: "currency",
    },
    {
      column: "details2.igstPerc",
      summaryType: "sum",
      valueFormat: "currency",
    },
    {
      column: "details2.igst",
      summaryType: "sum",
      valueFormat: "currency",
    },
  ],
  showQuantityFactors: { visible: false, rowIndex: 0 },
  batchSelectionData: "",
  popupSearchSelectionData: "",
  showPcode: false,
  quantityFactorData: "",
  batchEntryData: { visible: false, data: "", rowIndex: -1 },
  serialNoEntryData: { visible: false, data: "", rowIndex: -1 },
  productInfo: false,
  ShowProductBatchUnitDetails: false,
  ledgerDetails: false,
  dummyProducts: false,
  dataWarranty: [],
  dataBrands: [],
  isPopupVisible: false,
  gridColumns: [],
  showGridTheme: false,
  // stockUpdate: false
}

export const initialProductData: BarcodeLabel = {
  labelCount: 1,
  productCode: "",
  productName: "",
  arabicName: "",
  salesPrice: "",
  salesPrice2: "",
  salesPrice3: "",
  cost: "",
  autoBarcode: "",
  manualBarcode: "",
  costCode: "",
  note1: "",
  note2: "",
  note3: "",
  note4: "",
  unit: "",
  unitRemarks: "",
  unit1Remarks: "",
  unit2Remarks: "",
  unit3Remarks: "",
  qty: "",
  salesPriceWithVAT: "",
  salesPrice2WithVAT: "",
  salesPrice3WithVAT: "",
  batchNo: "",
  expiryDate: "",
  partNumber: "",
  mfdDate: "",
  packingDate: "",
  warrantyPeriod: "",
  expiryDays: "",
  brand: "",
  groupName: "",
  specification: "",
  itemAliasName: "",
  unit2: "",
  unit2SalesPrice: "",
  unit3: "",
  unit3SalesPrice: "",
  partyCode: "",
  productDescription: "",
  voucherNo: "",
  transDate: "",
  siNo: "",
  size: "",
  productId: 0,
  invQty: 0,
  isCalculate: false,
  reQty: 0.00,
  vatPerc: 0,
  pPrice: 0,
  mrp: 0,
  msp: 0,
  sPrice: 0,
  showPreview: false,
  pluCode: ""
};
export const initialProductDisplayData: ProductDisplayDto = {
  productName: "",
  productCode: "",
  groupName: "",
  productCategoryName: "",
  unitName: "",
  stockMin: "",
  stockMax: "",
  itemType: "",
  mfgDate: "",
  expiryDate: "",
  batchNo: "",
  warehouseName: "",
  brandName: "",
  autoBarcode: "",
  stdSalesPrice: "",
  stdPurchasePrice: "",
  stock: "",
  minSalePrice: "",
  image: ""
};