// export const domain = "http://localhost:5000";
export const domain = "https://erpapi.polosys.shabeerali.dev";
// export const domain = "https://tgerp.bustime.app";
// export const domain = import.meta.env.VITE_DOMAIN;
export const signupUrl = import.meta.env.VITE_SIGNUP;
export const companyName = import.meta.env.VITE_COMPANY_NAME;

export const cdnUrl = import.meta.env.VITE_CDN_URL;
export const projectName = import.meta.env.VITE_PROJECT_NAME;

console.log(`Urls,  : project_name_data`, projectName);

const Urls = {
  domain,
  upload: "/",
  user: "/user",
  imgBaseUrl: "/",
  host: `${domain}/`,
  baseUrl: `${domain}/api`,

  ///erp
  login: "/token/",
  language: "/settings/language/",
  country: "/settings/country/",
  state: "/settings/state/",

  dashboard: "/dashboard/home/",
  bar_graph: "/dashboard/home/graph/",
  pie_chart: "/dashboard/home/pie_chart/",
  cash_flow_diagram: "/dashboard/home/cash_flow/",

  /// Company
  companies: "/companies/company/",
  countries: "/settings/country/",
  states: "/settings/state/",
  currency: "/settings/currency/",
  currencies: "/settings/currency-tenant/",
  default_currencies: "/settings/default-currency/",
  exchange_rates: "/settings/exchange-rate/",
  base_currency_adjustment: "/settings/base-currency-adjustment/",
  base_currency_reevaluate: "/settings/base-currency-adjustment-item/revaluate/",
  base_balance_get: "/settings/base-currency-adjustment/balance_get/",
  adjust_base_currency: "/settings/base-currency-adjustment-item/",
  timezone: "/settings/timezone/",
  branch_address: "/companies/branch-address/",

  /// Items
  items: "/items/item/",
  items_all: "/items/item-all/",
  items_total_list: "/items/item-list/",
  items_all_list: "/items/item-alternate/",
  barcode_generate: "/items/item/barcode_generate/",
  price_list: "/items/item-price-list/",
  unit_class: "/items/item-unit-class/",
  item_unit: "/items/item-unit/",
  uom: "/items/item-unit/",
  item_search: "/items/find_item_details/get_details/",
  brand: "/items/item-brand/",
  category: "/items/item-category/",
  itemimage: "/items/item-image/",
  items_import: "/items/item/imports/",

  /// inventory
  inventory_adjustment: "/inventories/inventory-adjustment/",
  inventory_adjustment_reason: "/inventories/inventory-adjustment-reason/",

  // sales Menu
  customer: "/peoples/customers/",

  // Full List Data (No Paginations)
  customer_list: "/peoples/customer-list/",
  vendor_list: "/peoples/vendor-list/",
  currency_list: "/settings/currency-list/",
  place_of_supply_list: "/settings/place-of-supply-list/",
  payment_mode_cash_bank_list: "/settings/payment-modes/cash_bank_list/",
  uom_list: "/items/item-unit-list/",
  peoples_list: "/peoples/people-list/",
  tax_treatment_list: "/settings/tax-treatment-list/",
  payment_terms_list: "/settings/payment-terms-list/",
  default_currencies_list: "/settings/default-currency-list/",
  tax_category_list: "/taxes/tax-category-list/",
  tax_due: "/taxes/tax-file/",
  tax_payment: "/taxes/tax-payment/",
  country_list: "/settings/country-list/",
  language_list: "/settings/language-list/",
  fiscal_year_list: "/settings/fiscal-year-list/",
  brand_list: "/items/item-brand-list/",
  category_list: "/items/item-category-list/",
  price_lists: "/items/item-price-lists/",
  delivery_challan_types_list: "/sales/delivery-challan-types-list/",
  payment_mode_list: "/settings/payment-modes-list/",
  recurring_invoice_frequency_list: "/sales/recurring-invoice-frequency-list/",
  source_of_supply_list: "/settings/source-of-supply-list/",
  employees_list: "/peoples/employees-list/",
  recurring_expence_frequency_list: "/purchases/recurring_expense_frequency-list/",
  recurring_bills_frequency_list: "/purchases/recurring_purchase_invoice_frequency-list/",
  recurring_journal_frequency_list: "/journals/recurring_journal_frequency-list/",
  sales_person_list: "/peoples/sales-person-list/",

  customer_invoice_voucher: "peoples/customers/invoice_transaction/",
  customer_payment_voucher: "peoples/customers/payment_transactions/",
  customer_credits_apply: "/vouchers/sales-invoice-voucher/apply_credits_customer/",
  vendor_credits_apply: "/vouchers/purchase-invoice-voucher/apply_credits_customer/",
  customer_all_voucher: "peoples/customers/all_transactions/",
  ar_aging_summary: "reports/ar_aging_summary/",
  ar_aging_detail: "reports/ar_aging_detail/",
  estimates_list: "/sales/list_estimated_orders",
  estimates: "/sales/estimates/",
  invoices: "/sales/invoices/",
  all_invoices: "/sales/invoices-all/",
  all_bills: "/purchases/bills-all/",
  sale_order: "/sales/orders/",
  credit_note: "/sales/credit-note/",
  recurring_invoice: "/sales/recurring-invoice/",
  delivery_chellans: "/sales/delivery-challans/",
  payements_received: "/vouchers/receipt-voucher/",
  retainer_invoice_apply: "/vouchers/retainer-invoice-receipt/apply_invoice/",
  applied_invoices: "/vouchers/retainer-invoice-receipt/applied_invoices/",
  sales_return_apply: "/vouchers/sales-invoice-voucher/apply/",
  vendor_credit_apply: "/vouchers/purchase-invoice-voucher/apply/",
  retainer_record_payment: "/vouchers/retainer-invoice-receipt/",
  sales_return: "/sales/sales-returns/",
  retainer_invoice: "/sales/retainer-invoice/",
  sales_order_cancel: "/sales/sales-order-cancel/",
  sales_refund: "/sales/refund/",
  retainer_refund: "/sales/retainer-refund/",
  payment_received_refund: "/vouchers/receipt-voucher-refund/",
  payment_made_refund: "/vouchers/payment-voucher-refund/",
  sales_invoice_voucher: "/vouchers/sales-invoice-voucher/",
  excess_payment_voucher: "/vouchers/excess-payment-voucher/",
  debit_excess_payment_voucher: "/vouchers/debit-excess-payment-voucher/",
  debit_note_voucher: "/vouchers/debit-note-voucher/",
  debit_notes: "/sales/debit-note/",
  write_off: "/sales/writeoff/",

  // purchase Menu
  peoples: "/peoples/people/",
  vendors: "/peoples/vendors/",
  ap_aging_summary: "/reports/ap_aging_summary/",
  ap_aging_detail: "/reports/ap_aging_detail/",
  expenses: "/purchases/expense/",
  purchase_order: "/purchases/orders/",
  bills: "/purchases/invoices/",
  credit_notes_purchase: "/purchases/credit-notes/",
  vendor_credits: "/purchases/vendor_credits/",
  payments_made: "/vouchers/payment-voucher/",
  reccuring_expense: "/purchases/recurring_expense/",
  recuring_expense_entity: "/purchases/recurring_expense_entity_type/",
  recurring_expence_frequency: "/purchases/recurring_expense_frequency/",
  recurring_bills: "/purchases/recurring_purchase_invoice/",
  recurring_bills_entity: "/purchases/recurring_purchase_invoice_entity_type/",
  recurring_bills_frequency: "/purchases/recurring_purchase_invoice_frequency/",
  bill_type: "/purchases/bill-type/",
  purchase_order_cancel: "/purchases/purchase-order-cancel/",
  allocate_landed_cost_multiple: "purchases/allocate/multiple/",
  allocate_landed_cost_multiple_delete: "purchases/allocate/multiple_delete/",
  allocate_landed_cost: "purchases/allocate/",
  vendor_credit_refund: "/purchases/vendor-credit-refund/",
  bill_of_entry: "/purchases/bill-of-entry/",

  voucher: "/voucher/voucher-number/",
  unpaid_invoice: "/vouchers/receipt-voucher/unpaid_invoices/",
  unpaid_vouchers: "/vouchers/receipt-voucher/unpaid_vouchers/",
  unpaid_payment_vouchers: "/vouchers/payment-voucher/unpaid_vouchers/",
  expense_category: "/finance/expense_category/",
  repeat_master: "/sales/recurring-invoice-frequency/",
  challan_type: "/finance/delivery-challan-master/",
  bulk_update: "/finance/bulk-update/",
  bulk_account_update: "/finance/ledger/bulk_update/",

  sales_person: "/peoples/sales-person/",
  payment_terms: "/settings/payment-terms/",
  payment_terms_configure: "/settings/payment-terms/configure/",

  file_attachment: "/file_attachment/file_attachment/",
  file_attachment_folder: "/file_attachment/folder/",
  file_attachment_trash: "/file_attachment/trash/",
  file_attachment_voucher: "/file_attachment/file_attachment/get_by_voucher/",
  documents: "/settings/general-document/",

  // Accountant
  chart_of_accounts: "/finance/chart_of_accounts/",
  chart_of_accounts_by_type: "/finance/chart_of_accounts/account_get_by_account_type/",
  chart_of_account_expense: "/finance/chart_of_accounts/expense_accounts/",
  chart_of_accounts_expense_paid_through: "/finance/chart_of_accounts/paid_through_accounts/",
  chart_of_accounts_by_code: "/finance/chart_of_accounts/account_get_by_code/",
  chart_of_accounts_group: "finance/chart_of_accounts/account_groups",
  chart_of_accounts_ledger: "finance/chart_of_accounts/account_ledger",
  chart_of_accounts_ledgers: "finance/chart_of_account/",
  account_transactions: "/reports/transactions/",
  account_transaction: "/reports/account-transaction/",
  chart_of_account_transactions: "/reports/transactions/transaction_list/",
  transaction_locking: "/finance/ledger/transaction_lock/",
  transaction_lock_list: "/finance/ledger/transaction_lock_list/",
  transaction_lock_list_all: "/finance/ledger/transaction_lock_list_all/",
  transaction_lock_all: "/finance/ledger/transaction_lock_all/",
  transaction_unlock_all: "/finance/ledger/transaction_unlock_all/",
  transaction_unlock: "/finance/ledger/transaction_unlock/",
  disable_unlock: "/finance/ledger/disable_unlock/",
  disable_unlock_all: "/finance/ledger/disable_unlock_all/",
  account_balance: "/finance/ledger/ledger_balance/",

  // Preferences
  general_preference: "/preferences/general/",
  accountant_preference: "/preferences/account/",
  item_preference: "/preferences/item/",
  customer_and_vendor_preference: "/preferences/customer_vendor/",
  estimate_preference: "/preferences/estimate/",
  retainer_preference: "/preferences/retainer/",
  delivery_challan_preference: "/preferences/delivery-challan/",
  sales_invoice_preference: "/preferences/sales-invoice/",
  sales_order_preference: "/preferences/sales-order/",
  recurring_invoice_preference: "/preferences/recurring-invoice/",
  purchase_order_preference: "/preferences/purchase-order/",
  credit_note_preference: "/preferences/credit-note/",
  expense_preference: "/preferences/expense/",
  delivery_note_preference: "/preferences/delivery-note/",
  packing_slip_preference: "/preferences/packing-slip/",

  // Settings
  email_to: "/settings/mail-history/send_mail/",
  contact_person: "/peoples/contact-person/",
  opening_balance: "/finance/opening-balance/",
  opening_balance_customers: "/finance/opening-balance/customers/",
  opening_balance_vendors: "/finance/opening-balance/vendors/",
  tax_list: "/taxes/tax-category/",
  tax_settings: "/taxes/tax-settings/",
  tax_split: "/taxes/tax-category-split/",
  source_of_supply: "/settings/source-of-supply/",
  bulk_mail: "/settings/mail-history/send_bulk_mail/",
  notifications: "/settings/notifications/",
  mark_as_read_notifications: "/settings/notifications/mark_read/",

  payment_mode: "/settings/payment-modes/",
  payment_mode_cash: "/settings/payment-modes/cash/",
  payment_mode_cash_bank: "/settings/payment-modes/cash_bank/",
  bank_accounts: "/settings/bank-accounts/",
  delivery_challan_types: "/sales/delivery-challan-types/",
  reporting_tags: "/reporting_tag/reporting_tag/",
  place_of_supply: "/settings/place-of-supply/",
  fiscal_year: "/settings/fiscal-year/",
  currency_exchange: "/settings/currency-exchange-rate/",

  tax_treatment: "/settings/tax-treatment/",
  voucher_prefix: "/settings/voucher-prefix/",
  voucher_type_number: "/settings/voucher-prefix/get_prefix/",
  voucher_type_chart_of_account: "/finance/chart_of_accounts/get_prefix_company/",

  users: "/users/user/",
  owner: "/users/customer_owner/",
  user_invitations: "/users/user-invitations/",
  my_invitations: "/users/user-invitations/my_invitations/",
  export_fields: "users/export-fields/",
  approval_user: "/sales/approval-user/",
  templates: "users/user-templates/",
  user_logs: "settings/activity-log/",
  user_link: "/users/user-link/",

  /*  Listing Page control */
  user_table_listing: "users/user-table-fields/",
  custom_filter_list: "custom/custom-filter-list/",
  custom_filters: "custom/custom-filters/",

  customer_templates: "/peoples/customer-templates/",
  vendor_templates: "/peoples/vendor-templates/",

  // Apply Voucher
  retainer_invoices_apply: "/vouchers/retainer-invoice-voucher/apply/",
  debit_retainer_invoices_apply: "/vouchers/debit-retainer-invoice-voucher/apply/",
  applied_retainer_invoices: "/vouchers/retainer-invoice-voucher/",
  applied_debit_retainer_invoices: "/vouchers/debit-retainer-invoice-voucher/",
  sales_returns_apply: "/vouchers/sales-return-voucher/apply/",
  debit_sales_returns_apply: "/vouchers/debit-sales-return-voucher/apply/",
  applied_credits: "/vouchers/sales-return-voucher/",
  applied_debit_note_credits: "/vouchers/debit-sales-return-voucher/",
  opening_balance_delete: "/vouchers/customer-opening-voucher/",
  apply_vendor_credit: "/vouchers/vendor-credit-voucher/",
  apply_credit_note_delete: "/vouchers/credit-note-voucher/",
  apply_credit_note_vendor_credit: "/vouchers/vendor-credit-voucher-credit/",
  vendor_credit_opening_delete: "/vouchers/vendor-opening-voucher/",

  // Supporting API
  branch: "/companies/branch/",
  credit_reasons: "/sales/credit-note-reasons/",
  entity_type: "/sales/recurring-invoice-entity-type/",
  invoice_outstanding_receivables: "/sales/invoices/outstanding_summary/",
  partial_return: "/sales/delivery-challan-return/",
  vendor_credit_voucher: "/vouchers/purchase-invoice-voucher/",
  vendor_excess_payment: "/vouchers/vendor-excess-payment-voucher/",

  // Supporting API
  comments: "/comments/comment/",
  multiple_vendor_delete: "/peoples/vendors/multiple_delete/",
  create_retainer_invoice: "/sales/retainer-invoice/create_retainer/",
  retainer_invoices: "/sales/estimates/retainer_invoices/",
  retainer_invoice_voucher: "",
  applied_invoice_delete: "/vouchers/retainer-invoice-receipt/delete_invoice/",
  delete_record_payment: "/vouchers/retainer-invoice-receipt/delete_payment/",
  additional_address: "/peoples/additional-address/",

  // Users
  password_reset: "/users/password_reset",
  password_reset_confirm: "/users/reset-password/",
  social_signup: "/users/social-signup",
  user_profile: "/users/user-profile/",
  user_companies: "/users/user-company/",
  user_current_tenant: "/users/user-company/set_current_tenant/",
  user_fields: "/users/user-fields/",

  //subscriptions
  user_role: "/subscriptions/user-role/",
  permission_master: "/subscriptions/permission-master/",

  // Profile
  address: "/peoples/customers/",
  employees: "/peoples/employees/",
  address_post: "/peoples/address/",
  address_vendor: "/peoples/vendors/",
  address_type: "/peoples/address-type/",

  // Sample Data Populations
  polulate_data: "/sample-data/populate-data/",
  flush_data: "/sample-data/flush-data/",
  chart_of_account_tree: "/finance/chart_of_accounts/chart_of_account_tree/",

  // Unpaid
  unpaid_retainers: "/vouchers/receipt-voucher/unpaid_retainer/",
  unpaid_returns: "/vouchers/receipt-voucher/unpaid_sales_returns/",
  unpaid_vendor_credits: "/vouchers/payment-voucher/unpaid_vendor_credit/",

  // Journal
  journal: "/journals/journal/",
  journal_template: "/journals/journal-template/",
  recurring_journal: "/journals/recurring_journal/",
  recurring_journal_frequency: "/journals/recurring_journal_frequency/",
  recurring_journal_entity_type: "/journals/recurring_journal_entity_type/",

  // Reports
  generalledger: "/reports/general-ledger/",
  sales_by_customer: "/reports/sales-by-customer/",
  sales_order_by_item: "/reports/sales-order-by-item/",
  sales_by_customer_details: "/reports/sales-by-customer/details/",
  sales_by_items: "/reports/sales-by-item/",
  sales_by_salesperson: "/reports/sales-by-salesperson/",
  account_day_book: "/reports/account-daybook/",
  activity_exeption: "/reports/activity-exception/",
  api_usage: "/reports/api-usage/",
  bill_details: "/reports/bill-details/",
  billable_expence_details: "/reports/billable-expense-details/",
  cash_flow: "/reports/cash-flow/",
  customer_balance: "/reports/customer-balance/",
  customer_balance_summary: "/reports/customer-balance-summary/",
  dellivery_challan_details: "/reports/delivery-challan-details/",
  estimate_details: "/reports/estimate-details/",
  expense_by_category: "/reports/expense-by-category/",
  expense_by_category_details: "/reports/expense-by-category/details/",
  expense_by_customer: "/reports/expense-by-customer/",
  expense_by_customer_details: "/reports/expense-by-customer/details/",
  expense_details: "/reports/expense-details/",
  inventory_summary: "/reports/inventory-summary/",
  inventory_aging_summary: "/reports/inventory-aging/",
  invoice_details: "/reports/invoice-details/",
  payable_details: "/reports/payable-details/",
  payable_summary: "/reports/payable-summary/",
  payment_made: "/reports/payment-made/",
  product_sale: "/reports/product-sales/",
  profit_and_loss: "/reports/profit-loss-statement/",
  purchase_details_by_vendor: "/reports/purchase-by-vendor/details/",
  purchase_by_item: "/reports/purchase-by-item/",
  purchase_details_by_item: "/reports/purchase-by-item/details/",
  purchase_order_by_vendor: "/reports/purchase-order-by-vendor/",
  purchase_order_by_vendor_details: "/reports/purchase-order-by-vendor/details/",
  purchase_order_details: "/reports/purchase-order-details/",
  receivable_details: "/reports/receivable-details/",
  receivable_summary: "/reports/receivable-summary/",
  sales_order_details: "/reports/sales-order-details/",
  stock_summary: "/reports/stock-summary/",
  system_mails: "/reports/system-mails/",
  mail_history: "/settings/mail-history/",
  tax_summary: "/reports/tax-summary/",
  transaction: "/reports/transactions/",
  journal_transactions: "/reports/transactions/list_by_voucher/",
  transactions: "/reports/transactions/child_transaction/",
  vendor_balance: "/reports/vendor-balance/",
  vendor_balance_details: "/reports/vendor-balance/details/",
  vendor_balance_summary: "/reports/vendor-balance-summary/",
  vendor_credit_details: "/reports/vendor-credit-details/",
  vendor_invoice_voucher: "peoples/vendors/invoice_transaction/",
  vendor_payment_voucher: "peoples/vendors/payment_transactions/",
  vendor_all_voucher: "peoples/vendors/all_transactions/",
  balace_sheet: "/reports/balance-sheet/",
  movement_of_equity: "/reports/movement_of_equity/",
  business_ratio: "/reports/business_ratio/",
  activity_log: "/reports/activity-log/",
  client_review: "/reports/client-reviews/",
  expense_by_employee: "/reports/expense-by-employee/",
  account_type_transaction: "/reports/account-type-transaction/",
  trial_balance: "/reports/trial-balance/",
  sales_by_item_details: "/reports/sales-by-item/details/",
  sales_order_by_item_details: "/reports/sales-order-by-item/details/",
  favourites: "/reports/favourite-report/",
  sales_by_salesperson_details: "/reports/sales-by-salesperson/details/",
  purchase_by_vendor: "/reports/purchase-by-vendor/",
  commited_stock_details: "/reports/commited-stock/",
  inventory_valuation_summary: "/reports/inventory-valuation/",
  inventory_valuation_summary_details: "/reports/inventory-valuation/details/",
  landed_cost_summary: "/reports/landed_cost_summary/",
  abc_classification: "/reports/abc_classification/",
  journal_report: "/reports/journal-report/",
  payments_received_report: "/reports/payment-received/",
  credit_note_details: "/reports/credit-note-details/",
  refund_history: "/reports/refund/",
  payment_refund_history: "/reports/payment-made-refund/",
  acccount_type_summary: "/reports/account-type-summary/",
  recurring_invoice_details: "/reports/recurring_invoice_details/",
  retainer_invoice_details: "/reports/retainer_invoice_details/",
  profit_and_loss_shedule: "/reports/profit_loss_schedule/",
  balance_sheet_schedule: "/reports/balance_sheet_schedule/",
  scheduled_frequency: "/reports/scheduled-frequency/",
  scheduled_report: "/reports/scheduled-report/",
  customize_report: "reports/customize/",
  tax_return_details: "/reports/tax-return",
  tax_return_details_report: "reports/tax-return/details",
  tax_file: "/taxes/tax-file/",
  realized_gain: "/reports/realized-gain/",
  unrealized_gain: "/reports/unrealized-gain/",
  fifo_tracking: "/reports/fifo/",

  /////////////////// Email Templates /////////////
  email_template: "/users/user-email/",
  send_mail: "/users/user-email/send_mail/",
  clear_attachment: "/users/user-email/clear_attachment_file/",
  reminder: "/users/reminder/",
  reminder_details: "/users/reminder-details/",
  reminder_get: "/users/reminder/reminder_get/",
  reminder_send: "/users/reminder/send_mail/",
  schedule_mail: "/users/schedule-email/",
  share_report: "/reports/sharedreport/multiple/",
  share_report_list: "/reports/sharedreport/",

  // // ============== Banking Apis ====================
  bank_account_graph: "/settings/bank-accounts/graph/",
};

export default Urls;
