export interface PartiesData {
  partyID: number,
  branchID: number,
  ledgerID: number,
  partyCode: string,
  partyName: string,
  displayName: string,
  address1: string,
  address2: string,
  address3: string,
  address4: string,
  officePhone: string,
  workPhone: string,
  mobilePhone: string,
  contactPhone: string,
  faxNumber: string,
  webURL: string,
  email: string,
  billwiseBillApplicable: boolean,
  creditDays: number,
  creditAmount: number,
  priceCategoryID: number,
  formTypeID: number,
  partyPhoto: string,
  startDate?: Date,
  expiryDate?: Date,
  isActive: boolean,
  taxNumber: string,
  cstNumber: string,
  modifiedUserID: number,
  partyCategoryID: number,
  salesRouteID: number,
  isCommon: boolean,
  document1: string,
  document2: string,
  bankAcNumber1: string,
  bankAcName1: string,
  bankDetails1: string,
  bankAcNumber2: string,
  bankAcName2: string,
  bankDetails2: string,
  documentName1: string,
  documentName2: string,
  stopCredit: boolean,
  arabicName: string,
  buildingNumber: string,
  plotIdentificationNumber: string,
  postalCode: string,
  citySubDivision: string,
  country: string,
  countrySubEntity: string,
  idType: string,
  idNumber: string,
  legalName: string,
  tradeName: string,
  registrationType: string,
  aadharNo: string,
  panNo: string,
  stateName: string,
  stateCode: string,
  tcsCategoryID: number,
  partyType: string,
  createdUserID: number,
  visitSequenceNo: number,
  accGroupID: number
}
export const initialPartiesData = {
  data: {
    partyID: 0,
    branchID: 0,
    ledgerID: 0,
    ledgerName: "",
    partyCode: "",
    partyName: "",
    displayName: "",
    address1: "",
    address2: "",
    address3: "",
    address4: "",
    officePhone: "",
    workPhone: "",
    mobilePhone: "", 
    contactPhone: "",
    faxNumber: "",
    webURL: "",
    email: "",
    billwiseBillApplicable: false,
    creditDays: 0,
    creditAmount: 0,
    priceCategoryID: 0,
    formTypeID: 0,
    partyPhoto: "",
    startDate: new Date(),
    expiryDate: new Date(),
    isActive: true,
    taxNumber: "",
    cstNumber: "",
    modifiedUserID: 0,
    partyCategoryID: 0,
    salesRouteID: 0,
    isCommon: false,
    document1: "",
    document2: "",
    bankAcNumber1: "",
    bankAcName1: "",
    bankDetails1: "",
    bankAcNumber2: "",
    bankAcName2: "",
    bankDetails2: "",
    documentName1: "",
    documentName2: "",
    stopCredit: false,
    arabicName: "",
    buildingNumber: "",
    plotIdentificationNumber: "",
    postalCode: "",
    citySubDivision: "",
    country: "",
    countrySubEntity: "",
    idType: "",
    idNumber: "",
    legalName: "",
    tradeName: "",
    registrationType: "",
    aadharNo: "",
    panNo: "",
    stateName: "",
    stateCode: "",
    tcsCategoryID: 0,
    partyType: "",
    drCr: "",
    createdUserID: 0,
    visitSequenceNo: 0,
    accGroupID: 0
    
  },
  validations: {
    partyID: "",
    branchID: "",
    ledgerID: "",
    ledgerName: "",
    partyCode: "",
    partyName: "",
    displayName: "",
    address1: "",
    address2: "",
    address3: "",
    address4: "",
    officePhone: "",
    workPhone: "",
    mobilePhone: "",
    contactPhone: "",
    faxNumber: "",
    webURL: "",
    email: "",
    billwiseBillApplicable: "",
    creditDays: "",
    creditAmount: "",
    priceCategoryID: "",
    formTypeID: "",
    partyPhoto: "",
    startDate: "",
    expiryDate: "",
    isActive: "",
    taxNumber: "",
    cstNumber: "",
    modifiedUserID: "",
    partyCategoryID: "",
    salesRouteID: "",
    isCommon: "",
    document1: "",
    document2: "",
    bankAcNumber1: "",
    bankAcName1: "",
    bankDetails1: "",
    bankAcNumber2: "",
    bankAcName2: "",
    bankDetails2: "",
    documentName1: "",
    documentName2: "",
    stopCredit: "",
    arabicName: "",
    buildingNumber: "",
    plotIdentificationNumber: "",
    postalCode: "",
    citySubDivision: "",
    country: "",
    countrySubEntity: "",
    idType: "",
    idNumber: "",
    legalName: "",
    tradeName: "",
    registrationType: "",
    aadharNo: "",
    drCr: "",
    panNo: "",
    stateName: "",
    stateCode: "",
    tcsCategoryID: "",
    partyType: "",
    createdUserID: "",
    visitSequenceNo: "",
    accGroupID: ""
  },
};

export interface ProjectOrJob{
projectName:string;
address1:string;
address2:string;
address3:string;
}

export const initialProjectOrJobData= {
  data:{
    projectName:"",
    address1:"",
    address2:"",
    address3:"",
  },
  validation:{
    projectName:"",
    address1:"",
    address2:"",
    address3:"",
  }
}