import VoucherType from "../../../../enums/voucher-types";
import {
  Countries,
  UserModel,
} from "../../../../redux/slices/user-session/reducer";
import { ApplicationSettingsType } from "../../../settings/system/application-settings-types/application-settings-types";
import { ColumnModel, TransactionFormState } from "../transaction-types";
// voucherType ?? formState.transaction.master.voucherType
// formType ?? formState.transaction.master.voucherForm
export const stockGridColItemLoadRequest = (
  applicationSettings: ApplicationSettingsType,
  userSession: UserModel,
  voucherType: string,
  formType: string,
  t: any,
  formState: TransactionFormState
) =>
  [
    {
      dataField: "slNo",
      caption: "",
      dataType: "number",
      width: 40,
      isLocked: true,
      alignment: "center",
    },
    {
      dataField: "productID",
      caption: t("product_id"),
      dataType: "number",
      width: 100,
      readOnly: true,
      alignment: "right",
      visible: false,
    },
    {
      dataField: "productBatchID",
      caption: t("item_batch_id"),
      dataType: "number",
      width: 200,
      readOnly: true,
      alignment: "right",
      visible: false,
    },
    {
      dataField: "pCode",
      caption: t("code"),
      dataType: "string",
      allowEditing: true,
      width: 150,
      alignment: "left",
    },
    {
      dataField: "barCode",
      caption: t("barcode"),
      dataType: "string",
      allowEditing: true,
      width: 150,
      alignment: "left",
    },

    {
      dataField: "product",
      caption: t("product_name"),
      dataType: "string",
      allowEditing: true,
      width: 250,
      alignment: "left",
    },
    {
      dataField: "productDescription",
      caption: t("product_description"),
      dataType: "string",
      width: 250,
      readOnly: true,
      alignment: "left",
      visible: false,
    },
    {
      dataField: "qty",
      caption: t("qty"),
      dataType: "number",
      allowEditing: true,
      width: 100,
      alignment: "right",
    },
    {
      dataField: "unitID",
      caption: t("unit_id"),
      detailsOptionKey: "units",
      allowEditing: true,
      visible: false,
      width: 100,
      alignment: "right",
    },
    {
      dataField: "unit",
      idField: "unitID",
      caption: t("unit"),
      dataType: "cb",
      width: 150,
      alignment: "left",
      allowEditing: true,
      readOnly: true,
    },
    {
      dataField: "stock",
      caption: t("stock"),
      dataType: "number",
      readOnly: true,
      width: 100,
      alignment: "right",
      decimalPoint: 4,
    },
    {
      dataField: "cost",
      caption: t("cost"),
      dataType: "number",
      decimalPoint: applicationSettings.mainSettings.decimalPoints,
      readOnly: true,
      width: 100,
      alignment: "right",
    },
    {
      dataField: "salesPrice",
      caption: t("s_price"),
      dataType: "number",
      allowEditing: true,
      width: 200,
      alignment: "right",
      readOnly: true,
      decimalPoint: applicationSettings.mainSettings.decimalPoints,
    },
    {
      dataField: "batchNo",
      caption: t("batch"),
      dataType: "string",
      width: 150,
      alignment: "left",
    },
    {
      dataField: "expDate",
      caption: t("expiry_date"),
      dataType: "date",
      width: 100,
      format: "DD-MMM-YYYY",
      alignment: "left",
    },
    {
      dataField: "fromWhouseStock",
      caption: t("from_w_house_stock"),
      dataType: "string",
      width: 150,
      alignment: "left",
      visible: false,
    },
    {
      dataField: "toWhouseStock",
      caption: t("to_w_house_stock"),
      dataType: "string",
      width: 150,
      alignment: "left",
      visible: false,
    },
    {
      dataField: "brandID",
      field: { valueKey: "id", labelKey: "name" },
      caption: t("brand_id"),
      dataType: "number",
      width: 100,
      readOnly: false,
      allowEditing: true,
      alignment: "right",
      visible: false,
    },
    {
      dataField: "brand",
      caption: t("brand"),
      idField: "brand",
      dataType: "cb",
      field: { valueKey: "name", labelKey: "name" },
      width: 150,
      alignment: "left",
      allowEditing: true,
      visible: false,
    },

    {
      dataField: "actionCol",
      caption: "",
      dataType: "boolean",
      width: 55,
      readOnly: true,
      isLocked: true,
      alignment: "center",
    },
  ] as ColumnModel[];
