import VoucherType from "../../../../enums/voucher-types";
import {
  Countries,
  UserModel,
} from "../../../../redux/slices/user-session/reducer";
import { ApplicationSettingsType } from "../../../settings/system/application-settings-types/application-settings-types";
import { ColumnModel, TransactionFormState } from "../transaction-types";
// voucherType ?? formState.transaction.master.voucherType
// formType ?? formState.transaction.master.voucherForm
export const stockGridColStockAdjuster = (
  applicationSettings: ApplicationSettingsType,
  userSession: UserModel,
  voucherType: string,
  formType: string,
  t: any,
  formState: TransactionFormState
) =>
  [
    {
      dataField: "slNo",
      caption: "",
      dataType: "number",
      width: 40,
      isLocked: true,
      alignment: "center",
    },
    {
      dataField: "pCode",
      caption: t("code"),
      dataType: "string",
      allowEditing: true,
      width: 150,
      alignment: "left",
    },
    {
      dataField: "barCode",
      caption: t("barcode"),
      dataType: "string",
      allowEditing: true,
      width: 150,
      alignment: "left",
    },
    {
      dataField: "productBatchID",
      caption: t("item_batch_id"),
      dataType: "number",
      width: 200,
      readOnly: true,
      alignment: "right",
      visible: false,
    },
    {
      dataField: "product",
      caption: t("product"),
      dataType: "string",
      allowEditing: true,
      width: 250,
      alignment: "left",
    },
    {
      dataField: "qty",
      caption: t("qty"),
      dataType: "number",
      allowEditing: true,
      width: 100,
      alignment: "right",
    },
    {
      dataField: "unit",
      idField: "unitID",
      caption: t("unit"),
      dataType: "cb",
      width: 150,
      alignment: "left",
      allowEditing: true,
      readOnly: true,
    },
    {
      dataField: "productID",
      caption: t("product_id"),
      dataType: "number",
      width: 100,
      readOnly: true,
      alignment: "right",
      visible: false,
    },
    {
      dataField: "unitID",
      caption: t("unit_id"),
      detailsOptionKey: "units",
      allowEditing: true,
      visible: false,
      width: 100,
      alignment: "right",
    },
    {
      dataField: "excess",
      caption: t("excess"),
      dataType: "number",
      allowEditing: true,
      width: 100,
      alignment: "right",
    },
    {
      dataField: "shortage",
      caption: t("shortage"),
      dataType: "number",
      allowEditing: true,
      width: 100,
      alignment: "right",
    },
    {
      dataField: "rate",
      caption: t("rate"),
      dataType: "number",
      visible: false,
      width: 130,
      alignment: "right",
      // decimalPoint: applicationSettings.mainSettings.decimalPoints,
    },
    {
      dataField: "salesPrice",
      caption: t("sales_price"),
      dataType: "number",
      visible: false,
      allowEditing: true,
      width: 200,
      alignment: "right",
      readOnly: true,
      decimalPoint: applicationSettings.mainSettings.decimalPoints,
    },
    {
      dataField: "stock",
      caption: t("stock"),
      dataType: "number",
      readOnly: true,
      width: 100,
      alignment: "right",
      decimalPoint: 4,
    },
    {
      dataField: "stockDetails",
      caption: t("stock_details"),
      dataType: "string",
      readOnly: true,
      width: 200,
      alignment: "left",
    },
    {
      dataField: "productDescription",
      caption: t("product_description"),
      dataType: "string",
      width: 250,
      readOnly: true,
      alignment: "left",
      visible: false,
    },
    {
      dataField: "actionCol",
      caption: "",
      dataType: "boolean",
      width: 55,
      readOnly: true,
      isLocked: true,
      alignment: "center",
    },
  ] as ColumnModel[];
