import {
  Countries,
  UserModel,
} from "../../../../redux/slices/user-session/reducer";
import { ApplicationSettingsType } from "../../../settings/system/application-settings-types/application-settings-types";
import { ColumnModel, TransactionFormState } from "../transaction-types";
// voucherType ?? formState.transaction.master.voucherType
// formType ?? formState.transaction.master.voucherForm
export const stockGridColOpeningStock = (
  applicationSettings: ApplicationSettingsType,
  userSession: UserModel,
  voucherType: string,
  formType: string,
  t: any,
  formState: TransactionFormState
) =>
  [
    {
      dataField: "slNo",
      caption: "",
      dataType: "number",
      width: 40,
      isLocked: true,
      alignment: "center",
    },
    {
      dataField: "pCode",
      caption: t("code"),
      dataType: "string",
      allowEditing: true,
      width: 150,
      alignment: "left",
    },
    {
      dataField: "mrp",
      decimalPoint: applicationSettings.mainSettings?.decimalPoints,
      caption: t("mrp"),
      dataType: "number",
      allowEditing: true,
      width: 100,
      readOnly: false,
      visible: false,
      alignment: "right",
    },

    {
      dataField: "barCode",
      caption: t("barcode"),
      dataType: "string",
      allowEditing: true,
      width: 150,
      alignment: "left",
    },
    {
      dataField: "productBatchID",
      caption: t("item_batch_id"),
      dataType: "number",
      width: 200,
      readOnly: true,
      alignment: "right",
      visible: false,
    },
    {
      dataField: "product",
      caption: t("product"),
      dataType: "string",
      allowEditing: true,
      width: 250,
      alignment: "left",
    },
    {
      dataField: "productID",
      caption: t("product_id"),
      dataType: "number",
      width: 100,
      readOnly: true,
      alignment: "right",
      visible: false,
    },
    {
      dataField: "brand",
      caption: t("brand"),
      idField: "brand",
      dataType: "cb",
      field: { valueKey: "name", labelKey: "name" },
      width: 150,
      alignment: "left",
      allowEditing: true,
      visible: false,
    },
    {
      dataField: "brandID",
      field: { valueKey: "id", labelKey: "name" },
      caption: t("brand_id"),
      dataType: "number",
      width: 100,
      readOnly: false,
      allowEditing: true,
      alignment: "right",
      visible: false,
    },

    {
      dataField: "qty",
      caption: t("qty"),
      dataType: "number",
      allowEditing: true,
      width: 100,
      alignment: "right",
    },
    {
      dataField: "unit",
      idField: "unitID",
      caption: t("unit"),
      dataType: "cb",
      width: 150,
      alignment: "left",
      allowEditing: true,
      readOnly: true,
    },
    {
      dataField: "unitID",
      caption: t("unit_id"),
      detailsOptionKey: "units",
      allowEditing: true,
      visible: false,
      width: 100,
      alignment: "right",
    },
    {
      dataField: "rate",
      caption: t("rate"),
      dataType: "number",
      width: 130,
      alignment: "right",
      // decimalPoint: applicationSettings.mainSettings.decimalPoints,
    },
    {
      dataField: "gross",
      caption: t("gross"),
      dataType: "number",
      decimalPoint: 4,
      readOnly: true,
      width: 100,
      alignment: "right",
      visible: false,
      allowEditing: true,
    },
    {
      dataField: "discPerc",
      caption: t("disc_perc"),
      dataType: "number",
      decimalPoint: 3,
      allowEditing: true,
      width: 100,
      alignment: "right",
      visible: false,
    },
    {
      dataField: "discount",
      caption: t("discount"),
      dataType: "number",
      decimalPoint: 4,
      allowEditing: true,
      width: 100,
      alignment: "right",
      visible: false,
    },
    {
      dataField: "netValue",
      caption: t("net_value"),
      dataType: "number",
      decimalPoint: 4,
      width: 100,
      alignment: "right",
      readOnly: true,
      visible: false,
    },
    {
      dataField: "vatPerc",
      caption: t("vat_perc"),
      dataType: "number",
      readOnly: true,
      allowEditing: true,
      width: 100,
      alignment: "right",
      visible: false,
    },
    {
      dataField: "vatAmount",
      caption: t("vat"),
      dataType: "number",
      readOnly: true,
      width: 100,
      alignment: "right",
      decimalPoint: applicationSettings.mainSettings.decimalPoints,
      visible: false,
    },
    {
      dataField: "total",
      caption: t("total"),
      dataType: "number",
      width: 100,
      alignment: "right",
      readOnly: true,
      decimalPoint: applicationSettings.mainSettings.decimalPoints,
    },
    {
      dataField: "margin",
      caption: t("margin"),
      dataType: "number",
      visible: false,
      width: 100,
      allowEditing: true,
      alignment: "right",
      decimalPoint: 4,
    },
    {
      dataField: "salesPrice",
      caption: t("sales_price"),
      dataType: "number",
      allowEditing: true,
      width: 200,
      alignment: "right",
      readOnly: true,
      visible: false,
      decimalPoint: applicationSettings.mainSettings.decimalPoints,
    },
    {
      dataField: "size",
      caption: t("size"),
      dataType: "string",
      visible: false,
      width: 150,
      alignment: "left",
    },
    {
      dataField: "stickerQty",
      caption: t("sticker"),
      dataType: "number",
      visible: false,
      width: 130,
      alignment: "right",
      allowEditing: true,
    },
    {
      dataField: "cost",
      caption: t("cost"),
      dataType: "number",
      decimalPoint: applicationSettings.mainSettings.decimalPoints,
      readOnly: true,
      visible: false,
      width: 100,
      alignment: "right",
    },
    {
      dataField: "profit",
      caption: t("profit"),
      dataType: "number",
      width: 100,
      visible: false,
      alignment: "right",
      decimalPoint: applicationSettings.mainSettings.decimalPoints,
    },
    {
      dataField: "batchCreated",
      caption: t("batch_created"),
      dataType: "chk",
      visible: false,
      width: 150,
      alignment: "center",
    },
    {
      dataField: "barcodePrinted",
      caption: t("barcode_printed"),
      dataType: "chk",
      visible: false,
      width: 50,
      alignment: "center",
    },
    {
      dataField: "productDescription",
      caption: t("product_description"),
      dataType: "string",
      width: 250,
      readOnly: true,
      alignment: "left",
      visible: false,
    },
    {
      dataField: "serial",
      caption: t("sl"),
      dataType: "btn",
      visible: false,
      width: 150,
      readOnly: true,
      alignment: "left",
      allowEditing: false,
    },
    {
      dataField: "nosQty",
      caption: t("nos"),
      dataType: "number",
      visible: false,
      width: 100,
      readOnly: true,
      alignment: "right",
    },
    {
      dataField: "arabicName",
      caption: t("arabic_name"),
      dataType: "string",
      visible: false,
      width: 150,
      alignment: "left",
    },
    {
      dataField: "actionCol",
      caption: "",
      dataType: "boolean",
      width: 55,
      readOnly: true,
      isLocked: true,
      alignment: "center",
    },
  ] as ColumnModel[];
