export const employees50 = [
    {
        keyField: 1,
        id: 1,
        accountGroup: "Chart of Accounts",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 0,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 2,
        id: 2,
        accountGroup: "Balance Sheet",
        aliasName: "ورقة التوازن",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 1,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 3,
        id: 3,
        accountGroup: "Profit & Loss Account",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 1,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 4,
        id: 4,
        accountGroup: "Assets",
        aliasName: "الأصول",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 2,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 5,
        id: 5,
        accountGroup: "Liabilities",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 2,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 6,
        id: 6,
        accountGroup: "Current Asset",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 4,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 7,
        id: 7,
        accountGroup: "Fixed Asset",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 4,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 8,
        id: 8,
        accountGroup: "Income",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 3,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 9,
        id: 9,
        accountGroup: "Expense",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 3,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 10,
        id: 10,
        accountGroup: "Direct Income",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 8,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 11,
        id: 11,
        accountGroup: "Indirect Income",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 8,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 12,
        id: 12,
        accountGroup: "Cash In hand",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 6,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 13,
        id: 13,
        accountGroup: "Bank Account",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 6,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 14,
        id: 14,
        accountGroup: "Current Liability",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 5,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 15,
        id: 15,
        accountGroup: "Capital Account",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 5,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 16,
        id: 16,
        accountGroup: "Suspense Account",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 5,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 17,
        id: 17,
        accountGroup: "Indirect Expense",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 9,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 18,
        id: 18,
        accountGroup: "Salaries",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 14,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 19,
        id: 19,
        accountGroup: "Direct Expense",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 9,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 20,
        id: 20,
        accountGroup: "Projects",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 10,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 22,
        id: 22,
        accountGroup: "Account Payable",
        aliasName: "حساب المستحق",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 14,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 23,
        id: 23,
        accountGroup: "Purchase Accounts",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 19,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 24,
        id: 24,
        accountGroup: "Salary Account",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 17,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 25,
        id: 25,
        accountGroup: "Sales Incentive",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 17,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 26,
        id: 26,
        accountGroup: "Sales Accounts",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 10,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 27,
        id: 27,
        accountGroup: "Stock In Hand",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 6,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 28,
        id: 28,
        accountGroup: "Loan & Advances (Asset)",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 6,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 29,
        id: 29,
        accountGroup: "Loan(Liability)",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 5,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 30,
        id: 30,
        accountGroup: "Investments",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 7,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 31,
        id: 31,
        accountGroup: "Duties & Taxes",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 14,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 32,
        id: 32,
        accountGroup: "Deposits (Asset)",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 6,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 33,
        id: 33,
        accountGroup: "Provisions",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 14,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 34,
        id: 34,
        accountGroup: "Reserves & Surplus",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 15,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 35,
        id: 35,
        accountGroup: "Bank OD A/c",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 29,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 36,
        id: 36,
        accountGroup: "Discount Given",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 19,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 37,
        id: 37,
        accountGroup: "Discount Received",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 10,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 38,
        id: 38,
        accountGroup: "Duties & Taxes (In)",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 31,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 39,
        id: 39,
        accountGroup: "Duties & Taxes (Out)",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 31,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 40,
        id: 40,
        accountGroup: "Account Receivable",
        aliasName: "حساب العميل",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 6,
        createdUser: "admin",
        createdDate: "1980-01-01T12:00:00"
      },
      {
        keyField: 41,
        id: 41,
        accountGroup: "Job Works",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 19,
        createdUser: "admin",
        createdDate: "2014-08-16T11:10:00.173"
      },
      {
        keyField: 42,
        id: 42,
        accountGroup: "Branch Receivable",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 40,
        createdUser: "admin",
        createdDate: "2015-02-16T14:39:24.210"
      },
      {
        keyField: 43,
        id: 43,
        accountGroup: "Branch Payable",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 22,
        createdUser: "admin",
        createdDate: "2015-02-16T14:39:24.240"
      },
      {
        keyField: 44,
        id: 44,
        accountGroup: "Owners Current Account",
        aliasName: "",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 6,
        createdUser: "admin",
        createdDate: "2021-05-18T16:27:00.017"
      },
      {
        keyField: 45,
        id: 45,
        accountGroup: "gdfgdfgdfgdg",
        aliasName: "string",
        code: "",
        isGroup: 1,
        balance: "",
        parentID: 22,
        createdUser: "",
        createdDate: "2024-08-28T21:03:33.660"
      },
      {
        keyField: 46,
        id: 46,
        accountGroup: "CASH A/C",
        aliasName: "",
        code: "12221",
        isGroup: 0,
        balance: "0",
        parentID: 12,
        createdUser: "admin",
        createdDate: "2015-06-11T18:22:24.037"
      },
      {
        keyField: 47,
        id: 47,
        accountGroup: "Sales Account",
        aliasName: "",
        code: "SA",
        isGroup: 0,
        balance: "0",
        parentID: 26,
        createdUser: "admin",
        createdDate: "2015-06-11T18:22:24.043"
      },
      {
        keyField: 48,
        id: 48,
        accountGroup: "Sales Return Account",
        aliasName: "",
        code: "SRA",
        isGroup: 0,
        balance: "0",
        parentID: 26,
        createdUser: "admin",
        createdDate: "2015-06-11T18:22:24.043"
      },
      {
        keyField: 49,
        id: 49,
        accountGroup: "Purchase Account",
        aliasName: "",
        code: "PA",
        isGroup: 0,
        balance: "0",
        parentID: 23,
        createdUser: "admin",
        createdDate: "2015-06-11T18:22:24.043"
      },
      {
        keyField: 50,
        id: 50,
        accountGroup: "Purchase Return Account",
        aliasName: "",
        code: "PRA",
        isGroup: 0,
        balance: "0",
        parentID: 23,
        createdUser: "admin",
        createdDate: "2015-06-11T18:22:24.047"
      },
      {
        keyField: 51,
        id: 51,
        accountGroup: "Input VAT",
        aliasName: "",
        code: "IV",
        isGroup: 0,
        balance: "0",
        parentID: 31,
        createdUser: "admin",
        createdDate: "2015-06-11T18:22:24.047"
      },
      {
        keyField: 52,
        id: 52,
        accountGroup: "Output VAT",
        aliasName: "",
        code: "OV",
        isGroup: 0,
        balance: "0",
        parentID: 31,
        createdUser: "admin",
        createdDate: "2015-06-11T18:22:24.050"
      },
      {
        keyField: 53,
        id: 53,
        accountGroup: "Suspense Account",
        aliasName: "",
        code: "SUSP",
        isGroup: 0,
        balance: "0",
        parentID: 16,
        createdUser: "admin",
        createdDate: "2015-06-11T18:22:24.050"
      },
      {
        keyField: 54,
        id: 54,
        accountGroup: "Discount Given",
        aliasName: "",
        code: "DG",
        isGroup: 0,
        balance: "0",
        parentID: 36,
        createdUser: "admin",
        createdDate: "2015-06-11T18:22:24.050"
      },
      {
        keyField: 55,
        id: 55,
        accountGroup: "Discount Received",
        aliasName: "",
        code: "DR",
        isGroup: 0,
        balance: "0",
        parentID: 37,
        createdUser: "admin",
        createdDate: "2015-06-11T18:22:24.050"
      },
      {
        keyField: 56,
        id: 56,
        accountGroup: "Input CST",
        aliasName: "",
        code: "IC",
        isGroup: 0,
        balance: "0",
        parentID: 31,
        createdUser: "admin",
        createdDate: "2015-06-11T18:22:24.053"
      },
      {
        keyField: 57,
        id: 57,
        accountGroup: "Output CST",
        aliasName: "",
        code: "OC",
        isGroup: 0,
        balance: "0",
        parentID: 31,
        createdUser: "admin",
        createdDate: "2015-06-11T18:22:24.053"
      },
      {
        keyField: 58,
        id: 58,
        accountGroup: "Sales Incentive",
        aliasName: "",
        code: "SAInc",
        isGroup: 0,
        balance: "0",
        parentID: 25,
        createdUser: "admin",
        createdDate: "2015-06-11T18:22:24.053"
      },
      {
        keyField: 59,
        id: 59,
        accountGroup: "Branch Payable Account",
        aliasName: "",
        code: "BPA",
        isGroup: 0,
        balance: "0",
        parentID: 43,
        createdUser: "admin",
        createdDate: "2015-06-11T18:22:24.053"
      },
      {
        keyField: 60,
        id: 60,
        accountGroup: "SALARY ACCOUNT",
        aliasName: "",
        code: "SALAC",
        isGroup: 0,
        balance: "0",
        parentID: 24,
        createdUser: "admin",
        createdDate: "2015-06-11T18:40:45.787"
      },
      {
        keyField: 61,
        id: 61,
        accountGroup: "1649-QAMAR AL LAYAL TRADING CO - AL NASEEM",
        aliasName: "1649-SAFEENA STORE - AL NASEEM",
        code: "1649",
        isGroup: 0,
        balance: "0",
        parentID: 40,
        createdUser: "admin",
        createdDate: "2017-06-20T14:41:18.553"
      },
      
        {
            "keyField": 62,
            "id": 62,
            "accountGroup": "1743-RAHAD SHIMAL COMPANY -AL SAMER",
            "aliasName": "1743-RAHAD STORE -AL SAMER",
            "code": "1743",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.157"
        },
        {
            "keyField": 63,
            "id": 63,
            "accountGroup": "2233-AL RAYAN BAKERY- AL SAMER",
            "aliasName": "2233-AL RAYAN BAKERY- AL SAMER",
            "code": "2233",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.160"
        },
        {
            "keyField": 64,
            "id": 64,
            "accountGroup": "2235-KHALEEJ STORE-AL SAMER",
            "aliasName": "2235-KHALEEJ STORE-AL SAMER",
            "code": "2235",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.163"
        },
        {
            "keyField": 65,
            "id": 65,
            "accountGroup": "2236-AL KHAIR  STORE 2 -AL SAFA",
            "aliasName": "2236-AL KHAIR  STORE 2 -AL SAFA",
            "code": "2236",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.167"
        },
        {
            "keyField": 66,
            "id": 66,
            "accountGroup": "2238-USMAN STORE- AL SAMER",
            "aliasName": "2238-USMAN STORE- AL SAMER",
            "code": "2238",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.170"
        },
        {
            "keyField": 67,
            "id": 67,
            "accountGroup": "2239-ZAM ZAM- AL SAMER",
            "aliasName": "2239-ZAM ZAM- AL SAMER",
            "code": "2239",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.173"
        },
        {
            "keyField": 69,
            "id": 69,
            "accountGroup": "2241-SULTHAN STORE- AL SAMER",
            "aliasName": "2241-SULTHAN STORE- AL SAMER",
            "code": "2241",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.180"
        },
        {
            "keyField": 70,
            "id": 70,
            "accountGroup": "2242-ASWAK SHAFEENA (MARWA LULU)- BURAIMAN",
            "aliasName": "2242-SHAFEENA - BURAIMAN",
            "code": "2242",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.183"
        },
        {
            "keyField": 71,
            "id": 71,
            "accountGroup": "2243-RAJHAN STORE- AL SAMER",
            "aliasName": "2243-RAJHAN STORE- AL SAMER",
            "code": "2243",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.187"
        },
        {
            "keyField": 72,
            "id": 72,
            "accountGroup": "2244-SHAREEF HOSPITAL- AL SAMER",
            "aliasName": "2244-SHAREEF HOSPITAL- AL SAMER",
            "code": "2244",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.190"
        },
        {
            "keyField": 73,
            "id": 73,
            "accountGroup": "2316-AL WAFA SUPERMARKET-AL SAMER",
            "aliasName": "2316-WAFA STORE-AL SAMER",
            "code": "2316",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.193"
        },
        {
            "keyField": 74,
            "id": 74,
            "accountGroup": "2323-BURAIMAN S/M-AL SAFA",
            "aliasName": "2323-BURAIMAN S/M-AL SAFA",
            "code": "2323",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.197"
        },
        {
            "keyField": 75,
            "id": 75,
            "accountGroup": "2331-RAHAD SHIMAAL 3-AL SAMER",
            "aliasName": "2331-BASHIYA STORE-AL SAMER",
            "code": "2331",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.200"
        },
        {
            "keyField": 76,
            "id": 76,
            "accountGroup": "2332-BARAKATH STORE-  AL SAMER",
            "aliasName": "2332-BARAKATH STORE-  AL SAMER",
            "code": "2332",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.203"
        },
        {
            "keyField": 77,
            "id": 77,
            "accountGroup": "2341-TAMVINATH HUDHA - AL SAMAR",
            "aliasName": "2341-SAHLLY STORE, PUMP - AL SAMAR",
            "code": "2341",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.207"
        },
        {
            "keyField": 78,
            "id": 78,
            "accountGroup": "2342-HALAH - BURAIMAN",
            "aliasName": "2342-HALAH - BURAIMAN",
            "code": "2342",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.210"
        },
        {
            "keyField": 79,
            "id": 79,
            "accountGroup": "2343-BROTHERS STORE-AL SAMER",
            "aliasName": "2343-BROTHERS STORE-AL SAMER",
            "code": "2343",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.213"
        },
        {
            "keyField": 80,
            "id": 80,
            "accountGroup": "2354-UMMU HABEEBI-AL SAMER",
            "aliasName": "2354-UMMU HABEEBI-AL SAMER",
            "code": "2354",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.217"
        },
        {
            "keyField": 81,
            "id": 81,
            "accountGroup": "2355-AL HARITH S/M-AL SAMER",
            "aliasName": "2355-AL HARITH S/M-AL SAMER",
            "code": "2355",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.220"
        },
        {
            "keyField": 82,
            "id": 82,
            "accountGroup": "2356-BOLAND STORE-AL SAMER",
            "aliasName": "2356-BOLAND STORE-AL SAMER",
            "code": "2356",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.223"
        },
        {
            "keyField": 83,
            "id": 83,
            "accountGroup": "2357-SHABI STORE-AL SAMER",
            "aliasName": "2357-SHABI STORE-AL SAMER",
            "code": "2357",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.227"
        },
        {
            "keyField": 84,
            "id": 84,
            "accountGroup": "2358-FARASHA STORE-AL SAMER",
            "aliasName": "2358-FARASHA STORE-AL SAMER",
            "code": "2358",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.230"
        },
        {
            "keyField": 85,
            "id": 85,
            "accountGroup": "2359-AL ANFAL STORE-AL SAMER",
            "aliasName": "2359-AL ANFAL STORE-AL SAMER",
            "code": "2359",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.233"
        },
        {
            "keyField": 86,
            "id": 86,
            "accountGroup": "2360-HUSSEIN STORE-AL SAMER",
            "aliasName": "2360-HUSSEIN STORE-AL SAMER",
            "code": "2360",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.237"
        },
        {
            "keyField": 87,
            "id": 87,
            "accountGroup": "2361-ABDEL BAKERY-AL SAMER",
            "aliasName": "2361-ABDEL BAKERY-AL SAMER",
            "code": "2361",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.240"
        },
        {
            "keyField": 88,
            "id": 88,
            "accountGroup": "2362-AL ISHAQ  STORE-AL SAMER",
            "aliasName": "2362-AL ISHAQ  STORE-AL SAMER",
            "code": "2362",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.243"
        },
        {
            "keyField": 89,
            "id": 89,
            "accountGroup": "2363-RASHID STORE-AL SAMER",
            "aliasName": "2363-RASHID STORE-AL SAMER",
            "code": "2363",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.247"
        },
        {
            "keyField": 90,
            "id": 90,
            "accountGroup": "2364-AL ASAL STORE-AL SAMER",
            "aliasName": "2364-AL ASAL STORE-AL SAMER",
            "code": "2364",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.250"
        },
        {
            "keyField": 91,
            "id": 91,
            "accountGroup": "2365-SAAD  STORE-AL SAMER",
            "aliasName": "2365-SAAD  STORE-AL SAMER",
            "code": "2365",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.253"
        },
        {
            "keyField": 92,
            "id": 92,
            "accountGroup": "2366-AHMED STORE-AL SAMER",
            "aliasName": "2366-AHMED STORE-AL SAMER",
            "code": "2366",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.257"
        },
        {
            "keyField": 93,
            "id": 93,
            "accountGroup": "2367-AL  MAWDA STORE-AL SAMER",
            "aliasName": "2367-AL  MAWDA STORE-AL SAMER",
            "code": "2367",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.260"
        },
        {
            "keyField": 94,
            "id": 94,
            "accountGroup": "2368-AL ZAFAR STORE-AL SAMER",
            "aliasName": "2368-AL ZAFAR STORE-AL SAMER",
            "code": "2368",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.263"
        },
        {
            "keyField": 95,
            "id": 95,
            "accountGroup": "2369-MALIK STORE-AL SAMER",
            "aliasName": "2369-MALIK STORE-AL SAMER",
            "code": "2369",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.267"
        },
        {
            "keyField": 96,
            "id": 96,
            "accountGroup": "2370-AAL YASSER S/M-AL SAMER",
            "aliasName": "2370-AAL YASSER S/M-AL SAMER",
            "code": "2370",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.270"
        },
        {
            "keyField": 97,
            "id": 97,
            "accountGroup": "2371-NOUR STORE-AL SAMER",
            "aliasName": "2371-NOUR STORE-AL SAMER",
            "code": "2371",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.273"
        },
        {
            "keyField": 98,
            "id": 98,
            "accountGroup": "2372-NOOR STORE-AL SAMER",
            "aliasName": "2372-NOOR STORE-AL SAMER",
            "code": "2372",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.277"
        },
        {
            "keyField": 99,
            "id": 99,
            "accountGroup": "2373-AL ALI STORE-AL SAMER",
            "aliasName": "2373-AL ALI STORE-AL SAMER",
            "code": "2373",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.280"
        },
        {
            "keyField": 100,
            "id": 100,
            "accountGroup": "2374-SAUDI STORE-AL SAMER",
            "aliasName": "2374-SAUDI STORE-AL SAMER",
            "code": "2374",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.283"
        },
        {
            "keyField": 101,
            "id": 101,
            "accountGroup": "2375-FARIS  STORE-AL SAMER",
            "aliasName": "2375-FARIS  STORE-AL SAMER",
            "code": "2375",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.287"
        },
        {
            "keyField": 102,
            "id": 102,
            "accountGroup": "2376-AL BASHI STORE-AL SAMER",
            "aliasName": "2376-AL BASHI STORE-AL SAMER",
            "code": "2376",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.290"
        },
        {
            "keyField": 103,
            "id": 103,
            "accountGroup": "2377-AL JASIM STORE-AL SAMER",
            "aliasName": "2377-AL JASIM STORE-AL SAMER",
            "code": "2377",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.293"
        },
        {
            "keyField": 104,
            "id": 104,
            "accountGroup": "2378-AL AMEER STORE-AL SAMER",
            "aliasName": "2378-AL AMEER STORE-AL SAMER",
            "code": "2378",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.297"
        },
        {
            "keyField": 105,
            "id": 105,
            "accountGroup": "2379-MOHSEN STORE-AL SAMER",
            "aliasName": "2379-MOHSEN STORE-AL SAMER",
            "code": "2379",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.300"
        },
        {
            "keyField": 106,
            "id": 106,
            "accountGroup": "2380-AL REZZA STORE-AL SAMER",
            "aliasName": "2380-AL REZZA STORE-AL SAMER",
            "code": "2380",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.303"
        },
        {
            "keyField": 107,
            "id": 107,
            "accountGroup": "2381-HUSAINI STORE-AL SAMER",
            "aliasName": "2381-HUSAINI STORE-AL SAMER",
            "code": "2381",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.307"
        },
        {
            "keyField": 108,
            "id": 108,
            "accountGroup": "2382-MOUSTACHE STORE-AL SAMER",
            "aliasName": "2382-MOUSTACHE STORE-AL SAMER",
            "code": "2382",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.310"
        },
        {
            "keyField": 109,
            "id": 109,
            "accountGroup": "2383-AJAHMA STORE-AL SAMER",
            "aliasName": "2383-AJAHMA STORE-AL SAMER",
            "code": "2383",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.313"
        },
        {
            "keyField": 110,
            "id": 110,
            "accountGroup": "2384-AL OBAID STORE-AL SAMER",
            "aliasName": "2384-AL OBAID STORE-AL SAMER",
            "code": "2384",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.317"
        },
        {
            "keyField": 111,
            "id": 111,
            "accountGroup": "2385-AL RAHMA STORE-AL SAMER",
            "aliasName": "2385-AL RAHMA STORE-AL SAMER",
            "code": "2385",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.320"
        },
        {
            "keyField": 112,
            "id": 112,
            "accountGroup": "2386-AL NISAA STORE-AL SAMER",
            "aliasName": "2386-AL NISAA STORE-AL SAMER",
            "code": "2386",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.323"
        },
        {
            "keyField": 113,
            "id": 113,
            "accountGroup": "2387-AL YASSER STORE-AL SAMER",
            "aliasName": "2387-AL YASSER STORE-AL SAMER",
            "code": "2387",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.327"
        },
        {
            "keyField": 114,
            "id": 114,
            "accountGroup": "2388-AL HARITHY STORE-AL SAMER",
            "aliasName": "2388-AL HARITHY STORE-AL SAMER",
            "code": "2388",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.330"
        },
        {
            "keyField": 115,
            "id": 115,
            "accountGroup": "2389-MOHAMAD STORE-AL SAMER",
            "aliasName": "2389-MOHAMAD STORE-AL SAMER",
            "code": "2389",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.333"
        },
        {
            "keyField": 116,
            "id": 116,
            "accountGroup": "2390-AL WAHA STORE-AL SAMER",
            "aliasName": "2390-AL WAHA STORE-AL SAMER",
            "code": "2390",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.337"
        },
        {
            "keyField": 117,
            "id": 117,
            "accountGroup": "2391-SABAA STORE-AL SAMER",
            "aliasName": "2391-SABAA STORE-AL SAMER",
            "code": "2391",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.340"
        },
        {
            "keyField": 118,
            "id": 118,
            "accountGroup": "2392-HAMEED STORE-AL SAMER",
            "aliasName": "2392-HAMEED STORE-AL SAMER",
            "code": "2392",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.343"
        },
        {
            "keyField": 119,
            "id": 119,
            "accountGroup": "2393-AL FURSAN STORE-AL SAMER",
            "aliasName": "2393-AL FURSAN STORE-AL SAMER",
            "code": "2393",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.347"
        },
        {
            "keyField": 120,
            "id": 120,
            "accountGroup": "2394-AL FAREED STORE-AL SAMER",
            "aliasName": "2394-AL FAREED STORE-AL SAMER",
            "code": "2394",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.350"
        },
        {
            "keyField": 121,
            "id": 121,
            "accountGroup": "2395-AL MASHHADY STORE-AL SAMER",
            "aliasName": "2395-AL MASHHADY STORE-AL SAMER",
            "code": "2395",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.353"
        },
        {
            "keyField": 122,
            "id": 122,
            "accountGroup": "2396-AL SAMER STORE-AL SAMER",
            "aliasName": "2396-AL SAMER STORE-AL SAMER",
            "code": "2396",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.357"
        },
        {
            "keyField": 123,
            "id": 123,
            "accountGroup": "2397-AL WAZIR STORE-AL SAMER",
            "aliasName": "2397-AL WAZIR STORE-AL SAMER",
            "code": "2397",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.360"
        },
        {
            "keyField": 124,
            "id": 124,
            "accountGroup": "2398-AL MUSAYYIB STORE-AL SAMER",
            "aliasName": "2398-AL MUSAYYIB STORE-AL SAMER",
            "code": "2398",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.363"
        },
        {
            "keyField": 125,
            "id": 125,
            "accountGroup": "2399-AL MANAR STORE-AL SAMER",
            "aliasName": "2399-AL MANAR STORE-AL SAMER",
            "code": "2399",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.367"
        },
        {
            "keyField": 126,
            "id": 126,
            "accountGroup": "2400-AL ALBADA STORE-AL SAMER",
            "aliasName": "2400-AL ALBADA STORE-AL SAMER",
            "code": "2400",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.370"
        },
        {
            "keyField": 127,
            "id": 127,
            "accountGroup": "2401-AL JAWAD STORE-AL SAMER",
            "aliasName": "2401-AL JAWAD STORE-AL SAMER",
            "code": "2401",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.373"
        },
        {
            "keyField": 128,
            "id": 128,
            "accountGroup": "2402-AL FAZAA STORE-AL SAMER",
            "aliasName": "2402-AL FAZAA STORE-AL SAMER",
            "code": "2402",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.377"
        },
        {
            "keyField": 129,
            "id": 129,
            "accountGroup": "2403-SOFA STORE-AL SAMER",
            "aliasName": "2403-SOFA STORE-AL SAMER",
            "code": "2403",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.380"
        },
        {
            "keyField": 130,
            "id": 130,
            "accountGroup": "2404-AL DEWAN STORE-AL SAMER",
            "aliasName": "2404-AL DEWAN STORE-AL SAMER",
            "code": "2404",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.383"
        },
        {
            "keyField": 131,
            "id": 131,
            "accountGroup": "2405-AL MAHMOOD STORE-AL SAMER",
            "aliasName": "2405-AL MAHMOOD STORE-AL SAMER",
            "code": "2405",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.387"
        },
        {
            "keyField": 132,
            "id": 132,
            "accountGroup": "2406-MUJIB STORE-AL SAMER",
            "aliasName": "2406-MUJIB STORE-AL SAMER",
            "code": "2406",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.390"
        },
        {
            "keyField": 133,
            "id": 133,
            "accountGroup": "2407-AL RAZZAK STORE-AL SAMER",
            "aliasName": "2407-AL RAZZAK STORE-AL SAMER",
            "code": "2407",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.393"
        },
        {
            "keyField": 134,
            "id": 134,
            "accountGroup": "2408-AL KHALID STORE-AL SAMER",
            "aliasName": "2408-AL KHALID STORE-AL SAMER",
            "code": "2408",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.397"
        },
        {
            "keyField": 135,
            "id": 135,
            "accountGroup": "2409-AL OMAR STORE-AL SAMER",
            "aliasName": "2409-AL OMAR STORE-AL SAMER",
            "code": "2409",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.400"
        },
        {
            "keyField": 136,
            "id": 136,
            "accountGroup": "2410-AL ALI ALI STORE-AL SAMER",
            "aliasName": "2410-AL ALI ALI STORE-AL SAMER",
            "code": "2410",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.403"
        },
        {
            "keyField": 137,
            "id": 137,
            "accountGroup": "2411-AL ASHRAAF STORE-AL SAMER",
            "aliasName": "2411-AL ASHRAAF STORE-AL SAMER",
            "code": "2411",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.407"
        },
        {
            "keyField": 138,
            "id": 138,
            "accountGroup": "2412-AL ASHRAAF ALI STORE-AL SAMER",
            "aliasName": "2412-AL ASHRAAF ALI STORE-AL SAMER",
            "code": "2412",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.410"
        },
        {
            "keyField": 139,
            "id": 139,
            "accountGroup": "2413-AL NASSER STORE-AL SAMER",
            "aliasName": "2413-AL NASSER STORE-AL SAMER",
            "code": "2413",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.413"
        },
        {
            "keyField": 140,
            "id": 140,
            "accountGroup": "2414-AL FAHAD STORE-AL SAMER",
            "aliasName": "2414-AL FAHAD STORE-AL SAMER",
            "code": "2414",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.417"
        },
        {
            "keyField": 141,
            "id": 141,
            "accountGroup": "2415-SALIH STORE-AL SAMER",
            "aliasName": "2415-SALIH STORE-AL SAMER",
            "code": "2415",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.420"
        },
        {
            "keyField": 142,
            "id": 142,
            "accountGroup": "2416-AL ABDULLAH STORE-AL SAMER",
            "aliasName": "2416-AL ABDULLAH STORE-AL SAMER",
            "code": "2416",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.423"
        },
        {
            "keyField": 143,
            "id": 143,
            "accountGroup": "2417-AL HUSAIN STORE-AL SAMER",
            "aliasName": "2417-AL HUSAIN STORE-AL SAMER",
            "code": "2417",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.427"
        },
        {
            "keyField": 144,
            "id": 144,
            "accountGroup": "2418-AL AALY STORE-AL SAMER",
            "aliasName": "2418-AL AALY STORE-AL SAMER",
            "code": "2418",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.430"
        },
        {
            "keyField": 145,
            "id": 145,
            "accountGroup": "2419-AL RAED STORE-AL SAMER",
            "aliasName": "2419-AL RAED STORE-AL SAMER",
            "code": "2419",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.433"
        },
        {
            "keyField": 146,
            "id": 146,
            "accountGroup": "2420-AL KHALED STORE-AL SAMER",
            "aliasName": "2420-AL KHALED STORE-AL SAMER",
            "code": "2420",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.437"
        },
        {
            "keyField": 147,
            "id": 147,
            "accountGroup": "2421-MAWLA STORE-AL SAMER",
            "aliasName": "2421-MAWLA STORE-AL SAMER",
            "code": "2421",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.440"
        },
        {
            "keyField": 148,
            "id": 148,
            "accountGroup": "2422-FADHI STORE-AL SAMER",
            "aliasName": "2422-FADHI STORE-AL SAMER",
            "code": "2422",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.443"
        },
        {
            "keyField": 149,
            "id": 149,
            "accountGroup": "2423-AL KHALED ALSHAYEB STORE-AL SAMER",
            "aliasName": "2423-AL KHALED ALSHAYEB STORE-AL SAMER",
            "code": "2423",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.447"
        },
        {
            "keyField": 150,
            "id": 150,
            "accountGroup": "2424-AL NASHAB STORE-AL SAMER",
            "aliasName": "2424-AL NASHAB STORE-AL SAMER",
            "code": "2424",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.450"
        },
        {
            "keyField": 151,
            "id": 151,
            "accountGroup": "2425-AL NASSER AL KHALED STORE-AL SAMER",
            "aliasName": "2425-AL NASSER AL KHALED STORE-AL SAMER",
            "code": "2425",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.453"
        },
        {
            "keyField": 152,
            "id": 152,
            "accountGroup": "2426-AL RAZZAK AL SHAYEB STORE-AL SAMER",
            "aliasName": "2426-AL RAZZAK AL SHAYEB STORE-AL SAMER",
            "code": "2426",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.457"
        },
        {
            "keyField": 153,
            "id": 153,
            "accountGroup": "2427-AL SHARAF STORE-AL SAMER",
            "aliasName": "2427-AL SHARAF STORE-AL SAMER",
            "code": "2427",
            "isGroup": 0,
            "balance": "0",
             "parentID": 40,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.460"
        },
        {
            "keyField": 154,
            "id": 154,
            "accountGroup": "AL SAMER",
            "aliasName": "AL SAMER",
            "code": "154",
            "isGroup": 1,
            "balance": "0",
            "parentID": null,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.460"
        },
        {
            "keyField": 155,
            "id": 155,
            "accountGroup": "AL MANSOUR",
            "aliasName": "AL MANSOUR",
            "code": "155",
            "isGroup": 1,
            "balance": "0",
            "parentID": null,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.467"
        },
        {
            "keyField": 156,
            "id": 156,
            "accountGroup": "AL MUHAMMAD STORE",
            "aliasName": "AL MUHAMMAD STORE",
            "code": "156",
            "isGroup": 0,
            "balance": "0",
            "parentID": 155,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.470"
        },
        {
            "keyField": 157,
            "id": 157,
            "accountGroup": "AL FURAT STORE",
            "aliasName": "AL FURAT STORE",
            "code": "157",
            "isGroup": 0,
            "balance": "0",
            "parentID": 155,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.473"
        },
        {
            "keyField": 158,
            "id": 158,
            "accountGroup": "AL RAZZAK STORE",
            "aliasName": "AL RAZZAK STORE",
            "code": "158",
            "isGroup": 0,
            "balance": "0",
            "parentID": 155,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.477"
        },
        {
            "keyField": 159,
            "id": 159,
            "accountGroup": "AL SHAWAF STORE",
            "aliasName": "AL SHAWAF STORE",
            "code": "159",
            "isGroup": 0,
            "balance": "0",
            "parentID": 155,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.480"
        },
        {
            "keyField": 160,
            "id": 160,
            "accountGroup": "AL KHALED STORE",
            "aliasName": "AL KHALED STORE",
            "code": "160",
            "isGroup": 0,
            "balance": "0",
            "parentID": 155,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.483"
        },
        {
            "keyField": 161,
            "id": 161,
            "accountGroup": "AL ALI STORE",
            "aliasName": "AL ALI STORE",
            "code": "161",
            "isGroup": 0,
            "balance": "0",
            "parentID": 155,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.487"
        },
        {
            "keyField": 162,
            "id": 162,
            "accountGroup": "AL KHALED AL SHAYEB STORE",
            "aliasName": "AL KHALED AL SHAYEB STORE",
            "code": "162",
            "isGroup": 0,
            "balance": "0",
            "parentID": 155,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.490"
        },
        {
            "keyField": 163,
            "id": 163,
            "accountGroup": "AL FARIS STORE",
            "aliasName": "AL FARIS STORE",
            "code": "163",
            "isGroup": 0,
            "balance": "0",
            "parentID": 155,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.493"
        },
        {
            "keyField": 164,
            "id": 164,
            "accountGroup": "AL IZZ STORE",
            "aliasName": "AL IZZ STORE",
            "code": "164",
            "isGroup": 0,
            "balance": "0",
            "parentID": 155,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.497"
        },
        {
            "keyField": 165,
            "id": 165,
            "accountGroup": "AL RAZZAK AL SAMER STORE",
            "aliasName": "AL RAZZAK AL SAMER STORE",
            "code": "165",
            "isGroup": 0,
            "balance": "0",
            "parentID": 155,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.500"
        },
        {
            "keyField": 166,
            "id": 166,
            "accountGroup": "AL HUSAIN STORE",
            "aliasName": "AL HUSAIN STORE",
            "code": "166",
            "isGroup": 0,
            "balance": "0",
            "parentID": 155,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.503"
        },
        {
            "keyField": 167,
            "id": 167,
            "accountGroup": "AL SULIMAN STORE",
            "aliasName": "AL SULIMAN STORE",
            "code": "167",
            "isGroup": 0,
            "balance": "0",
            "parentID": 155,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.507"
        },
        {
            "keyField": 168,
            "id": 168,
            "accountGroup": "AL SHAHEEN STORE",
            "aliasName": "AL SHAHEEN STORE",
            "code": "168",
            "isGroup": 0,
            "balance": "0",
            "parentID": 155,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.510"
        },
        {
            "keyField": 169,
            "id": 169,
            "accountGroup": "AL BASHIR STORE",
            "aliasName": "AL BASHIR STORE",
            "code": "169",
            "isGroup": 0,
            "balance": "0",
            "parentID": 155,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.513"
        },
        {
            "keyField": 170,
            "id": 170,
            "accountGroup": "AL JAZEERAH STORE",
            "aliasName": "AL JAZEERAH STORE",
            "code": "170",
            "isGroup": 0,
            "balance": "0",
            "parentID": 155,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.517"
        },
        {
            "keyField": 171,
            "id": 171,
            "accountGroup": "AL QARAR STORE",
            "aliasName": "AL QARAR STORE",
            "code": "171",
            "isGroup": 0,
            "balance": "0",
            "parentID": 155,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.520"
        },
        {
            "keyField": 172,
            "id": 172,
            "accountGroup": "AL HIZAM STORE",
            "aliasName": "AL HIZAM STORE",
            "code": "172",
            "isGroup": 0,
            "balance": "0",
            "parentID": 155,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.523"
        },
        {
            "keyField": 173,
            "id": 173,
            "accountGroup": "AL ZAWAHIR STORE",
            "aliasName": "AL ZAWAHIR STORE",
            "code": "173",
            "isGroup": 0,
            "balance": "0",
            "parentID": 155,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.527"
        },
        {
            "keyField": 174,
            "id": 174,
            "accountGroup": "AL SAMER FURNITURE",
            "aliasName": "AL SAMER FURNITURE",
            "code": "174",
            "isGroup": 1,
            "balance": "0",
            "parentID": null,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.530"
        },
        {
            "keyField": 175,
            "id": 175,
            "accountGroup": "AL SAMER FURNITURE STORE",
            "aliasName": "AL SAMER FURNITURE STORE",
            "code": "175",
            "isGroup": 0,
            "balance": "0",
            "parentID": 174,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.533"
        },
        {
            "keyField": 176,
            "id": 176,
            "accountGroup": "AL SAMER BED STORE",
            "aliasName": "AL SAMER BED STORE",
            "code": "176",
            "isGroup": 0,
            "balance": "0",
            "parentID": 174,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.537"
        },
        {
            "keyField": 177,
            "id": 177,
            "accountGroup": "AL SAMER SOFA STORE",
            "aliasName": "AL SAMER SOFA STORE",
            "code": "177",
            "isGroup": 0,
            "balance": "0",
            "parentID": 174,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.540"
        },
        {
            "keyField": 178,
            "id": 178,
            "accountGroup": "AL SAMER LIVING ROOM STORE",
            "aliasName": "AL SAMER LIVING ROOM STORE",
            "code": "178",
            "isGroup": 0,
            "balance": "0",
            "parentID": 174,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.543"
        },
        {
            "keyField": 179,
            "id": 179,
            "accountGroup": "AL SAMER KITCHEN STORE",
            "aliasName": "AL SAMER KITCHEN STORE",
            "code": "179",
            "isGroup": 0,
            "balance": "0",
            "parentID": 174,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.547"
        },
        {
            "keyField": 180,
            "id": 180,
            "accountGroup": "AL SAMER OFFICE FURNITURE STORE",
            "aliasName": "AL SAMER OFFICE FURNITURE STORE",
            "code": "180",
            "isGroup": 0,
            "balance": "0",
            "parentID": 174,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.550"
        },
        {
            "keyField": 181,
            "id": 181,
            "accountGroup": "AL SAMER TABLE STORE",
            "aliasName": "AL SAMER TABLE STORE",
            "code": "181",
            "isGroup": 0,
            "balance": "0",
            "parentID": 174,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.553"
        },
        {
            "keyField": 182,
            "id": 182,
            "accountGroup": "AL SAMER CLOTHING STORE",
            "aliasName": "AL SAMER CLOTHING STORE",
            "code": "182",
            "isGroup": 1,
            "balance": "0",
            "parentID": null,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.557"
        },
        {
            "keyField": 183,
            "id": 183,
            "accountGroup": "AL SAMER MEN'S CLOTHING STORE",
            "aliasName": "AL SAMER MEN'S CLOTHING STORE",
            "code": "183",
            "isGroup": 0,
            "balance": "0",
            "parentID": 182,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.560"
        },
        {
            "keyField": 184,
            "id": 184,
            "accountGroup": "AL SAMER WOMEN'S CLOTHING STORE",
            "aliasName": "AL SAMER WOMEN'S CLOTHING STORE",
            "code": "184",
            "isGroup": 0,
            "balance": "0",
            "parentID": 182,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.563"
        },
        {
            "keyField": 185,
            "id": 185,
            "accountGroup": "AL SAMER CHILDREN'S CLOTHING STORE",
            "aliasName": "AL SAMER CHILDREN'S CLOTHING STORE",
            "code": "185",
            "isGroup": 0,
            "balance": "0",
            "parentID": 182,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.567"
        },
        {
            "keyField": 186,
            "id": 186,
            "accountGroup": "AL SAMER SPORTS CLOTHING STORE",
            "aliasName": "AL SAMER SPORTS CLOTHING STORE",
            "code": "186",
            "isGroup": 0,
            "balance": "0",
            "parentID": 182,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.570"
        },
        {
            "keyField": 187,
            "id": 187,
            "accountGroup": "AL SAMER ACCESSORIES STORE",
            "aliasName": "AL SAMER ACCESSORIES STORE",
            "code": "187",
            "isGroup": 0,
            "balance": "0",
            "parentID": 182,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.573"
        },
        {
            "keyField": 188,
            "id": 188,
            "accountGroup": "AL SAMER FOOTWEAR STORE",
            "aliasName": "AL SAMER FOOTWEAR STORE",
            "code": "188",
            "isGroup": 0,
            "balance": "0",
            "parentID": 182,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.577"
        },
        {
            "keyField": 189,
            "id": 189,
            "accountGroup": "AL SAMER HOUSEHOLD STORE",
            "aliasName": "AL SAMER HOUSEHOLD STORE",
            "code": "189",
            "isGroup": 1,
            "balance": "0",
            "parentID": null,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.580"
        },
        {
            "keyField": 190,
            "id": 190,
            "accountGroup": "AL SAMER ELECTRONICS STORE",
            "aliasName": "AL SAMER ELECTRONICS STORE",
            "code": "190",
            "isGroup": 0,
            "balance": "0",
            "parentID": 189,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.583"
        },
        {
            "keyField": 191,
            "id": 191,
            "accountGroup": "AL SAMER APPLIANCES STORE",
            "aliasName": "AL SAMER APPLIANCES STORE",
            "code": "191",
            "isGroup": 0,
            "balance": "0",
            "parentID": 189,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.587"
        },
        {
            "keyField": 192,
            "id": 192,
            "accountGroup": "AL SAMER FURNITURE APPLIANCES STORE",
            "aliasName": "AL SAMER FURNITURE APPLIANCES STORE",
            "code": "192",
            "isGroup": 0,
            "balance": "0",
            "parentID": 189,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.590"
        },
        {
            "keyField": 193,
            "id": 193,
            "accountGroup": "AL SAMER OTHER STORE",
            "aliasName": "AL SAMER OTHER STORE",
            "code": "193",
            "isGroup": 0,
            "balance": "0",
            "parentID": 189,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.593"
        },
        {
            "keyField": 194,
            "id": 194,
            "accountGroup": "AL SAMER MISC STORE",
            "aliasName": "AL SAMER MISC STORE",
            "code": "194",
            "isGroup": 0,
            "balance": "0",
            "parentID": 189,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.597"
        },
        {
            "keyField": 195,
            "id": 195,
            "accountGroup": "AL SHAHBA STORE",
            "aliasName": "AL SHAHBA STORE",
            "code": "195",
            "isGroup": 0,
            "balance": "0",
            "parentID": 189,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.600"
        },
        {
            "keyField": 196,
            "id": 196,
            "accountGroup": "AL KHALDI STORE",
            "aliasName": "AL KHALDI STORE",
            "code": "196",
            "isGroup": 0,
            "balance": "0",
            "parentID": 189,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.603"
        },
        {
            "keyField": 197,
            "id": 197,
            "accountGroup": "AL SAMER MOBILE STORE",
            "aliasName": "AL SAMER MOBILE STORE",
            "code": "197",
            "isGroup": 0,
            "balance": "0",
            "parentID": 189,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.607"
        },
        {
            "keyField": 198,
            "id": 198,
            "accountGroup": "AL SAMER ANTIQUE STORE",
            "aliasName": "AL SAMER ANTIQUE STORE",
            "code": "198",
            "isGroup": 0,
            "balance": "0",
            "parentID": 189,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.610"
        },
        {
            "keyField": 199,
            "id": 199,
            "accountGroup": "AL SAMER FASHION STORE",
            "aliasName": "AL SAMER FASHION STORE",
            "code": "199",
            "isGroup": 0,
            "balance": "0",
            "parentID": 189,
            "createdUser": "admin",
            "createdDate": "2017-06-20T14:41:19.613"
        }
    ]
    
      
      
      
      
