export const employees44 =[
    {
        "KeyField": 1,
        "ID": 1,
        "AccountGroup": "Chart of Accounts",
        "AliasName": "",
        "Code": "1",
        "IsGroup": 0,
        "Balance": "",
        "ParentID": null,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 2,
        "ID": 2,
        "AccountGroup": "Balance Sheet",
        "AliasName": "ورقة التوازن",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 1,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 3,
        "ID": 3,
        "AccountGroup": "Profit & Loss Account",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 1,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 4,
        "ID": 4,
        "AccountGroup": "Assets",
        "AliasName": "الأصول",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 2,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 5,
        "ID": 5,
        "AccountGroup": "Liabilities",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 2,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 6,
        "ID": 6,
        "AccountGroup": "Current Asset",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 4,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 7,
        "ID": 7,
        "AccountGroup": "Fixed Asset",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 4,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 8,
        "ID": 8,
        "AccountGroup": "Income",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 3,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 9,
        "ID": 9,
        "AccountGroup": "Expense",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 3,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 10,
        "ID": 10,
        "AccountGroup": "Direct Income",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 8,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 11,
        "ID": 11,
        "AccountGroup": "Indirect Income",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 8,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 12,
        "ID": 12,
        "AccountGroup": "Cash In hand",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 6,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 13,
        "ID": 13,
        "AccountGroup": "Bank Account",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 6,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 14,
        "ID": 14,
        "AccountGroup": "Current Liability",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 5,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 15,
        "ID": 15,
        "AccountGroup": "Capital Account",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 5,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 16,
        "ID": 16,
        "AccountGroup": "Suspense Account",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 5,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 17,
        "ID": 17,
        "AccountGroup": "Indirect Expense",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 9,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 18,
        "ID": 18,
        "AccountGroup": "Salaries",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 14,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 19,
        "ID": 19,
        "AccountGroup": "Direct Expence",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 9,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 20,
        "ID": 20,
        "AccountGroup": "Projects",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 10,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 22,
        "ID": 22,
        "AccountGroup": "Account Payable",
        "AliasName": "حساب المستحق",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 14,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 23,
        "ID": 23,
        "AccountGroup": "Purchase Accounts",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 19,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 24,
        "ID": 24,
        "AccountGroup": "Salary Account",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 17,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 25,
        "ID": 25,
        "AccountGroup": "Sales Incentive",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 17,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 26,
        "ID": 26,
        "AccountGroup": "Sales Accounts",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 10,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 27,
        "ID": 27,
        "AccountGroup": "Stock In Hand",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 6,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 28,
        "ID": 28,
        "AccountGroup": "Loan & Advances (Asset)",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 6,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 29,
        "ID": 29,
        "AccountGroup": "Loan(Liability)",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 5,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 30,
        "ID": 30,
        "AccountGroup": "Investments",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 7,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 31,
        "ID": 31,
        "AccountGroup": "Duties & Taxes",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 14,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 32,
        "ID": 32,
        "AccountGroup": "Deposits (Asset)",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 6,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 33,
        "ID": 33,
        "AccountGroup": "Provisions",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 14,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 34,
        "ID": 34,
        "AccountGroup": "Reserves & Surplus",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 15,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 35,
        "ID": 35,
        "AccountGroup": "Bank OD A/c",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 29,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 36,
        "ID": 36,
        "AccountGroup": "Discount Given",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 19,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 37,
        "ID": 37,
        "AccountGroup": "Discount Recieved",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 10,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 76,
        "ID": 76,
        "AccountGroup": "Duties & Taxes (In)",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 31,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 77,
        "ID": 77,
        "AccountGroup": "Duties & Taxes (Out)",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 31,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 154,
        "ID": 154,
        "AccountGroup": "Account Receivable",
        "AliasName": "حساب العميل",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 6,
        "CreatedUser": "admin",
        "CreatedDate": "1980-01-01 12:00:00.000"
    },
    {
        "KeyField": 159,
        "ID": 159,
        "AccountGroup": "Job Works",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 19,
        "CreatedUser": "admin",
        "CreatedDate": "2014-08-16 11:10:00.173"
    },
    {
        "KeyField": 175,
        "ID": 175,
        "AccountGroup": "Branch Receivable",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 154,
        "CreatedUser": "admin",
        "CreatedDate": "2015-02-16 14:39:24.210"
    },
    {
        "KeyField": 176,
        "ID": 176,
        "AccountGroup": "Branch Payable",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 22,
        "CreatedUser": "admin",
        "CreatedDate": "2015-02-16 14:39:24.240"
    },
    {
        "KeyField": 179,
        "ID": 179,
        "AccountGroup": "Owners Current Account",
        "AliasName": "",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 6,
        "CreatedUser": "admin",
        "CreatedDate": "2021-05-18 16:27:00.017"
    },
    {
        "KeyField": 180,
        "ID": 180,
        "AccountGroup": "gdfgdfgdfgdg",
        "AliasName": "string",
        "Code": "",
        "IsGroup": 1,
        "Balance": "",
        "ParentID": 22,
        "CreatedUser": "",
        "CreatedDate": "2024-08-28 21:03:33.660"
    },
    
        {
            "KeyField": 191,
            "ID": 1,
            "AccountGroup": "CASH A/C",
            "AliasName": "",
            "Code": "12221",
            "IsGroup": 0,
            "Balance": "",
            "ParentID": 12,
            "CreatedUser": "admin",
            "CreatedDate": "2015-06-11 18:22:24.037"
        },
        {
            "KeyField": 193,
            "ID": 3,
            "AccountGroup": "Sales Account",
            "AliasName": "",
            "Code": "SA",
            "IsGroup": 0,
            "Balance": "",
            "ParentID": 26,
            "CreatedUser": "admin",
            "CreatedDate": "2015-06-11 18:22:24.043"
        },
        {
            "KeyField": 194,
            "ID": 4,
            "AccountGroup": "Sales Return Account",
            "AliasName": "",
            "Code": "SRA",
            "IsGroup": 0,
            "Balance": "",
            "ParentID": 26,
            "CreatedUser": "admin",
            "CreatedDate": "2015-06-11 18:22:24.043"
        },
        {
            "KeyField": 195,
            "ID": 5,
            "AccountGroup": "Purchase Account",
            "AliasName": "",
            "Code": "PA",
            "IsGroup": 0,
            "Balance": "",
            "ParentID": 23,
            "CreatedUser": "admin",
            "CreatedDate": "2015-06-11 18:22:24.043"
        },
        {
            "KeyField": 196,
            "ID": 6,
            "AccountGroup": "Purchase Return Account",
            "AliasName": "",
            "Code": "PRA",
            "IsGroup": 0,
            "Balance": "",
            "ParentID": 23,
            "CreatedUser": "admin",
            "CreatedDate": "2015-06-11 18:22:24.047"
        },
        {
            "KeyField": 197,
            "ID": 7,
            "AccountGroup": "Input VAT",
            "AliasName": "",
            "Code": "IV",
            "IsGroup": 0,
            "Balance": "",
            "ParentID": 31,
            "CreatedUser": "admin",
            "CreatedDate": "2015-06-11 18:22:24.047"
        },
        {
            "KeyField": 198,
            "ID": 8,
            "AccountGroup": "Output VAT",
            "AliasName": "",
            "Code": "OV",
            "IsGroup": 0,
            "Balance": "",
            "ParentID": 31,
            "CreatedUser": "admin",
            "CreatedDate": "2015-06-11 18:22:24.050"
        },
        {
            "KeyField": 199,
            "ID": 9,
            "AccountGroup": "Suspense Account",
            "AliasName": "",
            "Code": "SUSP",
            "IsGroup": 0,
            "Balance": "",
            "ParentID": 16,
            "CreatedUser": "admin",
            "CreatedDate": "2015-06-11 18:22:24.050"
        },
        {
            "KeyField": 200,
            "ID": 10,
            "AccountGroup": "Discount Given",
            "AliasName": "",
            "Code": "DG",
            "IsGroup": 0,
            "Balance": "",
            "ParentID": 36,
            "CreatedUser": "admin",
            "CreatedDate": "2015-06-11 18:22:24.050"
        },
        {
            "KeyField": 201,
            "ID": 11,
            "AccountGroup": "Discount Received",
            "AliasName": "",
            "Code": "DR",
            "IsGroup": 0,
            "Balance": "",
            "ParentID": 37,
            "CreatedUser": "admin",
            "CreatedDate": "2015-06-11 18:22:24.050"
        },
        {
            "KeyField": 205,
            "ID": 15,
            "AccountGroup": "Input CST",
            "AliasName": "",
            "Code": "IC",
            "IsGroup": 0,
            "Balance": "",
            "ParentID": 31,
            "CreatedUser": "admin",
            "CreatedDate": "2015-06-11 18:22:24.053"
        },
        {
            "KeyField": 206,
            "ID": 16,
            "AccountGroup": "Output CST",
            "AliasName": "",
            "Code": "OC",
            "IsGroup": 0,
            "Balance": "",
            "ParentID": 31,
            "CreatedUser": "admin",
            "CreatedDate": "2015-06-11 18:22:24.053"
        },
        {
            "KeyField": 207,
            "ID": 17,
            "AccountGroup": "Sales Incentive",
            "AliasName": "",
            "Code": "SAInc",
            "IsGroup": 0,
            "Balance": "",
            "ParentID": 25,
            "CreatedUser": "admin",
            "CreatedDate": "2015-06-11 18:22:24.053"
        },
        {
            "KeyField": 208,
            "ID": 18,
            "AccountGroup": "Branch Payable Account",
            "AliasName": "",
            "Code": "BPA",
            "IsGroup": 0,
            "Balance": "",
            "ParentID": 176,
            "CreatedUser": "admin",
            "CreatedDate": "2015-06-11 18:22:24.053"
        },
        {
            "KeyField": 209,
            "ID": 19,
            "AccountGroup": "SALARY ACCOUNT",
            "AliasName": "",
            "Code": "SALAC",
            "IsGroup": 0,
            "Balance": "",
            "ParentID": 24,
            "CreatedUser": "admin",
            "CreatedDate": "2015-06-11 18:40:45.787"
        },
        {
            "KeyField": 210,
            "ID": 20,
            "AccountGroup": "1649-QAMAR AL LAYAL TRADING CO - AL NASEEM",
            "AliasName": "1649-SAFEENA STORE - AL NASEEM",
            "Code": "1649",
            "IsGroup": 0,
            "Balance": "",
            "ParentID": 154,
            "CreatedUser": "admin",
            "CreatedDate": "2017-06-20 14:41:18.553"
        },
        {
            "KeyField": 211,
            "ID": 21,
            "AccountGroup": "1741-BSHYYAH TRADING COMPANY PUMB - HAMDANIYA",
            "AliasName": "1741-BEESHA STORE-HERRA",
            "Code": "1741",
            "IsGroup": 0,
            "Balance": "",
            "ParentID": 154,
            "CreatedUser": "admin",
            "CreatedDate": "2017-06-20 14:41:18.983"
        }
    ]
    

