import { productDto } from "./products-type";

const initialProductData: productDto = {
  product: {
    productID: 1,
    productCode: "",
    productName: "",
    productGroupId: 101,
    productCategoryID: 201,
    supplyMethod: "Direct",
    hsnCode: "",
    commodityCode: "",
    active: true,
    aliasItemCode: "",
    aliasItemName: "",
    remarks: "",
    unitID: 1,
    minimumStock: 10,
    maximumStock: 100,
    reorderLevel: 20,
    reorderQty: 30,
    secondLanguage: "",
    marginPercentage: 15,
    canSale: true,
    canPurchase: true,
    canManufacture: false,
    itemType: "",
    createdUserID: 1,
    supplierID: 1,
    taxCategoryID: 1,
    batchCriteria: "FIFO",
    isRawMaterial: false,
    isFinishedGood: true,
    isWeighingScale: false,
    unitQty: 1,
    packingSlip: true,
    financialYearID: 2023
  },
  productValidation: {
    productName: "",
    productGroupId: "101",
    unitID: "1",
    commodityCode: "",
    taxCategoryID: 0,
    productCategoryID: "201",
    defSalesUnitID: "1",
    defPurchaseUnitID: "1",
    defReportUnitID: "1",
    brandID: "1",
    salesPrice: "100",
    stdSalesPrice: "90"
  },
  batch: {
    productID: 1,
    productBatchID: 1,
    manualBarcode: "BATCH001",
    brandID: 1,
    stdPurchasePrice: 80,
    stdSalesPrice: 100,
    mrp: 120,
    warehouseID: 1,
    shelfID: 1,
    specification: "Sample Specification",
    batchNo: "BATCH001",
    modifiedUserID: 1,
    isActive: true,
    mfgDate: new Date("2023-01-01"),
    expiryDate: new Date("2024-01-01"),
    margingPerc: 20,
    supplierLedgerID: 1,
    voucherType: "Sales",
    systemName: "System1",
    unitID2: 2,
    unit2Qty: 10,
    unit2SalesRate: 95,
    unit2MRP: 115,
    autoBarcode: 123456,
    unitMBarCode: "MBARCODE001",
    unit3ID: 3,
    unit3Qty: 5,
    unit2Barcode: "BARCODE002",
    unit3Barcode: "BARCODE003",
    unit3SalesPrice: 90,
    unit3MRP: 110,
    unit2MinSalesRate: 85,
    unit3MinSalesRate: 80,
    basicUnitID: 1,
    defSalesUnitID: 1,
    defPurchaseUnitID: 1,
    defReportUnitID: 1,
    location: "Warehouse A",
    displayCost: 75,
    modelNumber: "MODEL001",
    upcCode: "UPC001",
    packing: 1,
    packingUnitID: 1,
    onlineStatus: true,
    openingStock: 50,
    openingStockNOs: 50,
    openingDate: new Date("2023-01-01"),
    warrantyPeriod: "1 Year",
    partNumber: "PART001",
    refItemID: 1,
    refItemName: "Reference Item",
    landingCost: 70,
    stockIN: 100,
    createdUserID: 1,
    isForm6_2: false,
    freeBatchID: 1,
    gatePass: true,
    selectedProductBatchID: 1,
    selectedUnitID: 1,
    prevProductBatchID: 1,
    supplierWiseBatchCreation: true,
    baseUnitRemarks: "Base Unit Remarks"
  },
  moreInfo: {
    id: 1,
    productId: 1,
    notes1: "Note 1",
    notes2: "Note 2",
    notes3: "Note 3",
    notes4: "Note 4",
    notes5: "Note 5",
    notes6: "Note 6",
    notes7: "Note 7",
    notes8: "Note 8",
    notes9: "Note 9",
    notes10: "Note 10"
  },
  prices: [
    {
      productMultiPriceID: 1,
      productBatchID: 1,
      priceCategoryID: 1,
      salesPrice: 100,
      purchasePrice: 80,
      discountPerc: 10,
      unitID: 1,
      profitAmt: 20,
      mrp: 120,
      msp: 90
    }
  ],
  units: [
    {
      productUnitID: 1,
      productBatchID: 1,
      unitID: 1,
      multiFactor: 1,
      barCode: "UNIT001",
      sprice: 100,
      description: "Unit Description",
      descriptionFL: "Unit Description FL",
      unitRemarks: "Unit Remarks",
      gatePass: true,
      multiBarcodes: "MULTIBARCODE001"
    }
  ],
  nutrients: [
    {
      nutrients: "Protein",
      valuePerServing: "10g"
    }
  ],
  supplierProducts: [
    {
      ledgerID: 1,
      refCode: "SUP001"
    }
  ],
  config: {
    showProductDuplicateWarning: true,
    showProductDetailesAfterSave: true,
    blockConvertProductNameToUpperCase: false,
    calculateMarkUpValue: true,
    showDisplayCost: true
  }
};

export default initialProductData;