import { productDto } from "./products-type";

const initialProductData: productDto = {
  product: {
    productID: 0,
    productCode: "",
    productName: "",
    productGroupID: -2,
    productCategoryID: 0,
    supplyMethod: "",
    hsnCode: "",
    commodityCode: "",
    isActive: true,
    aliasItemCode: "",
    aliasItemName: "",
    remarks: "",
    minimumStock: 0,
    maximumStock: 0,
    reorderLevel: 0,
    reorderQty: 0,
    secondLanguage: "",
    marginPercentage: 0,
    canSale: true,
    canPurchase: true,
    canManufacture: false,
    itemType: "",
    createdUserID: 0,
    supplierID: 0,
    taxCategoryID: -2,
    batchCriteria: "",
    isRawMaterial: false,
    isFinishedGood: true,
    isWeighingScale: false,
    unitQty: 1,
    packingSlip: true,
    financialYearID: 0,
    basicUnitID: -2,
    sectionID: 0,
    defaultVendorID: -2,
    basicUnitName: ""
  },
  productValidation: {
    productName: "",
    productGroupId: "",
    unitID: "",
    commodityCode: "",
    taxCategoryID: "",
    productCategoryID: "",
    defSalesUnitID: "",
    defPurchaseUnitID: "",
    defReportUnitID: "",
    brandID: "",
    salesPrice: "",
    stdSalesPrice: ""
  },
  batch: {
    productID: 0,
    productBatchID: 0,
    manualBarcode: "",
    brandID: 0,
    stdPurchasePrice: 0,
    stdSalesPrice: 0,
    mrp: 0,
    warehouseID: 0,
    shelfID: 0,
    specification: "",
    batchNo: "",
    modifiedUserID: 0,
    isActive: true,
    mfgDate: new Date("2023-01-01"),
    expiryDate: new Date("2024-01-01"),
    margingPerc: 0,
    supplierLedgerID: 0,
    voucherType: "",
    systemName: "",
    unitID2: 0,
    unit2Qty: 0,
    unit2SalesRate: 0,
    unit2MRP: 0,
    autoBarcode: 0,
    unitMBarCode: "",
    unit3ID: 0,
    unit3Qty: 0,
    unit2Barcode: "",
    unit3Barcode: "",
    unit3SalesPrice: 0,
    unit3MRP: 0,
    unit2MinSalesRate: 0,
    unit3MinSalesRate: 0,
    basicUnitID: 0,
    defSalesUnitID: 0,
    defPurchaseUnitID: 0,
    defReportUnitID: 0,
    location: "",
    displayCost: 0,
    modelNumber: "",
    upcCode: "",
    packing: 0,
    packingUnitID: 0,
    onlineStatus: true,
    openingStock: 0,
    openingStockNOs: 0,
    openingDate: new Date("2023-01-01"),
    warrantyPeriod: "",
    partNumber: "",
    refItemID: 0,
    refItemName: "",
    landingCost: 0,
    stockIN: 0,
    createdUserID: 0,
    isForm6_2: false,
    freeBatchID: 0,
    gatePass: true,
    selectedProductBatchID: 0,
    selectedUnitID: 0,
    prevProductBatchID: 0,
    supplierWiseBatchCreation: true,
    baseUnitRemarks: "",
    aPC: 0,
    stock: 0
  },
  moreInfo: {
    id: 0,
    productId: 0,
    notes1: "",
    notes2: "",
    notes3: "",
    notes4: "",
    notes5: "",
    notes6: "",
    notes7: "",
    notes8: "",
    notes9: "",
    notes10: ""
  },
  prices: [],
  units: [],
  nutrients: [
    {
      nutrients: "",
      valuePerServing: 0
    }
  ],
  supplierProducts: [],
  config: {
    showProductDuplicateWarning: true,
    showProductDetailesAfterSave: true,
    blockConvertProductNameToUpperCase: false,
    calculateMarkUpValue: true,
    showDisplayCost: true,
    showOpeningStock: false
  },
  productImageString: "",
  barcode: "",
  sectionID: 0,
  upcBarcode: false,
  mu: false,
  mr: false,
  markup: "",
  batchCriteria: false,
  details: false,
  onHold: false,
  taxCategoryTaxPercentage: 0,
  hasDisabled: false
};

export default initialProductData;