export const initialAccountGroup = {
  data: {
    ledgerID: 0,
    branchID: 0,
    ledgerName: '',
    accGroupID: 0,
    ledgerCode: '',
    aliasName: '',
    isEditable: true,
    isBillwiseApplicable: true,
    isDeletable: true,
    remarks: '',
    isIncomeLedger: true,
    isActive: true,
    createdUserID: 0,
    modifiedUserID: 0,
    isProtected: true,
    isCommon: true,
    accTransactionID: 0,
    isCostCentreApplicable: '',
    arabicName: ''
  },
  validations: {
    ledgerID: '',
    branchID: '',
    ledgerName: '',
    accGroupID: '',
    ledgerCode: '',
    aliasName: '',
    isEditable: '',
    isBillwiseApplicable: '',
    isDeletable: '',
    remarks: '',
    isIncomeLedger: '',
    isActive: '',
    createdUserID: '',
    modifiedUserID: '',
    isProtected: '',
    isCommon: '',
    accTransactionID: '',
    isCostCentreApplicable: '',
    arabicName: ''
  },
};