import config from "../config";

export const domain = config.api.APP_API_URL;
export const signupUrl = import.meta.env.VITE_SIGNUP;
export const companyName = import.meta.env.VITE_COMPANY_NAME;

export const cdnUrl = import.meta.env.VITE_CDN_URL;
export const projectName = import.meta.env.VITE_PROJECT_NAME;

const Urls = {
  domain,
  upload: "/",
  user: "/user",
  imgBaseUrl: "/",
  host: `${domain}/`,
  baseUrl: `${domain}/api`,

  // Dropdown - core
  data_countries: "/Data/Countries/",
  data_states: "/Data/States/",
  data_currencies: "/Data/Currencies/",
  data_industries: "/Data/Industries/",
  data_stock_valuation_methods: "/Data/StockValuationMethods/",
  data_salesRoute: "/Data/SalesRoutes/",
  data_form_type: "/Data/FormTypes/",
  data_warehouse: "/Data/Warehouses/",
  data_scheme_master: "/Data/SchemeMaster/",
  data_employees: "/Data/Employees",
  data_user_types: "/Data/UserTypes/",
  data_users: "/Data/users/",
  data_duties_taxes: "/Data/Duties&Taxes/",
  data_batchcriteria: "/Data/BatchCriterias/",
  data_pricectegory: "/Data/PriceCategories/",
  data_languages: "/Data/Languages/",
  data_counters: "/Data/Counters/",
  data_templates: "/Data/Templates/",
  data_cashLedger: "/Data/CashLedgers/",

  // Dropdown - accounts
  data_acc_groups: "/Accounts/Data/AccGroups/",
  data_acc_Branches: "/Data/BranchWithoutDefault",
  data_acc_Branches_All: "/Data/Branches",
  data_acc_ledgers: "/Accounts/Data/AccLedgers/",
  // data_acc_ledgers_Code: "/Accounts/Data/LedgerCode/",
  data_costcentres: "/Accounts/Data/CostCentres/",
  data_parties: "/Accounts/Data/Parties/",
  data_party_categories: "/Accounts/Data/PartyCategories/",
  data_privilage_cards: "/Accounts/Data/PrivilageCards/",
  data_projects: "/Accounts/Data/Projects/",
  data_projects_by_ledgerid: "/Accounts/Data/ProjectsByLedger/",
  data_upis: "/Accounts/Data/UPIs/",
  data_vouchertype: "/Accounts/Data/VoucherType",
  data_InputCalamity: "/Accounts/Data/InputCalamity",
  data_FormTypeBySI: "/Accounts/Data/FormTypeBySI",
  data_FormTypeBySR: "/Accounts/Data/FormTypeBySR",
  data_VPrefixForSI: "/Accounts/Data/VPrefixForSI",
  data_VPrefixForSR: "/Accounts/Data/VPrefixForSR",
  data_CashLedgers: "/Accounts/Data/CashLedgers",
  data_SuspenseAccount: "/Accounts/Data/SuspenseAccount",
  data_BankAccounts: "/Accounts/Data/BankAccounts",
  data_SalesAccount: "/Accounts/Data/SalesAccount",
  data_FormTypeByPI: "/Accounts/Data/FormTypeByPI",
  data_FormTypeByPR: "/Accounts/Data/FormTypeByPR",
  data_SelectAccGroupsUnderAccGroupIDForCombo: "/Accounts/Data/SelectAccGroupsUnderAccGroupIDForCombo/",
  data_SelectAccLedgersByAccGroupIDForCombo: "/Accounts/Data/SelectAccLedgersByAccGroupIDForCombo/",
  data_PurchaseAccount: "/Accounts/Data/PurchaseAccount/",
  data_BranchRecPayAccount: "/Accounts/Data/BranchRecPayAccount/",
  data_CustSupp: "/Accounts/Data/CustomerAndSupplier/",
  data_party_color: "",
  data_getNextLedgerCode: "/Accounts/AccLedger/GetNextLedgerCode/",
  // Dropdown - inventory
  data_productgroup: "/Inventory/Data/ProductGroup",
  data_products: "/Inventory/Data/Products",
  data_brands: "/Inventory/Data/Brands",
  data_color: "/Inventory/Data/Color",
  data_warranty: "/Inventory/Data/Warranty",
  data_sections: "/Inventory/Data/Sections",
  data_groupcategory: "/Inventory/Data/GroupCategory",
  data_locations: "/Inventory/Data/Locations",
  data_productcategory: "/Inventory/Data/ProductCategory",
  data_services: "/Inventory/Data/Services",
  data_mainsalesroute: "/Inventory/Data/MainSalesRoute",
  data_units: "/Inventory/Data/UnitOfMeasures",
  data_taxCategory:"/Inventory/Data/TaxCategory/",

  //Dropdown - settings
  data_base_currency: "/Core/ExchangeRates/GetExchangeRatesData/",
  data_company_id: "/Core/Branch/GetBranchData",

  // Auth
  login: "/login/",
  logout: "/logout/",
  password_reset: "/passwordReset/",
  password_reset_confirm: "/resetPassword/",
  social_signup: "/socialSignup/",
  set_branch: "/Subscription/Auth/SetBranch/",
  SendEmailToken: "/Subscription/Auth/SendEmailToken",
  ValidateToken: "/Subscription/Auth/ValidateToken",
  SendSmsOtp: "/Subscription/Auth/SendSmsOtp",
  get_login_credentials: "/Subscription/Auth/LoginCredentials/",
  sent_token: "/Subscription/Auth/SendTokenAsync",
  validate_token: "/Subscription/Auth/ValidateTokenAsync",
  reset_password: "/Subscription/Auth/ResetPasswordAsync",

  // App
  application_setting: "/Core/ApplicationSettings/",
  getUserAppSetting: "/User/getUserAppSetting/",
  updateUserAppSetting: "/User/updateUserAppSetting",

  // AccountSettings/Profile
  uploadUserImage: "/Subscription/Profile/UploadUserImage/",
  changeEmailRequest_profile: "/Subscription/Profile/ChangeEmailRequest/",
  verifyEmail_profile: "/Subscription/Profile/VerifyEmail/",
  changePhoneRequest_profile: "/Subscription/Profile/ChangePhoneRequest/",
  changePhone: "/Subscription/Profile/ChangePhone/",
  verifyPhone_profile: "/Subscription/Profile/VerifyPhone/",
  updateUserBasicInfo: "/Subscription/Profile/ChangeBasicInfo/",
  getUserBasicInfo: "/Subscription/Profile/GetBasicInfo/",
  getEmail_profile: "/Subscription/Profile/GetEmail/",
  getPhone_profile: "/Subscription/Profile/GetPhone/",
  getImage_profile: "/Subscription/Profile/GetProfileImage/",
  getUserSession: "/Core/LoginSessions/GetAllAsync/",
  logoutUserSession: "/Core/LoginSessions/InActiveSession/",
  uploadCompanyLogo: "/Subscription/WorkSpace/UploadCompanyLogo/",
  changeEmailRequest_workspace: "/Subscription/WorkSpace/ChangeEmailRequest/",
  verifyEmail_workspace: "/Subscription/WorkSpace/VerifyEmail/",
  updateCompanyEmail_workspace: "/Subscription/WorkSpace/UpdateCompanyEmailAsync/",
  UpdateCompanyPhone_workspace: "/Subscription/WorkSpace/UpdateCompanyPhoneAsync/",
  changePhoneRequest_workspace: "/Subscription/WorkSpace/ChangePhoneRequest/",
  changePhone_workspace: "/Subscription/WorkSpace/UpdateCompanyPhoneAsync/",
  verifyPhone_workspace: "/Subscription/WorkSpace/VerifyPhone/",
  changeBasicInfo_workspace: "/Subscription/WorkSpace/ChangeBasicInfo/",
  changeAddress_workspace: "/Subscription/WorkSpace/ChangeAddress/",
  getBasicInfo_workspace: "/Subscription/WorkSpace/GetBasicInfo/",
  getEmail_workspace: "/Subscription/WorkSpace/GetEmail/",
  getPhone_workspace: "/Subscription/WorkSpace/GetPhone/",
  getLogo_workspace: "/Subscription/WorkSpace/GetLogo/",
  getAddress_workspace: "/Subscription/WorkSpace/GetAddress/",
  delete_workspace: "/Subscription/WorkSpace/DeleteWorkspace/",
  get_members: "/Subscription/WorkSpace/GetMembers/",

  // AccountSettings/Security
  updatePassword: "/Subscription/AccountSettings/Security/ResetPassword/",

  // AccountSettings/Preferences
  updateLanguage: "/Core/Preferences/UpdateLanguage/",
  updatePreference: "/Core/Preferences/UpdatePreference/",
  updateUserThemes: "/Core/Preferences/UpdateUserThemes/",
  getLanguage: "/Core/Preferences/GetLanguage/",
  getPreference: "/Core/Preferences/GetPreference/",
  getDateRegion: "/Core/Preferences/GetDateRegion/",
  getUserThemes: "/Core/Preferences/GetUserThemes/",
  reset_user_theme: "/Core/Preferences/ResetUserTheme/",
  reset_user_settings: "/Core/Preferences/ResetUserSettings/",
  // AccountSettings/UserBranches
  userBranches: "/Core/UserBranches/",
  deleteUserBranches: "/Core/UserBranches/{Id}/",
  //setting
  //setting/userManagement
  Users: "/Subscription/User/",
  // getUserSubscripeByName:'/Subscription/User/GetUser/:id?UserName=',
  patchUserSubscriped: "/Subscription/User/EditUser/",
  UserTypes: "/Core/UserType/",
  user_rights: "/Core/UserRights/",

  //setting/Administrations
  CompanyProfiles: "/Core/CompanyProfile/",
  CompanyProfileIndia: "/Core/CompanyDetails/",
  Branch: "/Subscription/Branch/",
  BranchInfo: "/Core/Branch/BranchInfo/",
  branch_code: "/Branch/GetNextBranchCode/",
  BankPosSettings: "/Core/BankPOS/AddCounter/",
  deleteInactiveTransactions: "/Core/DeleteInActive/",

  //setting/system
  get_userLedger_by_user_id: "/Accounts/AccLedger/GetUserLedgerByUserID/",

  counter_settings: "/Core/CounterSettings/",
  counter_settings_current_data: "/Core/CounterSettings/GetCurrentCounter/",
  Counter: "/Core/Counter/",
  Voucher: "/Core/Vouchers/",
  FinancialYear: "/Core/FinancialYear/",
  DayClose: "/Core/DayClose/",
  Remainder: "/Core/Remainder/",
  userActionReport: "/Core/UserAction/Report",
  currencyExchange: "/Core/ExchangeRates/",
  currencyExchangeRate: "/Core/ExchangeRates/GetCurrencyExchangeRate",
  postCurrency: "/Accounts/Currency/",
  authorization_settings: "/Core/Authorization/",
  reset_data_base: "/Core/ResetDataBase/",
  application_settings: "/Core/ApplicationSettings/",
  application_settings_virtual: "/Core/ApplicationSettings/Virtual/",
  application_settings_GetSettingsScreen: "/Core/Preferences/GetSettingsScreen",
  application_settings_UpdateSettingsScreen: "/Core/Preferences/UpdateSettingsScreen",
  sql_commands: "/Core/SQLCommand/",
  notification_provider: "/Core/NotificationProvider/GetAllByChannel/",
  notification_provider_update: "/Core/NotificationProvider/UpdateConfig/",
  notification_provider_set_as_default: "/Core/NotificationProvider/SetAsDefault/",
  notification_provider_test: "/Core/NotificationProvider/TestConnection/",
  notification_transaction: "/Core/TransactionNotification",
  notification_template: "/Core/NotificationTemplate/",
  headers_footers: "/Core/HeaderFooter/",
  eWayBill: "/Core/EWayBillGST/",
  eInvoiceGST: "/Core/EInvoiceGST/",
  //setings/AdvanceOptions
  // advanceOptions:"/Core/AdvancedOptions",
  revertBillModifications: "/Core/AdvancedOptions/",
  branchDataReset: "/Core/AdvancedOptions/BranchDataReset/",
  // refresh all branches
  refreshAllBranches: "/Core/RefreshAllBranch/RefreshAllBranch/",
  //barcode
  barcodePrintGrid: "/Core/BarcodePrint/GetBarcodePrintGrid/",
  barcodePrintTransaction:
    "/Core/BarcodePrint/GetBarcodePrintGridFromTransaction/",
  // Accounts Start
  // Masters
  hide_Ledger: "/Accounts/HideLedger/",
  account_group: "/Accounts/AccGroup/",
  account_ledger: "/Accounts/AccLedger/",
  cost_center: "/Accounts/CostCenter/",
  account_privilege_card: "/Accounts/PrivilegeCards/",
  branch_ledger: "/Accounts/BranchLedgers/",
  account_party_category: "/Accounts/PartyCategory/",
  account_currency_master: "/Accounts/Currency/",
  chart_of_accounts: "/Accounts/ChartofAccounts/",
  chart_of_accounts_new: "/Accounts/ChartofAccounts/chartOfAccounts",
  parties: "/Accounts/Parties/",
  get_next_party_code: "/Accounts/Parties/GetNextPartyCode/",
  party_projects: "/Accounts/Project/",
  cust_supp_ledger: "/Accounts/CustSuppLedger/",
  upi: "/Accounts/UPI/",
  acc_group_order: "/Accounts/AccGroupOrderArrangement/",
  bankCards: "/Accounts/BankCards/",
  post_acc_user_config: "/Core/Preferences/UpdateLocalSettings",
  get_acc_user_config: "/Core/Preferences/GetLocalSettings",
  acc_attachment_upload: "/Core/AttachmentInfo/Upload/",
  acc_attachmentInfo_download: "/Core/AttachmentInfo/Download/",
  //Reports Start
  acc_reports_ledger: "/Accounts/RptLedgerReport/LedgerReport/",
  acc_reports_cash_book: "/Accounts/RptCashBook/CashBookLedgerSummary/",
  acc_reports_cash_book_monthwise: "/Accounts/RptCashBook/CashBookMonthwiseSummary/",
  acc_reports_cash_book_daywise: "/Accounts/RptCashBook/CashBookDaywiseSummary/",
  acc_reports_cash_book_transactionwise: "/Accounts/RptCashBook/CashBookDetailed/",
  acc_reports_day_book_detailed: "/Accounts/RptDayBook/DayBookDetailed/",
  acc_reports_day_book_summary: "/Accounts/RptDayBook/DayBookSummary/",
  acc_reports_day_book_billwise: "/Accounts/RptDayBook/DayBookSummaryBillwise/",
  acc_reports_payment: "/Accounts/RptPaymentReport/PaymentReport/",
  acc_reports_collection: "/Accounts/RptCollectionReport/CollectionReport/",
  acc_reports_cash_summary: "/Accounts/RptCashSummaryReport/CashSummary/",
  acc_reports_cash_summary_ledgerwise: "/Accounts/RptCashSummaryReport/CashSummaryLedgerwise/",
  acc_reports_transaction: "/Accounts/RptTransactionReport/TransactionReport/",
  acc_reports_inventory_history: "/Accounts/RptTransactionHistory/TransactionHistoryInventory/",
  acc_reports_inventory_history_popup: "/Accounts/RptTransactionHistory/ShowTransHistoryInventoryPopUp/",
  acc_reports_inventory_history_details: "/Accounts/RptTransactionHistory/ShowTransHistoryInventoryDetails/",
  acc_reports_accounts_history: "/Accounts/RptTransactionHistory/TransactionHistoryAccounts/",
  acc_reports_accounts_history_popup: "/Accounts/RptTransactionHistory/ShowTransHistoryAccountsPopUp/",
  acc_reports_daily_summary_global: "/Accounts/RptDailySummaryReport/DailySummaryReportGlobal/",
  acc_reports_daily_summary: "/Accounts/RptDailySummaryReport/DailySummaryReport/",
  acc_reports_daily_summary_detailed: "/Accounts/RptDailySummaryReport/DailySummaryDetailedReport/",
  acc_reports_daily_summary_credit_details: "/Accounts/RptDailySummaryReport/CreditSalesReportDaily/",
  acc_reports_daily_summary_receipt_details: "/Accounts/RptDailySummaryReport/SelectCashReceiptReportDaily/",
  acc_reports_billwise_profit: "/Accounts/RptBillWsieProfitReport/BillwiseProfit/",
  acc_reports_billwise_profit_global: "/Accounts/RptBillWsieProfitReport/BillwiseProfitGlobal/",
  acc_reports_party_summary_basic_info: "/Accounts/RptPartyWiseSummary/BasicInfo/",
  acc_reports_party_summary_ledger: "/Accounts/RptPartyWiseSummary/Ledger/",
  acc_reports_party_summary_payment: "/Accounts/RptPartyWiseSummary/Payment/",
  acc_reports_party_summary_collections: "/Accounts/RptPartyWiseSummary/collections/",
  acc_reports_party_summary_purchase: "/Accounts/RptPartyWiseSummary/Purchase/",
  acc_reports_party_summary_sales: "/Accounts/RptPartyWiseSummary/Sales/",
  acc_reports_party_summary_purchase_return: "/Accounts/RptPartyWiseSummary/PurchaseReturn/",
  acc_reports_party_summary_purchase_order: "/Accounts/RptPartyWiseSummary/PurchaseOrder/",
  acc_reports_party_summary_sales_return: "/Accounts/RptPartyWiseSummary/SalesReturn/",
  acc_reports_party_summary_sales_order: "/Accounts/RptPartyWiseSummary/SalesOrder/",
  acc_reports_bank_statement: "/Accounts/RptBankStatement/BankStatement/",
  acc_reports_payable: "/Accounts/RptOutstandingReport/Payable/",
  acc_reports_receivable: "/Accounts/RptOutstandingReport/Receivable/",
  // acc_reports_aging_payable: "/Accounts/RptAging/AgingPayable/",
  // acc_reports_aging_receivable: "/Accounts/RptAging/AgingReceivable/",
  acc_reports_trial_balance: "/Accounts/RptTrialBalance/TrialBalance/",
  acc_reports_trial_balance_detailed: "/Accounts/RptTrialBalance/TrialBalancePeriodwise/",
  acc_reports_balance_sheet: "/Accounts/RptBalanceSheet/BalanceSheet/",
  acc_reports_balance_sheet_vertical: "/Accounts/RptBalanceSheet/BalanceSheetDetailed/",
  acc_reports_account_ledger_balance_view: "/Accounts/RptBalanceSheet/AccountLedgerBalanceView/",
  acc_reports_profit_and_loss: "/Accounts/RptProfitAndLoss/ProfitAndLoss/",
  acc_reports_profit_and_loss_detailed: "/Accounts/RptProfitAndLoss/ProfitAndLossDetailed/",
  acc_reports_account_ledger_balance_view_sub_group_inc: "/Accounts/RptProfitAndLoss/AccountLedgerBalanceViewSubGroupIncluded/",
  acc_reports_closing_stock_details: "/Accounts/RptProfitAndLoss/ClosingStockDetails/",
  acc_reports_income_expense_report: "/Accounts/RptIncomeExpense/Expense/",
  acc_reports_income_expense_report_detailed: "/Accounts/RptIncomeExpense/ExpenseDetailed/",
  acc_reports_income_expense_statement: "/Accounts/RptIncomeExpense/IncomeExpenseStmt/",
  acc_reports_cash_flow: "/Accounts/RptCashFlowBankFlow/CashFlow/",
  acc_reports_bank_flow: "/Accounts/RptCashFlowBankFlow/BankFlow/",
  acc_reports_cash_bank_flow_detailed: "/Accounts/RptCashFlowBankFlow/CashBankFlowDetailed/",
  acc_reports_cash_bank_flow_detailed_summary: "/Accounts/RptCashFlowBankFlow/CashBankFlowNewDrilldown/",
  acc_reports_cash_bank_flow_detailed_summary_in: "/Accounts/RptCashFlowBankFlow/CashBankFlowdetailedDrilldownIN/",
  acc_reports_cash_bank_flow_detailed_summary_out: "/Accounts/RptCashFlowBankFlow/CashBankFlowdetailedDrilldownOut/",
  acc_reports_outstanding_aging_receivable: "/Accounts/RptAging/OutstandingAgingReceivable/",
  acc_reports_outstanding_aging_payable: "/Accounts/RptAging/OutstandingAgingPayable/",
  acc_reports_aging_analysis: "/Accounts/RptAging/AgingAnalysisReport/",

  //inventory
  inv_reports_price_list: "",
  inv_reports_stock_ledger: "",
  inv_reports_balance_report: "",
  inv_reports_stock_flow: "",
  purchase_summary_report: "/Inventory/RptPurchaseReport/PurchaseSummary/",
  purchase_register_report: "/Inventory/RptPurchaseReport/PurchaseRegister/",
  party_wise_report: "/Inventory/RptPurchaseReport/PartywisePurchase/",
  purchase_tax_report_detailed: "/Inventory/RptPurchaseReport/TaxReportPurchaseDetailed/",
  purchase_tax_report_summary: "/Inventory/RptPurchaseReport/TaxReportPurchaseSummary/",
  purchase_return_summary: "/Inventory/RptPurchaseReport/PurchaseReturnSummary/",
  purchase_return_register: "/Inventory/RptPurchaseReport/PurchaseReturnRegister/",
  purchase_estimate_summary: "/Inventory/RptPurchaseReport/PurchaseEstimateSummary/",
  purchase_order_summary: "/Inventory/RptPurchaseReport/PurchaseOrderSummary/",
  Purchase_tax: "/Inventory/RptTAXReport/MonthlyVATPurchaseStatement",
  inventory_reports_product_inventory: "/Inventory/RptPurchaseReport/PurchaseOrderTransitAndStockDetails",
  party_monthwise_purchase_summary: "/Inventory/RptPurchaseReport/PartyMonthwisePurchaseSummary",
  Credit_purchase_summary: "/Inventory/RptPurchaseReport/CreditPurchaseSummary",
  Purchase_Order_Transit_And_Stock_Details: "/Inventory/RptPurchaseReport/PurchaseOrderTransitAndStockDetails",
  daily_statement_all: "/Inventory/RptInventoryDailyStatementReport/DailyStatementReportAll",
  itemwise_purchase_summary: "/Inventory/RptItemwiseReport/ItemwisePurchaseSummary",
  item_wise_purchase_return_summary: "/Inventory/RptItemwiseReport/ItemwisePurchaseReturnSummary/",
  item_wise_purchase_order_summary: "/Inventory/RptItemwiseReport/ItemwisePurchaseOrderSummary/",
  item_wise_purchase_estimate_summary: "/Inventory/RptItemwiseReport/ItemwisePurchaseEstimateSummary/",
  item_wise_purchase_quotation_summary: "/Inventory/RptItemwiseReport/ItemwisePurchaseQuotationSummary/",
  product_summary_transaction: "/Inventory/RptInventoryReport/ProductSummaryReportByTransaction/",
  product_summary_basic_info: "/Inventory/RptInventoryReport/ProductSummaryReportBasicInfo/",
  product_summary_basic_info_batch_details: "/Inventory/RptInventoryReport/ProductSummaryReportBasicInfoBatchDetails/",
  product_summary_stock_ledger: "/Inventory/RptInventoryReport/ProductSummaryReportStockLedger/",
  opening_stock: "/Inventory/RptStockReport/OpeningStockReport/",
  stock_transfer: "/Inventory/RptStockReport/StockTransferReport/",
  damage_stock: "/Inventory/RptStockReport/DamageStockReport/",
  excess_stock: "/Inventory/RptStockReport/ExcessStockReport/",
  shortage_stock: "/Inventory/RptStockReport/ShortageStockReport/",
  branch_transfer_out: "/Inventory/RptStockReport/BranchTransferOut/",
  branch_transfer_in:"/Inventory/RptStockReport/BranchTransferIn/",
  branch_transfer_summary_out:"/Inventory/RptStockReport/BranchTransferSummaryOut/",
  branch_transfer_summary_in:"/Inventory/RptStockReport/BranchTransferSummaryIn/",
  sales_summary:"/Inventory/RptSalesReport/SalesSummary/",
  purchase_gst_daily_summary:"/api/Inventory/RptGSTReport/PurchaseTaxDailySummaryReport",
  purchase_gst_taxwise:"/api/Inventory/RptGSTReport/PurchaseTaxGSTTaxWiseReport",
  purchase_gst_taxwise_with_hsn:"/api/Inventory/RptGSTReport/PurchaseTaxGSTTaxWiseWithHSNReport",
  purchase_gst_monthly_summary:"/api/Inventory/RptGSTReport/PurchaseTaxGSTMonthlySummaryReport",
  purchase_gst_detailed:"/api/Inventory/RptGSTReport/PurchaseTaxGSTDetailedReport",
  purchase_gst_register_format:"/api/Inventory/RptGSTReport/PurchaseTaxRegisterFormatReport",
  purchase_gst_adv_register_format:"/api/Inventory/RptGSTReport/PurchaseTaxAdvRegisterFormatReport",
  purchase_return_gst_daily_summary:"/api/Inventory/RptGSTReport/PurchaseReturnTaxDailySummaryReport",
  purchase_return_gst_taxwise:"/api/Inventory/RptGSTReport/PurchaseReturnTaxGSTTaxWiseReport",
  purchase_return_gst_taxwise_with_hsn:"/api/Inventory/RptGSTReport/PurchaseReturnTaxGSTTaxWiseWithHSNReport",
  purchase_return_gst_monthly_summary:"/api/Inventory/RptGSTReport/PurchaseReturnTaxGSTMonthlySummaryReport",
  purchase_return_gst_detailed:"/api/Inventory/RptGSTReport/PurchaseReturnTaxGSTDetailedReport",
  purchase_return_gst_register_format:"/api/Inventory/RptGSTReport/PurchaseReturnTaxRegisterFormatReport",
  purchase_return_gst_adv_register_format:"/api/Inventory/RptGSTReport/PurchaseTaxAdvRegisterFormatReport",
  vat_return_form:"/Inventory/RptTAXReport/VatReturnForm",

  //Report End
  //Inventory Reports Starts
  //Purchase
  inv_reports_purchase_summary: "/Inventory/RptPurchaseReport/PurchaseSummaryTest/",
  // Transaction

  acc_transaction_base: "/Accounts/",
  acc_transaction_ledger_bill_wise: "/Accounts/BillwiseMaster",
  acc_transaction_is_bill_wise_trans_adjustment_exists: "/Accounts/BillwiseMaster/IsBillwiseTransAdjustmentExists",
  acc_transaction_grid: "/Accounts/CashPayment/List Page",
  acc_transaction_parties_tax_on_expense: "/Accounts/TXPayment/SearchParty/",

  // Accounts End
  //Grid Preference
  grid_preference: "/Core/GridPreference",
  grid_preference_reset: "/Core/GridPreference/Reset/",
  //Templates
  templates: "/Core/Template/",
  default_template: "Core/Template/Default",
  crm_templates: "/Core/Template/CRM/",
  // Tax Treatments
  tax_treatment: "api/tax_treatment/",

  //Import Excel
  import_parties: "/Accounts/Import/Parties/",
  import_parties_excel: "/Accounts/Import/PartiesExcel/",
  download_party_format: "/Accounts/Import/DownloadPartyFormat/",
  import_privilegeCards: "/Accounts/Import/PrivilegeCards/",
  import_privilegeCards_Excel: "/Accounts/Import/PrivilegeCardsExcel/",
  download_privilegeCards_format: "/Accounts/Import/DownloadPrivilegeCardsFormat/",

  // Inventory
  products: "/Inventory/Product/",
  get_product_config: "/Inventory/Product/GetProductConfig/",
  update_product_config: "/Inventory/Product/UpdateProductConfig/",
  change_barcode: "/Inventory/Product/ChangeProductAutoBarcode/",
  fast_moving_products: "/Inventory/FastMovingProducts/",
  product_scheme_details: "/Inventory/Schemes/GetProductSchemeDetails/",
  productGroup: "/Inventory/ProductGroup/",
  productCategory: "/Inventory/ProductCategory/",
  brands: "/Inventory/Brands/",
  priceCategory: "/Inventory/PriceCategory/",
  unitOfMeasure: "/Inventory/UnitofMeasures/",
  vehicles: "/Inventory/Vehicles/",
  schemes: "/Inventory/schemes/",
  Warehouse: "/Inventory/Warehouse/",
  taxCategory: "/Inventory/TaxCategory/",
  sales_man_route: "/Inventory/SalesManRoute/",
  salesRoute: "/Inventory/SalesRoute/",
  daily_statement_sales: "/Inventory/RptInventoryDailyStatementReport/DailyStatementReportSales",
  daily_statement_purchase: "/Inventory/RptInventoryDailyStatementReport/DailyStatementReportPurchase",
  section: "/Inventory/Section/",
  group_category__: "/Inventory/Product/SelectProductGroupDetails/",
  group_category: "/Inventory/GroupCategory/",
  payment_receipt_billwise_advice_for_print: "/Core/TransactionBase/PaymentReceiptBillwiseAdviceForPrint/",


  // URLs for SpecialPriceController (Inventory Module)
  insert_special_price_scheme: "/Inventory/SpecialPrice",                             // POST
  insert_special_price_scheme_by_group_id: "/Inventory/SpecialPrice/{groupId}",       // POST
  select_special_price_scheme_by_scheme_id: "/Inventory/SpecialPrice/BySchemeID",     // GET
  select_product_by_barcode: "/Inventory/SpecialPrice/ByBarcode/{barcode}",           // GET
  select_item_for_special_price_scheme_by_group_id: "/Inventory/SpecialPrice/ByGroupId{productGroupId}", // GET
  select_price_schemes_for_combo: "/Inventory/SpecialPrice/SpecialPriceCombo",        // GET
  delete_special_price_scheme: "/Inventory/SpecialPrice/{specialPriceId}",            // DELETE
  load_product_details: "/Inventory/SpecialPrice/LoadProductDetails",                 // GET (with body + query)
  select_foc_product_batch_grid: "/Inventory/SpecialPrice/LoadBatchDetails/{productId}", // GET
  

  //Transaction
  // common

  log_user_action: "/Core/UserAction/",
  get_last_voucher_no: "/Core/TransactionBase/GetNextVoucherNumber/",
  get_ledger_balance: "/Core/TransactionBase/GetLedgerBalance/",
  get_and_set_transaction_edit_mode: "/Core/TransactionBase/GetAndSetTransactionEditMode/",
  get_ledgerId_by_code: "/Core/TransactionBase/GetLedgerIdByCode/",
  get_ledgerCode_by_id: "/Core/TransactionBase/GetLedgerCodeById/",
  upsert_bill_modified_history: "/Core/TransactionBase/UpsertBillModifiedHistory/",
  unlock_acc_transaction_master: "/Core/TransactionBase/UnlockAccTransactionMaster/",
  ledgerDataForTransaction: "/Core/TransactionBase/ledgerDataForTransaction/",
  voucher_history: "/Core/UserAction/GetByVoucher/",
  voucher_selector: "/Core/VoucherSelector/",
  partiesBankNames: "/Core/TransactionBase/SelectPartiesBankNames",
  validate_cheque_status: "/Core/TransactionBase/ValidateChequeStatus/",
  get_currency_exchange_rate: "/Core/TransactionBase/GetCurrencyExchangeRate",
  is_ledger_billwise_applicable: "/Core/TransactionBase/IsLedgerBillwiseApplicable/",
  pdc: "/Accounts/PDC/",
  bankReconciliation: "/Accounts/BankReconciliation/",

  //Invite
  invite_link: "/Subscription/User/SendInviteLink",
  accept_link: "/Subscription/User/AcceptInviteLink",

  demo_whatsapp_message: "",
  demo_email_message: "",
  demo_sms_message: "",
};

export default Urls;
