import { 
  PrintMasterDto,
  PrintDetailDto,
  InvDetail2ForPrint,
  PrintResponse,
  InvMaster2ForPrint,
  InvMaster3ForPrint,
  PartyDetailsForPrint,
  CompanyDetailsForPrint,
  VehicleDetailsForPrint,
  OpticalDetailsDV,
  OpticalDetailsCL,
  OpticalDetailsADD,
  EInvoiceDetailsForPrint,
  MultiPaymentForPrint,
  PrintCustomFields
} from './use-print-type';

// ---------------------- Sub Objects ---------------------- //
export const initialInvMaster2ForPrint: InvMaster2ForPrint = {
  cardTip: 0,
  cashTip: 0,
  creditCardDetails: "",
  notes1: "",
  notes2: ""
};

export const initialInvMaster3ForPrint: InvMaster3ForPrint = {
  shipLegalName: "",
  shipTradeName: "",
  shipAddress1: "",
  shipAddress2: "",
  shipGstIn: ""
};

export const initialPartyDetailsForPrint: PartyDetailsForPrint = {
  partyName: "",
  partyDisplayName: "",
  partyCode: "",
  officePhone: "",
  workPhone: "",
  mobilePhone: "",
  contactPhone: "",
  faxNumber: "",
  partyAddress2: "",
  partyAddress3: "",
  partyAddress4: "",
  partyStreet: "",
  partyCity: "",
  partyDistrict: "",
  partyBuildingNo: "",
  partyPostalCode: "",
  partyAdditionalNo: "",
  stateCode: "",
  stateName: "",
  webURL: "",
  email: "",
  taxNumber: "",
  partyCRNumber: "",
  partyType: "",
  partyNameInArabic: "",
  partyName2: "",
  creditDays: 0,
  partyAdditionalNumber: "",
  partyBuildingNumber: "",
  partyCitySubDivision: "",
  partyCountrySubDivision: "",
  partyCountry: ""
};

export const initialCompanyDetailsForPrint: CompanyDetailsForPrint = {
  companyRegistredNameEnglish: "",
  companyRegistredNameArabic: "",
  companyTaxRegNumber: "",
  companyCRNumber: "",
  companyBuildingNo: "",
  companyStreetName: "",
  companyDistrict: "",
  companyCity: "",
  companyPostalCode: "",
  companyAdditionalNo: "",
  companyCountry: "",
  companyEmail: "",
  companyTelephone: "",
  companyMobile: ""
};

export const initialVehicleDetailsForPrint: VehicleDetailsForPrint = {
  vehicleName: "",
  vehicleNumber: "",
  vehicleModel: "",
  vehicleCapacity: "",
  vehicleManufacturer: "",
  vehicleOwner: "",
  vehicleColor: "",
  vehicleOdometer: "",
  vehicleRemarks: "",
  driver: ""
};

export const initialOpticalDetailsDV: OpticalDetailsDV = {
  dvREAXIS: 0,
  dvRECYL: 0,
  dvRESPH: 0,
  dvREVn: 0,
  dvLECYL: 0,
  dvLESPH: 0,
  dvLEAXIS: 0,
  dvLEVN: 0,
  dvRemarks: "",
  dvVisionType: ""
};

export const initialOpticalDetailsCL: OpticalDetailsCL = {
  clREAXIS: 0,
  clRECYL: 0,
  clRESPH: 0,
  clREVn: 0,
  clLECYL: 0,
  clLESPH: 0,
  clLEAXIS: 0,
  clLEVN: 0,
  clRemarks: "",
  clVisionType: ""
};

export const initialOpticalDetailsADD: OpticalDetailsADD = {
  addREAXIS: 0,
  addRECYL: 0,
  addRESPH: 0,
  addREVn: 0,
  addLECYL: 0,
  addLESPH: 0,
  addLEAXIS: 0,
  addLEVN: 0,
  addRemarks: "",
  addVisionType: ""
};

export const initialEInvoiceDetailsForPrint: EInvoiceDetailsForPrint = {
  iqr: "",
  eInvoiceQRCode: "",
  acknowledgementNumber: "",
  acknowledgementDate: null,
  irn: ""
};

export const initialMultiPaymentForPrint: MultiPaymentForPrint = {
  cardAmt: 0,
  upi: 0
};

export const initialInvDetail2ForPrint: InvDetail2ForPrint = {
  cgst: 0,
  cgstPerc: 0,
  sgst: 0,
  sgstPerc: 0,
  igst: 0,
  igstPerc: 0,
  cessAmt: 0,
  cessPerc: 0,
  additionalCess: 0,
  additionalCessPerc: 0,
  gstPerc: 0
};

export const initialPrintCustomFields: PrintCustomFields = {
  streamReader: null,
  currentLine: "",
  salesBillNumbers: "",
  salesRetBillNumbers: "",
  billAmounts: "",
  retBillAmounts: "",
  currentSettingsArray: [],
  backWardLines: 0,
  ejectLines: 0,
  linesPerPage: 0,
  minLinesPerPage: 0,
  linesBetweenPages: 0,
  width: 0,
  height: 0,
  printerName: "",
  showPrinterSelection: false,
  gapBetweenItems: 0,
  kitchenPrinterName: "",
  commonKitchenProductGroupId: 0,
  pageHeight: 0,
  pageSize: 0,
  totalBillQty: 0,
  landscape: false,
  dosPrint: false,
  sortItemList: false,
  portForm: "",
  backgroundImgPath: "",
  invTransactionMasterID: 0,
  fldName: "",
  fldText: "",
  fldLength: "",
  fldFont: "",
  fldFontSize: "",
  fldAlign: "",
  fldLeft: "",
  fldTop: "",
  fldBold: "",
  fldItalic: "",
  fldUnderLine: "",
  fldFormat: "",
  fldHideCodes: "",
  tempFname: "",
  ihSettings: "",
  phSettings: "",
  dtSettings: "",
  pfSettings: "",
  ifSettings: "",
  dtTranMaster: null,
  dtTransDetails: null,
  noOfCopies: 1,
  printInCopy: 1,
  groupNameHeadHeight: 0,
  grandTotal: 0,
  totReturnAmount: 0,
  roundAmt: 0,
  adjustmentAmount: 0,
  totDiscAmt: 0,
  fcAmount: 0,
  balancePaid: 0,
  billDiscount: 0,
  privilegeAmt: 0,
  privilegeCardID: 0,
  exchangeRate: 0,
  qrPay: 0,
  bankCard: 0,
  isInvTrans: false,
  isSalesView: false,
  isServiceTrans: false,
  isReprint: false,
  isFromSalesReceipt: false,
  lastGroupName: "",
  stateCode: "",
  stateName: "",
  bankCardName: "",
  lastGroupNameWithUnit: "",
  hasGroupHeaderPrinting: false,
  isPOSPrinting: false,
  kitchenID: 0,
  commonKitchenProductGroupID: 0,
  totalBillItemNos: 0,
  kitchenName: "",
  pageNo: 1,
  noOfPages: 1,
  totalItems: 0,
  pageTotDebit: 0,
  pageTotCredit: 0,
  pageTotAmount: 0,
  pageTotNetAmount: 0,
  totalNetValue: 0,
  totalNetAmount: 0,
  totalQty: 0,
  totalPageQty: 0,
  sumOfGross: 0,
  unitNetValue: 0,
  sumOfDisc: 0,
  sumOfTax: 0,
  sumOfNetAmt: 0,
  sumOfVAT: 0,
  sumOfTotDisc: 0,
  sumOfCST: 0,
  sumOfNetValue: 0,
  sumOfMRP: 0,
  sumOfNosQty: 0,
  sumOfMRPRate: 0,
  sumOfSchemDisc: 0,
  sumOfGrossfc: 0,
  pageTotalofGross: 0,
  pageTotalofDisc: 0,
  pageTotalofTax: 0,
  pageTotalofNetAmt: 0,
  pageTotalofSchmeDisc: 0,
  pageTotalofVAT: 0,
  pageTotalofTotDisc: 0,
  pageTotalofCST: 0,
  pageTotalofNetValue: 0,
  pageTotalofNosQty: 0,
  pageTotFree: 0,
  totalFree: 0,
  totalQtyFree: 0,
  sumOfCGST: 0,
  sumOfSGST: 0,
  sumOfIGST: 0,
  sumOfCessAmt: 0,
  sumOfAddCessAmt: 0,
  sumOfGST: 0,
  sumOfNetWeight: 0,
  serviceItems: [],
  serviceItemsAMT: [],
  zeroTaxable: 0,
  sumGST: 0,
  zeroCGSTAmt: 0,
  zeroSGSTAmt: 0,
  zeroIGSTAmt: 0,
  zeroTotal: 0,
  threeTaxable: 0,
  threeCGST: 0,
  threeSGST: 0,
  threeIGST: 0,
  threeTotal: 0,
  fiveTaxable: 0,
  fiveCGSTAmt: 0,
  fiveSGSTAmt: 0,
  fiveIGSTAmt: 0,
  fiveTotal: 0,
  twelveTaxable: 0,
  twelveCGSTAmt: 0,
  twelveSGSTAmt: 0,
  twelveIGSTAmt: 0,
  twelveTotal: 0,
  eighteenTaxable: 0,
  eighteenCGSTAmt: 0,
  eighteenSGSTAmt: 0,
  eighteenIGSTAmt: 0,
  eighteenTotal: 0,
  twentyEightTaxable: 0,
  twentyEightCGSTAmt: 0,
  twentyEightSGSTAmt: 0,
  twentyEightIGSTAmt: 0,
  twentyEightTotal: 0,
  mrpDifference: 0,
  totalCST: 0,
  mrpTotal: 0,
  totalEffectiveDiscount: 0,
  totalSavedAmt: 0,
  partyLedgerID: 0,
  productBatchID: 0,
  invQty: 0,
  openingBalance: 0,
  cashReceived: 0,
  bankAmt: 0,
  cashReturned: 0,
  stockTransferTotalSalesValue: 0,
  cashPaidOrRcvd: 0,
  loyaltyCardNo: "",
  total5PerctaxableValue: 0,
  total5PercTaxValue: 0,
  totalzeroPercentTaxableValue: 0,
  totalzeroPercentTaxValue: 0,
  totalOtherTaxableValue: 0,
  totalOtherTaxValue: 0,
  total15PerctaxableValue: 0,
  total15PercTaxValue: 0,
  drCr: "",
  jvTotalDebit: 0,
  jvTotalCredit: 0,
  gatePass: false,
  productNameGatePass: "",
  qtyGatePass: 0,
  transactionDate: "",
  transactionTime: "",
  transDate: "",
  countGate: 0,
  gt: false,
  voucherNumberGate: "",
  transactionTimeGate: "",
  totalItemsGate: 0,
  tokenBarcodeGate: "",
  currentRow: 0,
  linesPerCurrentPage: 0,
  freeString: "",
  prodName: "",
  prodDescription: "",
  qtyWithUnit: "",
  modelNoKOT: "",
  productCode: "",
  token: "",
  productUnitRemarks: "",
  productUnitRemarksOrProductName: "",
  narration: "",
  mannualBarcode: "",
  autoBarcode: "",
  transactionBarcode: "",
  billNumberBarcode: "",
  pageTotalBarcode: "",
  invoiceNumberAndPageTotalBarcode: "",
  pHeight: "",
  pWidth: "",
  nonHeightWidth: "",
  printCount: "",
  tokenBarcode: "",
  voucherNumberBarcode: "",
  billNumberPrefBarcode: "",
  oldInvTransactionID: 0,
  isIHPrinted: false,
  isPHPrinted: false,
  isPFPrinted: false,
  isDTPrinted: false,
  dtSecTop: 0,
  dtSecExtra: 0,
  pfSecTop: 0,
  ifSecTop: 0,
  stdDetSecTop: 0,
  skipLineHeight: 0,
  lastDetailsPrintTop: 0,
  currentPrintingSection: "",
  inOut: "",
  partyName: "",
  address1: "",
  address2: "",
  mobile: "",
  noOfItemsInVoucher: 0,
  deliveryAddress3: "",
  priceCategoryName: "",
  isCheque: false,
  chequeDate: "",
  chequePaytoAccountName: "",
  chequeAmount: "",
  chequeAmountInWords: "",
  chequeRemarks: "",
  kmWaiter: "",
  kmOrderNumber: "",
  kmTableNo: "",
  kmSeatNo: "",
  kmTokenNumber: "",
  kmServeType: "",
  kmKitchenRemarks: "",
  kmKitchenRemarks1: "",
  kmKitchenRemarks2: "",
  kmKitchenRemarks3: "",
  kmKitchenRemarks4: "",
  isKitchenMsg: false,
  kitchenId: 0,
  privilageCardBalance: 0
};

// ---------------------- Master Object ---------------------- //
export const initialPrintMasterDto: PrintMasterDto = {
  invTransactionMasterID: 0,
  branchID: 0,
  financialYearID: 0,
  counterID: 0,
  salesMan: 0,
  inventoryLedgerID: 0,
  ledgerID: 0,
  referalAgentID: null,
  address1: "",
  address2: "",
  address3: "",
  address4: "",
  voucherPrefix: "",
  voucherNumber: "",
  dailyVoucherNumber: "",
  transactionDate: new Date(),
  remarks: "",
  fromWarehouseID: null,
  toWarehouseID: null,
  createdUserID: 0,
  modifiedUserID: 0,
  systemDateTime: new Date(),
  voucherType: "",
  voucherForm: "",
  purchaseInvoiceNumber: "",
  purchaseInvoiceDate: null,
  quotationNumber: "",
  quotationDate: null,
  dueDate: null,
  deliveryNoteNumber: "",
  refNoSales: "",
  deliveryDate: null,
  refDateSales: null,
  despatchDocumentNumber: "",
  despatchDate: null,
  vehicelID: null,
  salesManID: null,
  deliveryManID: null,
  driverID: null,
  vatAmount: 0,
  totalVat: 0,
  vatPercentage: 0,
  totalGross: 0,
  privRedeem: 0,
  privAddAmount: 0,
  privCardID: null,
  netTotal: 0,
  totalDiscount: 0,
  sumofDiscount: 0,
  totItemDiscPlusBillDisc: 0,
  billDiscount: 0,
  adjustmentAmount: 0,
  grandTotal: 0,
  totalProfit: 0,
  roundAmount: 0,
  cashReceived: 0,
  advanceAmt: 0,
  cashReturned: 0,
  shortageAmount: 0,
  salesManIncentive: 0,
  gatePassNo: "",
  displayOrderNumber: "",
  cashAmt: 0,
  bankAmt: 0,
  creditAmt: 0,
  oldInvTransactionID: null,
  createdDate: new Date(),
  modifiedDate: new Date(),
  isActive: true,
  tokenNumber: "",
  inout: "",
  fcAmount: 0,
  customerType: "",
  taxOnDiscount: false,
  counterName: "",
  salesManCode: "",
  salesManName: "",
  costCentreName: "",
  projectName: "",
  projectAddress1: "",
  projectAddress2: "",
  projectAddress3: "",
  privCardNumber: "",
  userName: "",
  orderNumber: "",
  orderDate: null,
  srAmount: 0,
  warehouseName: "",
  fromWarehouseName: "",
  toWarehouseName: "",
  salesManEmail: "",
  salesManMobile: "",
  referenceNumber: "",
  mannualInvoiceNumber: "",
  transactionDateWithTime: new Date(),
  couponAmt: 0,
  noofItems: 0,
  tableLocation: "",
  tableNo: "",
  seatNumber: "",
  exchangeRate: 0,
  grandTotalFC: 0,
  totalDiscountFC: 0,
  priceCategoryName: "",
  master2Data: initialInvMaster2ForPrint,
  master3Data: initialInvMaster3ForPrint,
  vehicleData: initialVehicleDetailsForPrint,
  partyData: initialPartyDetailsForPrint,
  companyData: initialCompanyDetailsForPrint,
  opDVData: initialOpticalDetailsDV,
  opADDData: initialOpticalDetailsADD,
  opCLData: initialOpticalDetailsCL,
  eInvoiceData: initialEInvoiceDetailsForPrint,
  multiPaymentData: initialMultiPaymentForPrint,
  accTransactionMasterID: 0,
  departmentID: 0,
  costCentreID: 0,
  billwiseMasterID: 0,
  employeeID: 0,
  invTransactionID: 0,
  prevTransDate: "",
  bankDate: "",
  referenceDate: "",
  particulars: "",
  totalDebit: 0,
  billwiseTotalAdjAmt: 0,
  billwiseAdjAmt: 0,
  totalCredit: 0,
  totDiscount: 0,
  empIncentive: 0,
  commonNarration: "",
  formType: "",
  debitNoteTransID: 0,
  creditNoteTransID: 0,
  currencyID: 0,
  accTransDetailID: 0,
  adjustedTransDetailID: 0,
  currencyRate: 0,
  isPosted: false,
  randomKey: 0,
  onlineTrans: "",
  isEdit: false,
  chequeStatus: "",
  checkBouncedDate: "",
  drCr: "",
  isSalesView: false,
  refBranchID: 0,
  uuid: "",
  oldAccTransactionMasterID: 0,
  actionStatus: "",
  counterShiftID: 0,
  isLocked: false,
  editId: 0,
  notes: "",
  masterAccount: "",
  employeeName: "",
  employeeCode: "",
  branch: "",
  netAmount: 0,
  returnAmount: 0
};

// ---------------------- Detail Object ---------------------- //
export const initialPrintDetailDto: PrintDetailDto = {
  slNo: 1,
  invTransactionDetailID: 0,
  invTransactionMasterID: 0,
  productBatchID: 0,
  productDescription: "",
  quantity: 0,
  qtyInBaseUnit: 0,
  baseUnitUnitPrice: 0,
  taxIncludedBasePrice: 0,
  baseQty: 0,
  free: 0,
  qtyInNumbers: 0,
  unitID: 0,
  totalQty: 0,
  barcodeQty: 0,
  unitPrice: 0,
  valuationPrice: 0,
  rateWithTax: 0,
  grossValue: 0,
  discountPer1: 0,
  discountAmt1: 0,
  totalDiscount: 0,
  vatPercentage: 0,
  vat: 0,
  netValue: 0,
  taxIncludedPrice: 0,
  cstPerc: 0,
  cst: 0,
  netAmount: 0,
  costPerItem: 0,
  totalProfit: 0,
  marginPer: 0,
  marginAmt: 0,
  stdSalesPrice: 0,
  mrp: 0,
  invStatus: "",
  salesManID: 0,
  qtyIn: 0,
  qtyOut: 0,
  qtyNosIn: 0,
  qtyNosOut: 0,
  adjQty: 0,
  adjQtyNos: 0,
  modelNo: "",
  specification: "",
  color: "",
  autoBarcode: "",
  mannualBarcode: "",
  mfgDate: "",
  brandName: "",
  brandID: 0,
  brandShortName: "",
  sVatPerc: 0,
  pVatPerc: 0,
  taxCategoryName: "",
  productCode: "",
  productName: "",
  hsnCode: "",
  commodityCode: "",
  itemAliasCode: "",
  itemAlias: "",
  itemNameinSecondLanguage: "",
  arabicName: "",
  batchStdSalesPrice: 0,
  stdPurchasePrice: 0,
  batchMRP: 0,
  modelNumber: "",
  batchSpecification: "",
  upcCode: "",
  packing: "",
  partNumber: "",
  productColour: "",
  warranty: "",
  productCategoryCode: "",
  productCategoryName: "",
  unitCode: "",
  unitName: "",
  unitRemarks: "",
  groupName: "",
  serialNumber: "",
  location: "",
  salesValue: 0,
  unitSalesValue: 0,
  unitQty: 0,
  additionalExpense: 0,
  scannedBarcode: "",
  unitPriceFC: 0,
  grossFC: 0,
  netValueFC: 0,
  netAmountFC: 0,
  totalDiscountFC: 0,
  exchangeRate: 0,
  productUnitRemarks: "",
  warehouseID: 0,
  warehouse: "",
  supplierReferenceProductCode: "",
  batchNo: "",
  expiryDate: "",
  schemeDiscAmt: 0,
  schemeDiscPerc: 0,
  memo: "",
  stock: 0,
  netWeight: 0,
  netWeightUnitName: "",
  productNotes1: "",
  productNotes2: "",
  productNotes3: "",
  productNotes4: "",
  itemType: "",
  gatePass: 0,
  stockDetails: "",
  voucherNumber: "",
  dailyVoucherNumber: "",
  voucherType: "",
  branchID: 0,
  counterID: 0,
  partyName: "",
  vatAmount: 0,
  billDiscount: 0,
  grandTotal: 0,
  roundAmount: 0,
  cashReceived: 0,
  advanceAmt: 0,
  cashReturned: 0,
  salesManIncentive: 0,
  adjustmentAmount: 0,
  branch: "",
  siNo: 0,
  accTransactionDetailID: 0,
  ledgerCode: "",
  accountName: "",
  relatedLedgerCode: "",
  particulars: "",
  particularLedgerCode: "",
  ledgerID: 0,
  relatedLedgerID: 0,
  debit: 0,
  credit: 0,
  amount: 0,
  narration: "",
  discount: 0,
  incentives: 0,
  adjAmount: 0,
  bankDate: "",
  chequeNumber: "",
  checkStatus: "",
  checkBouncedDate: "",
  chequeDate: "",
  billwiseDetails: "",
  ledgerNameArabic: "",
  relatedLedgerNameArabic: "",
  costCentreName: "",
  txp_PartyName: "",
  txp_TaxNo: "",
  txp_TaxPercentage: 0,
  txp_TaxAmount: 0,
  txp_TaxableAmount: 0,
  txp_RefNo: "",
  txp_RefDate: "",
  detail2Data: initialInvDetail2ForPrint
};

// ---------------------- Full Response ---------------------- //
export const initialPrintResponse: PrintResponse = {
  master: initialPrintMasterDto,
  details: [],
  ledgerBalance: 0,
  previousLedgerBalance: 0,
  loyaltyCardBalance: 0,
  totalTaxableValue0Percent: 0,
  totalTaxableValue5Percent: 0,
  totalTaxableValue15Percent: 0,
  totalTaxValue5Percent: 0,
  totalTaxValue15Percent: 0,
  printCount: 0,
  configData: {},
  isCashInHandLedger: false,
  isLedgerUnderBank: false,
  isLedgerUnderCashOrBank: false,
  salesBillNumbers: "",
  salesBillAmounts: "",
  salesRetBillNumbers: "",
  salesRetBillAmounts: "",
  custom: initialPrintCustomFields
};



// Helper function to create a new empty detail line
export const createEmptyDetailLine = (slNo: number = 1): PrintDetailDto => ({
  ...initialPrintDetailDto,
  slNo
});


