import {
  AdjustmentsVerticalIcon,
  BanknotesIcon,
  BellAlertIcon,
  BellIcon,
  BuildingOffice2Icon,
  CheckBadgeIcon,
  PuzzlePieceIcon,
  UserIcon,
  WrenchIcon,
} from "@heroicons/react/24/outline";
import {toggleAuthorizationSettingsPopup, toggleBankPosPopup, toggleBranchPopup, toggleCommandsPopup, toggleCompanyProfilePopup, 
        toggleDayClosePopup, 
        toggleDeleteInactiveTransactionPopup, 
        toggleImportExportPopup, 
        toggleResetDataBasePopup, 
        toggleUserActionPopup} from "../../../../redux/slices/popup-reducer";

export const SettingsMenuItems = [
  // {
  //   menutitle: 'Settings',
  //   showWorkspaceMiniCard: true,
  // },
  {
    icon: (<CheckBadgeIcon className="side-menu__icon" />),
    type: 'sub',
    Name: '',
    active: false,
    selected: false,
    title: 'acc_masters',
    badge: '',
    badgetxt: '',
    class: 'badge !bg-warning/10 !text-warning !py-[0.25rem] !px-[0.45rem] !text-[0.75em] ms-2',
    columns: 2,
    children: [
      { path: `${import.meta.env.BASE_URL}settings/_/account-masters/account-group`, type: 'link', active: false, selected: false, title: 'acc_group' },
      { path: `${import.meta.env.BASE_URL}settings/_/account-masters/account-ledger`, type: 'link', active: false, selected: false, title: 'acc_ledger' },
      { path: `${import.meta.env.BASE_URL}settings/_/account-masters/currency-master`, type: 'link', active: false, selected: false, title: 'currency' },
      { path: `${import.meta.env.BASE_URL}settings/_/account-masters/cost-center`, type: 'link', active: false, selected: false, title: 'costcenter' },
      { path: `${import.meta.env.BASE_URL}settings/_/account-masters/branch-ledgers`, type: 'link', active: false, selected: false, title: 'branch_ledger' },
      { path: `${import.meta.env.BASE_URL}settings/_/account-masters/chart-of-accounts`, type: 'link', active: false, selected: false, title: 'chart_of_accounts' },
      { path: `${import.meta.env.BASE_URL}settings/_/account-masters/chart-of-accounts/cost-center`, type: 'link', active: false, selected: false, title: 'costcenter_coa' },
      { path: `${import.meta.env.BASE_URL}settings/_/account-masters/opening-balance`, type: 'link', active: false, selected: false, title: 'opening_balance' },
      { path: `${import.meta.env.BASE_URL}settings/_/account-masters/party-category`, type: 'link', active: false, selected: false, title: 'party_category' },
      { path: `${import.meta.env.BASE_URL}settings/_/account-masters/supplier-customer-master`, type: 'link', active: false, selected: false, title: 'supp_cust_master' },
      { path: `${import.meta.env.BASE_URL}settings/_/account-masters/cash-bank-master`, type: 'link', active: false, selected: false, title: 'cash_bank_master' },
      { path: `${import.meta.env.BASE_URL}settings/_/account-masters/privilege-cards`, type: 'link', active: false, selected: false, title: 'privilege_cards' },
      { path: `${import.meta.env.BASE_URL}settings/_/account-masters/customer-supplier-ledger`, type: 'link', active: false, selected: false, title: 'cust_supp_ledger' },
    ]
  },
  {
    icon: (<UserIcon className="side-menu__icon" />),
    type: 'sub',
    Name: '',
    active: false,
    selected: false,
    title: 'user-roles',
    badge: '',
    badgetxt: '',
    class: 'badge !bg-warning/10 !text-warning !py-[0.25rem] !px-[0.45rem] !text-[0.75em] ms-2',
    children: [
      { path: `${import.meta.env.BASE_URL}settings/_/user-management/users`, type: 'link', active: false, selected: false, title: 'users' },
      { path: `${import.meta.env.BASE_URL}settings/_/user-management/userstypes`, type: 'link', active: false, selected: false, title: 'usertype' },
      { path: `${import.meta.env.BASE_URL}settings/_/user-management/user-type-privileges`, type: 'link', active: false, selected: false, title: 'user_type_privilege' },
    ]
  },
  {
    icon: (<UserIcon className="side-menu__icon" />),
    type: 'sub',
    Name: '',
    active: false,
    selected: false,
    title: 'administration',
    badge: '',
    badgetxt: '',
    class: 'badge !bg-warning/10 !text-warning !py-[0.25rem] !px-[0.45rem] !text-[0.75em] ms-2',
    children: [
      { action:toggleCompanyProfilePopup, type: 'popup', active: false, selected: false, title: 'company_profile' },
      { action:toggleBranchPopup, type: 'popup', active: false, selected: false, title: 'branches' },
      { action:toggleDeleteInactiveTransactionPopup, type: 'popup', active: false, selected: false, title: 'delete_inactive_transactions' },
      { action:toggleBankPosPopup, type: 'popup', active: false, selected: false, title: 'bank_pos_settings' },
    ]
  },
  {
    icon: (<UserIcon className="side-menu__icon" />),
    type: 'sub',
    Name: '',
    active: false,
    selected: false,
    title: 'system',
    badge: '',
    badgetxt: '',
    columns: 2,
    class: 'badge !bg-warning/10 !text-warning !py-[0.25rem] !px-[0.45rem] !text-[0.75em] ms-2',
    children: [
      { path: `${import.meta.env.BASE_URL}settings/_/system/administration-settings`, type: 'link', active: false, selected: false, title: 'Administration Settings' },
      { action:toggleImportExportPopup, type: 'popup', active: false, selected: false, title: 'Export Import' },
      { action:toggleResetDataBasePopup, type: 'popup', active: false, selected: false, title: 'Reset Database' },
      { path: `${import.meta.env.BASE_URL}settings/_/system/counters`, type: 'link', active: false, selected: false, title: 'Counters' },
      { path: `${import.meta.env.BASE_URL}settings/_/system/financial-year`, type: 'link', active: false, selected: false, title: 'Financial Year' },
      { path: `${import.meta.env.BASE_URL}settings/_/system/vouchers`, type: 'link', active: false, selected: false, title: 'Vouchers' },
      { path: `${import.meta.env.BASE_URL}settings/_/system/barcode-print`, type: 'link', active: false, selected: false, title: 'Barcode Print' },
      { path: `${import.meta.env.BASE_URL}settings/_/system/headers-footers`, type: 'link', active: false, selected: false, title: 'Headers and Footers' },
      { path: `${import.meta.env.BASE_URL}settings/_/templates`, type: 'link', active: false, selected: false, title: 'Invoice Designer' },
      { action:toggleCommandsPopup, type: 'popup', active: false, selected: false, title: 'Commands' },
      { action:toggleUserActionPopup, type: 'popup', active: false, selected: false, title: 'User Action Report' },
      { path: `${import.meta.env.BASE_URL}settings/_/system/reminders`, type: 'link', active: false, selected: false, title: 'Reminders' },
      { path: `${import.meta.env.BASE_URL}settings/_/system/exchange-rates`, type: 'link', active: false, selected: false, title: 'Exchange Rates' },
      { path: `${import.meta.env.BASE_URL}settings/_/system/refresh-all-branches`, type: 'link', active: false, selected: false, title: 'Refresh All Branches' },
      {action:toggleDayClosePopup, type: 'popup', active: false, selected: false, title: 'Day Close' },
      { path: `${import.meta.env.BASE_URL}settings/_/system/advance-options`, type: 'link', active: false, selected: false, title: 'Advance Options' },
      {action:toggleAuthorizationSettingsPopup, type: 'popup', active: false, selected: false, title: 'Authorization Settings' },
    ]
  },
];