import {
  AdjustmentsVerticalIcon,
  BanknotesIcon,
  BellAlertIcon,
  BellIcon,
  BuildingOffice2Icon,
  CheckBadgeIcon,
  PuzzlePieceIcon,
  UserIcon,
  WrenchIcon,
} from "@heroicons/react/24/outline";
import {toggleBankPosPopup, toggleBranchPopup, toggleCommandsPopup, toggleCompanyProfilePopup, 
        toggleDayClosePopup, 
        toggleDeleteInactiveTransactionPopup, 
        toggleImportExportPopup, 
        toggleResetDataBasePopup, 
        toggleUserActionPopup} from "../../../../redux/slices/popup-reducer";

export const SettingsMenuItems = [
  // {
  //   menutitle: 'Settings',
  //   showWorkspaceMiniCard: true,
  // },
  {
    icon: (<CheckBadgeIcon className="side-menu__icon" />),
    type: 'sub',
    Name: '',
    active: false,
    selected: false,
    title: 'Accounts Masters',
    badge: '',
    badgetxt: '',
    class: 'badge !bg-warning/10 !text-warning !py-[0.25rem] !px-[0.45rem] !text-[0.75em] ms-2',
    columns: 2,
    children: [
      { path: `${import.meta.env.BASE_URL}settings/account-masters/account-group`, type: 'link', active: false, selected: false, title: 'Account Group' },
      { path: `${import.meta.env.BASE_URL}settings/account-masters/account-ledger`, type: 'link', active: false, selected: false, title: 'Account Ledger' },
      { path: `${import.meta.env.BASE_URL}settings/account-masters/currency-master`, type: 'link', active: false, selected: false, title: 'Currency Master' },
      { path: `${import.meta.env.BASE_URL}settings/account-masters/cost-center`, type: 'link', active: false, selected: false, title: 'Cost Center' },
      { path: `${import.meta.env.BASE_URL}settings/account-masters/branch-ledgers`, type: 'link', active: false, selected: false, title: 'Branch Ledgers' },
      { path: `${import.meta.env.BASE_URL}settings/account-masters/chart-of-accounts`, type: 'link', active: false, selected: false, title: 'Chart of Accounts' },
      { path: `${import.meta.env.BASE_URL}settings/account-masters/chart-of-accounts/cost-center`, type: 'link', active: false, selected: false, title: 'Cost Center (Chart of Accounts)' },
      { path: `${import.meta.env.BASE_URL}settings/account-masters/opening-balance`, type: 'link', active: false, selected: false, title: 'Opening Balance' },
      { path: `${import.meta.env.BASE_URL}settings/account-masters/party-category`, type: 'link', active: false, selected: false, title: 'Party Category' },
      { path: `${import.meta.env.BASE_URL}settings/account-masters/supplier-customer-master`, type: 'link', active: false, selected: false, title: 'Supplier/Customer Master' },
      { path: `${import.meta.env.BASE_URL}settings/account-masters/cash-bank-master`, type: 'link', active: false, selected: false, title: 'Cash/Bank Master' },
      { path: `${import.meta.env.BASE_URL}settings/account-masters/privilege-cards`, type: 'link', active: false, selected: false, title: 'Privilege Cards' },
      { path: `${import.meta.env.BASE_URL}settings/account-masters/customer-supplier-ledger`, type: 'link', active: false, selected: false, title: 'Customer/Supplier Ledger' },
    ]
  },
  {
    icon: (<UserIcon className="side-menu__icon" />),
    type: 'sub',
    Name: '',
    active: false,
    selected: false,
    title: 'Users & Roles',
    badge: '',
    badgetxt: '',
    class: 'badge !bg-warning/10 !text-warning !py-[0.25rem] !px-[0.45rem] !text-[0.75em] ms-2',
    children: [
      { path: `${import.meta.env.BASE_URL}settings/_/user-management/users`, type: 'link', active: false, selected: false, title: 'Users' },
      { path: `${import.meta.env.BASE_URL}settings/_/user-management/userstypes`, type: 'link', active: false, selected: false, title: 'User Types' },
      { path: `${import.meta.env.BASE_URL}settings/user-management/user-type-privileges`, type: 'link', active: false, selected: false, title: 'User Type Privileges' },
    ]
  },
  {
    icon: (<UserIcon className="side-menu__icon" />),
    type: 'sub',
    Name: '',
    active: false,
    selected: false,
    title: 'Administration',
    badge: '',
    badgetxt: '',
    class: 'badge !bg-warning/10 !text-warning !py-[0.25rem] !px-[0.45rem] !text-[0.75em] ms-2',
    children: [
      { action:toggleCompanyProfilePopup, type: 'popup', active: false, selected: false, title: 'Company Profile' },
      { action:toggleBranchPopup, type: 'popup', active: false, selected: false, title: 'Branches' },
      { action:toggleDeleteInactiveTransactionPopup, type: 'popup', active: false, selected: false, title: 'Delete Inactive Transactions' },
      { action:toggleBankPosPopup, type: 'popup', active: false, selected: false, title: 'Bank POS Settings' },
    ]
  },
  {
    icon: (<UserIcon className="side-menu__icon" />),
    type: 'sub',
    Name: '',
    active: false,
    selected: false,
    title: 'System',
    badge: '',
    badgetxt: '',
    columns: 2,
    class: 'badge !bg-warning/10 !text-warning !py-[0.25rem] !px-[0.45rem] !text-[0.75em] ms-2',
    children: [
      { path: `${import.meta.env.BASE_URL}settings/system/administration-settings`, type: 'link', active: false, selected: false, title: 'Administration Settings' },
      { action:toggleImportExportPopup, type: 'popup', active: false, selected: false, title: 'Export Import' },
      { action:toggleResetDataBasePopup, type: 'popup', active: false, selected: false, title: 'Reset Database' },
      { path: `${import.meta.env.BASE_URL}settings/system/counters`, type: 'link', active: false, selected: false, title: 'Counters' },
      { path: `${import.meta.env.BASE_URL}settings/system/financial-year`, type: 'link', active: false, selected: false, title: 'Financial Year' },
      { path: `${import.meta.env.BASE_URL}settings/system/vouchers`, type: 'link', active: false, selected: false, title: 'Vouchers' },
      { path: `${import.meta.env.BASE_URL}settings/system/barcode-print`, type: 'link', active: false, selected: false, title: 'Barcode Print' },
      { path: `${import.meta.env.BASE_URL}settings/system/headers-footers`, type: 'link', active: false, selected: false, title: 'Headers and Footers' },
      { path: `${import.meta.env.BASE_URL}settings/templates`, type: 'link', active: false, selected: false, title: 'Invoice Designer' },
      { action:toggleCommandsPopup, type: 'popup', active: false, selected: false, title: 'Commands' },
      { action:toggleUserActionPopup, type: 'popup', active: false, selected: false, title: 'User Action Report' },
      { path: `${import.meta.env.BASE_URL}settings/system/reminders`, type: 'link', active: false, selected: false, title: 'Reminders' },
      { path: `${import.meta.env.BASE_URL}settings/system/exchange-rates`, type: 'link', active: false, selected: false, title: 'Exchange Rates' },
      { path: `${import.meta.env.BASE_URL}settings/system/refresh-all-branches`, type: 'link', active: false, selected: false, title: 'Refresh All Branches' },
      {action:toggleDayClosePopup, type: 'popup', active: false, selected: false, title: 'Day Close' },
      { path: `${import.meta.env.BASE_URL}settings/system/advance-options`, type: 'link', active: false, selected: false, title: 'Advance Options' },
    ]
  },
];