export const initialPrivilegeCard = {
  data: {
    privilegeCardID: 0,
    branchID: 0,
    cardNumber: "",
    cardHolderName: "",
    address1: "",
    address2: "",
    phone: "",
    mobile: "",
    email: "",
    dob: "",
    changeID: 0,
    cardType: "",
    priceCategoryID: 0,
    expiryDate: "",
    activateDate: "",
    createdUserID: 0,
    opBalance: 0
  },
  validations: {
    privilegeCardID: "",
    branchID: "",
    cardNumber: "",
    cardHolderName: "",
    address1: "",
    address2: "",
    phone: "",
    mobile: "",
    email: "",
    dob: "",
    changeID: "",
    cardType: "",
    priceCategoryID: "",
    expiryDate: "",
    activateDate: "",
    createdUserID: "",
    opBalance: ""
  },
};

export interface PrivilegeCardData {
  privilegeCardID: number,
  branchID: number,
  cardNumber: string,
  cardHolderName: string,
  address1: string,
  address2: string,
  phone: string,
  mobile: string,
  email: string,
  dob: string,
  changeID: number,
  cardType: string,
  priceCategoryID: number,
  expiryDate: string,
  activateDate: string,
  createdUserID: number,
  opBalance: number
}
