
import { Option, OptionGroup } from "../../components/ERPComponents/erp-grouped-combo";
import { CompanyDetails, initialCompanyDetails, BranchDetails, initialBranchDetails, HeaderFooter, initialHeaderFooter } from "../../redux/slices/user-session/reducer";
import { initialPrintCustomFields, PrintCustomFields } from "../../utilities/use-common-values";
import { modelToListFromObject } from "../../utilities/Utils";
import { initialProductData, initialTransactionDetailData, TransactionMasterInitialData } from "../inventory/transactions/purchase/transaction-type-data";
import { BarcodeLabel, TransactionDetail, TransactionMaster } from "../inventory/transactions/purchase/transaction-types";

export const fields = [
   "org_name",
   "org_branch",
   "invMaster_grandTotal",
   "accMaster_invDetails",
   "org_details",
   "branch_Details",
   "custom",
    "[Footer1]",
    "[Footer10]",
    "[Footer2]",
    "[Footer3]",
    "[Footer4]",
    "[Footer5]",
    "[Footer6]",
    "[Footer7]",
    "[Footer8]",
    "[Footer9]",
    "[Header1]",
    "[Header10]",
    "[Header2]",
    "[Header3]",
    "[Header4]",
    "[Header5]",
    "[Header6]",
    "[Header7]",
    "[Header8]",
    "[Header9]",
    "AliasName",
    "ArabicName",
    "AutoBarcode",
    "AutoBarcodeText",
    "BarCode",
    "BarCodeText",
    "Batch",
    "BatchNo",
    "Cost",
    "ExpDate",
    "ExpDays",
    "ExpiryDate",
    "ExpiryDescription",
    "GroupName",
    "MBarcode",
    "MBarcodeBarcode",
    "MBarcodeBarCode2",
    "MfdDate",
    "MfgDate",
    "MRP",
    "MRPCode",
    "MRPPerUnit",
    "MSP",
    "MSPCode",
    "netWt",
    "Nutrient01",
    "Nutrient02",
    "Nutrient03",
    "Nutrient04",
    "Nutrient05",
    "Nutrient06",
    "Nutrient07",
    "Nutrient08",
    "Nutrient09",
    "Nutrient10",
    "PackingDate",
    "PackingQty2",
    "PackingQty3",
    "PartyCode",
    "PCodeBarCode",
    "PrintDate",
    "PrintTime",
    "ProductCategoryName",
    "ProductCode",
    "ProductDescription",
    "ProductName",
    "ProductName2",
    "ProductName3",
    "PurchaseCostCode",
    "PurchasePriceCode",
    "Qty",
    "salesPrice",
    "SalesPrice2",
    "SalesPrice3",
    "SalesPriceCode",
    "SalesPricePerUnit",
    "SalesPriceWithVAT",
    "SINo",
    "SINo/Qty",
    "Size",
    "Specification",
    "TextOnly",
    "TransDate",
    "Unit",
    "Unit2AutoBarcode",
    "Unit2Barcode",
    "Unit2BarcodeBarCode",
    "Unit3AutoBarcode",
    "Unit3Barcode",
    "Unit3BarcodeBarCode",
    "VAT%",
    "VocuherNo",
  ];

export const AccountMasterFields = [
    "accTransactionMasterID",
    "departmentID",
    "costCentreID",
    "billwiseMasterID",
    "employeeID",
    "invTransactionID",
    "transactionDate",
    "prevTransDate",
    "bankDate",
    "voucherPrefix",
    "voucherNumber",
    "referenceNumber",
    "referenceDate",
    "dueDate",
    "particulars",
    "totalDebit",
    "billwiseTotalAdjAmt",
    "billwiseAdjAmt",
    "totalCredit",
    "totDiscount",
    "empIncentive",
    "commonNarration",
    "remarks",
    "voucherType",
    "formType",
    "debitNoteTransID",
    "creditNoteTransID",
    "currencyID",
    "accTransactionDetailID",
    "adjustedTransDetailID",
    "currencyRate",
    "isPosted",
    "randomKey",
    "onlineTrans",
    "isEdit",
    "checkStatus",
    "checkBouncedDate",
    "drCr",
    "isSalesView",
    "branchID",
    "counterID",
    "refBranchID",
    "uuid",
 ];

 export const AccountMasterDetails = [
    "accTransactionMasterID",
    "accTransactionDetailID",
    "ledgerID",
    "relatedLedgerID",
    "amount",
    "discount",
    "debit",
    "credit",
    "randomKey",
    "incentives",
    "projectSiteID",
    "narration",
    "currencyID",
    "exchangeRate",
    "adjAmount",
    "bankDate",
    "chequeNumber",
    "particularsLedgerID",
    "isDr",
    "isDisplay",
    "voucherType",
    "checkStatus",
    "checkBouncedDate",
    "billwiseDetails",
    "branchID",
    "costCentreID",
    "projectID",
    "bankName",
    "nameOnCheque",
    "firstCreditLedgerid",
    "firstDebitLedgerID",
    "taxAmount",
 ];
  
        
const generalFields = [
  "org_name",
  "org_branch",
  "invMaster_grandTotal",
  "accMaster_invDetails",
  "org_details",
  "branch_Details",
  "custom",
];

const footerFields = [
  "Footer1","Footer10","Footer2","Footer3","Footer4",
  "Footer5","Footer6","Footer7","Footer8","Footer9",
];

const headerFields = [
  "Header1","Header10","Header2","Header3","Header4",
  "Header5","Header6","Header7","Header8","Header9",
];


// Array of all fields with their labels id's are BarcodeLabel keys

interface fdf  {
  fdd: number
}
export const inventoryFields: OptionGroup[] = [
  { groupName: 'Custom', options: modelToListFromObject<PrintCustomFields>(initialPrintCustomFields,"custom___") },
  { groupName: 'InvMaster', options: modelToListFromObject<TransactionMaster>(TransactionMasterInitialData,"master___") },
  { groupName: 'InvDetails',  options: modelToListFromObject<TransactionDetail>(initialTransactionDetailData,"details___") },
  { groupName: 'Organization',  options: modelToListFromObject<CompanyDetails>(initialCompanyDetails,"org___") },
  { groupName: 'Branch',  options: modelToListFromObject<BranchDetails>(initialBranchDetails,"branch___") },
  { groupName: 'HeaderFooter',  options: modelToListFromObject<HeaderFooter>(initialHeaderFooter,"headerFooter___") },
];
export const accountsFields: OptionGroup[] = [
  { groupName: 'Custom', options: modelToListFromObject<PrintCustomFields>(initialPrintCustomFields,"custom___") },
  { groupName: 'AccMaster',  options: modelToListFromObject<TransactionMaster>(TransactionMasterInitialData,"master___") },
  { groupName: 'AccDetails',  options: modelToListFromObject<TransactionMaster>(TransactionMasterInitialData,"details___") },
  { groupName: 'Organization',  options: modelToListFromObject<CompanyDetails>(initialCompanyDetails,"org___") },
  { groupName: 'Branch',  options: modelToListFromObject<BranchDetails>(initialBranchDetails,"branch___") },
  { groupName: 'HeaderFooter',  options: modelToListFromObject<HeaderFooter>(initialHeaderFooter,"headerFooter___") },
];
export const barCodeField: OptionGroup[] = [
  {groupName: "BarCodeField",options:modelToListFromObject<BarcodeLabel>(initialProductData,"barcode___")}
]
export const bindingDemoData = {
  org_name: "Acme Corporation Pvt Ltd",
  org_branch: "Bangalore Branch",
  org_details: {
    address: "123 MG Road, Bangalore, Karnataka, India",
    contact: "+91-9876543210",
    email: "info@acmecorp.com",
    gstNumber: "29ABCDE1234F1Z5",
  },
  branch_Details: {
    branchCode: "BLR001",
    manager: "Ravi Kumar",
    phone: "+91-9876543210",
    email: "blrbranch@acmecorp.com",
  },
  invMaster_grandTotal: "₹ 1,25,000.00",
  accMaster_invDetails: [
    {
      itemName: "Steel Pipes",
      quantity: 100,
      unitPrice: 500,
      total: 50000,
    },
    {
      itemName: "Valves",
      quantity: 50,
      unitPrice: 1000,
      total: 50000,
    },
    {
      itemName: "Fittings",
      quantity: 25,
      unitPrice: 1000,
      total: 25000,
    },
  ],
  custom: "This is a custom note or dynamic field.",

  // Footer and header placeholders
  "[Footer1]": "Thank you for your business!",
  "[Footer2]": "Payment terms: 30 days",
  "[Footer3]": "Authorized Signatory",
  "[Footer4]": "Acme Corporation Pvt Ltd",
  "[Footer5]": "Visit us: www.acmecorp.com",
  "[Footer6]": "Customer care: +91-1234567890",
  "[Footer7]": "GST inclusive",
  "[Footer8]": "No returns accepted after 15 days",
  "[Footer9]": "Generated by ERP System",
  "[Footer10]": "This is a system-generated document.",

  "[Header1]": "Tax Invoice",
  "[Header2]": "Acme Corporation Pvt Ltd",
  "[Header3]": "Invoice Date: 04-Jul-2025",
  "[Header4]": "Invoice No: INV-2025-00123",
  "[Header5]": "Branch: Bangalore",
  "[Header6]": "Customer: ABC Industries",
  "[Header7]": "Dispatch through: Courier",
  "[Header8]": "Delivery address: Mumbai",
  "[Header9]": "Due Date: 03-Aug-2025",
  "[Header10]": "Page 1 of 1",
};
