
import { Option, OptionGroup } from "../../components/ERPComponents/erp-grouped-combo";
import { CompanyDetails, initialCompanyDetails, BranchDetails, initialBranchDetails, HeaderFooter, initialHeaderFooter } from "../../redux/slices/user-session/reducer";
import { modelToListFromObject } from "../../utilities/Utils";
import { initialProductData, initialTransactionDetailData, TransactionMasterInitialData } from "../inventory/transactions/purchase/transaction-type-data";
import { BarcodeLabel, TransactionDetail, TransactionMaster } from "../inventory/transactions/purchase/transaction-types";
import { PrintCustomFields } from "../use-print-type";
import { initialPrintCustomFields } from "../use-print-type-data";




interface fdf  {
  fdd: number
}
export const inventoryFields: OptionGroup[] = [
  { groupName: 'Custom', options: modelToListFromObject<PrintCustomFields>(initialPrintCustomFields,"custom___") },
  { groupName: 'Master', options: modelToListFromObject<TransactionMaster>(TransactionMasterInitialData,"master___") },
  { groupName: 'Details',  options: modelToListFromObject<TransactionDetail>(initialTransactionDetailData,"details___") },
  { groupName: 'Organization',  options: modelToListFromObject<CompanyDetails>(initialCompanyDetails,"org___") },
  // { groupName: 'Branch',  options: modelToListFromObject<BranchDetails>(initialBranchDetails,"branch___") },
  { groupName: 'HeaderFooter',  options: modelToListFromObject<HeaderFooter>(initialHeaderFooter,"headerFooter___") },
];
export const accountsFields: OptionGroup[] = [
  { groupName: 'Custom', options: modelToListFromObject<PrintCustomFields>(initialPrintCustomFields,"custom___") },
  { groupName: 'Master',  options: modelToListFromObject<TransactionMaster>(TransactionMasterInitialData,"master___") },
  { groupName: 'Details',  options: modelToListFromObject<TransactionMaster>(TransactionMasterInitialData,"details___") },
  { groupName: 'Organization',  options: modelToListFromObject<CompanyDetails>(initialCompanyDetails,"org___") },
  // { groupName: 'Branch',  options: modelToListFromObject<BranchDetails>(initialBranchDetails,"branch___") },
  { groupName: 'HeaderFooter',  options: modelToListFromObject<HeaderFooter>(initialHeaderFooter,"headerFooter___") },
];
export const barCodeField: OptionGroup[] = [
  {groupName: "BarCodeField",options:modelToListFromObject<BarcodeLabel>(initialProductData,"barcode___")}
]
export const imgField: OptionGroup[] = [
 { groupName: 'Organization',  options: modelToListFromObject<CompanyDetails>(initialCompanyDetails,"org___") },
]
export const qrCodeField: OptionGroup[] = [
  { groupName: 'Master', options: modelToListFromObject<TransactionMaster>(TransactionMasterInitialData,"master___") },
]

export const bindingDemoData = {
  org_name: "Acme Corporation Pvt Ltd",
  org_branch: "Bangalore Branch",
  org_details: {
    address: "123 MG Road, Bangalore, Karnataka, India",
    contact: "+91-9876543210",
    email: "info@acmecorp.com",
    gstNumber: "29ABCDE1234F1Z5",
  },
  branch_Details: {
    branchCode: "BLR001",
    manager: "Ravi Kumar",
    phone: "+91-9876543210",
    email: "blrbranch@acmecorp.com",
  },
  invMaster_grandTotal: "₹ 1,25,000.00",
  accMaster_invDetails: [
    {
      itemName: "Steel Pipes",
      quantity: 100,
      unitPrice: 500,
      total: 50000,
    },
    {
      itemName: "Valves",
      quantity: 50,
      unitPrice: 1000,
      total: 50000,
    },
    {
      itemName: "Fittings",
      quantity: 25,
      unitPrice: 1000,
      total: 25000,
    },
  ],
  custom: "This is a custom note or dynamic field.",

  // Footer and header placeholders
  "[Footer1]": "Thank you for your business!",
  "[Footer2]": "Payment terms: 30 days",
  "[Footer3]": "Authorized Signatory",
  "[Footer4]": "Acme Corporation Pvt Ltd",
  "[Footer5]": "Visit us: www.acmecorp.com",
  "[Footer6]": "Customer care: +91-1234567890",
  "[Footer7]": "GST inclusive",
  "[Footer8]": "No returns accepted after 15 days",
  "[Footer9]": "Generated by ERP System",
  "[Footer10]": "This is a system-generated document.",

  "[Header1]": "Tax Invoice",
  "[Header2]": "Acme Corporation Pvt Ltd",
  "[Header3]": "Invoice Date: 04-Jul-2025",
  "[Header4]": "Invoice No: INV-2025-00123",
  "[Header5]": "Branch: Bangalore",
  "[Header6]": "Customer: ABC Industries",
  "[Header7]": "Dispatch through: Courier",
  "[Header8]": "Delivery address: Mumbai",
  "[Header9]": "Due Date: 03-Aug-2025",
  "[Header10]": "Page 1 of 1",
};
