import { DeafultTemplateProps } from "./billTemplates";

const DefaultSITemplates: DeafultTemplateProps[] = [
  {
    content: {
      /* ################  Standard Template  ################ */
      totalState: {
        showTotalSection: true,
        showSubTotalLabel: true,
        showDicount: true,
        showTax: true,
        showQuantity: true,
        showPaymentDetail: true,
        showAmoutInWords: true,
        subTotalLabel: "Sub Total",
        shippingLabel: "Shipping",
      },
      propertiesState: {
        bg_color: "#ffffff",
        font_family: "Poppins",
        font_size: 12,
        font_color: "#000000",
        font_weight: 400,

        label_font_size: 12,
        label_font_color: "#000000",
        label_font_weight: 400,
        pageSize: "A4",
        height: 500,
        width: 500,
        padding: {
          top: 0,
          bottom: 0,
          left: 0,
          right: 0,
        },
        templateName: "Standard Template (INV)",
        template_type: "standard",
        template_kind: "standard",
      },
      headerState: {
        showLogo: false,
        logo: "",
        logoSize: 50,
        showOrgName: true,
        showOrgAddress: true,
        showDocTitle: true,
        docTitle: "",
        showBalanceDue: false,
        hasPhoneField: false,
        phoneLabel: "",
        hasfaxField: false,
        faxLabel: "",
        hasEmailField: false,
        emailLabel: "",
        bgColor: "#FFFFFF",
        isFirstOnly: false,
        bg_image_header_position: "center",
        headerHeight: 50,
        showHeader: true,
        docTitleFontSize: 16,
        docTitleFontColor: "#000000",
        OrganizationFontSize: 12,
        OrganizationFontColor: "#000000",
        show_balance_due: false,
        showStatusStamp: false,
        showReceivedFrom: false,
        showVender: false,
        venderNameFontSize: 11,
        venderNameFontColor: "#000000",
        receivedFromLabel: "",
        customerNameFontSize: 12,
        customerNameFontColor: "#000000",
        hasBillTo: false,
        billTo: "",
        hasShipTo: false,
        shipTo: "",
        orgNameFontSize: 12,
        orgNameFontColor: "#000000",
        showNumberField: false,
        numberField: "",
        showReasonField: false,
        reasonLabel: "",
        showAccountField: false,
        accountLabel: "",
        showAdjTypeField: false,
        adjTypeLabel: "",
        showCreateUserField: false,
        createUserLabel: "",
        showBranchField: false,
        branchLabel: "",
        showNotesLabel: false,
        notesLabel: "",
        showAmount: false,
        amountLabel: "",
        showDateField: false,
        dateField: "",
        showTerms: false,
        terms: "",
        showDueDate: false,
        due_date: "",
        showReference: false,
        reference: "",
        showSalesPerson: false,
        salesPerson: "",
        showProject: false,
        project: "",
        showEWayBill: false,
        eWayBill: "",
        showPlaceOfSupply: false,
        placeOfSupply: "",
        showSubject: false,
        subject: "",
        showTransactionType: false,
        transactionType: "",
        showSupplyDate: false,
        supplyDate: "",
        showShipmentDate: false,
        shipmentDateLabel: "",
        showAssociatedInvNo: false,
        showAssociatedInvDate: false,
        recieptInfo: {
          showReceiptTable: false,
          showReceiptNumber: false,
          receiptNumberLabel: "",
          showReceiptDate: false,
          receiptDateLabel: "",
          showReceiptReference: false,
          receiptReferenceLabel: "",
          showReceiptMode: false,
          receiptModeLabel: "",
          showReceiptAmount: false,
          receiptAmountLabel: "",
          amtReceivedLabel: "",
          currencySymbolPosition: "before",
          amtReceivedFontSize: 12,
          amtReceivedFontColor: "#000000",
          amtReceivedBgColor: "#FFFFFF",
        },
        accountSummary: {
          showAccountSummary: false,
          accountSummaryLabel: "",
          showOpeningBalance: false,
          openingBalanceLabel: "",
          showInvoicedAmount: false,
          invoicedAmountLabel: "",
          showAmountPaid: false,
          amountPaidLabel: "",
          showBalanceDue: false,
          balanceDueLabel: "",
        },
        customElements: {
          height: 0, elements: [], thumbImage: ""
        },
      },
      footerState: {
        notesLabel: "Notes",
        noteFontSize: 12,
        customElements: {
          height: 0, elements: [], thumbImage: ""
        },
      },
     

    },
    is_default: true,
    is_primary: true,
    voucher_type: "sales_invoice",
  },
  {
    content: {
      /* ################  Retail- Standard Template  ################ */

      totalState: {
        balanceFontSize: 8,
        shippingLabel: "Shipping",
        showAmoutInWords: true,
        showDicount: false,
        showPaymentDetail: true,
        showQuantity: true,
        showSubTotalLabel: true,
        showTax: true,
        showTotalSection: true,
        subTotalLabel: "Sub Total",
        totalFontSize: 8,
      },
      propertiesState: {
        bg_color: "#ffffff",
        font_family: "Poppins",
        font_color: "#000000",
        font_size: 8,
        font_weight: 400,
        label_font_color: "#000000",
        label_font_size: 8,
        label_font_weight: 600,
        pageSize: "3Inch",
        padding: {
          top: 0,
          bottom: 0,
          left: 0,
          right: 0,
        },
        templateName: "Retail Standard",
        template_kind: "standard",
        template_type: "standard",
      },
      headerState: {
        showLogo: false,
        logo: "",
        logoSize: 50,
        showOrgName: true,
        showOrgAddress: true,
        showDocTitle: true,
        docTitle: "",
        showBalanceDue: false,
        hasPhoneField: false,
        phoneLabel: "",
        hasfaxField: false,
        faxLabel: "",
        hasEmailField: false,
        emailLabel: "",
        bgColor: "#FFFFFF",
        isFirstOnly: false,
        bg_image_header_position: "center",
        headerHeight: 50,
        showHeader: true,
        docTitleFontSize: 16,
        docTitleFontColor: "#000000",
        OrganizationFontSize: 12,
        OrganizationFontColor: "#000000",
        show_balance_due: false,
        showStatusStamp: false,
        showReceivedFrom: false,
        showVender: false,
        venderNameFontSize: 11,
        venderNameFontColor: "#000000",
        receivedFromLabel: "",
        customerNameFontSize: 12,
        customerNameFontColor: "#000000",
        hasBillTo: false,
        billTo: "",
        hasShipTo: false,
        shipTo: "",
        orgNameFontSize: 12,
        orgNameFontColor: "#000000",
        showNumberField: false,
        numberField: "",
        showReasonField: false,
        reasonLabel: "",
        showAccountField: false,
        accountLabel: "",
        showAdjTypeField: false,
        adjTypeLabel: "",
        showCreateUserField: false,
        createUserLabel: "",
        showBranchField: false,
        branchLabel: "",
        showNotesLabel: false,
        notesLabel: "",
        showAmount: false,
        amountLabel: "",
        showDateField: false,
        dateField: "",
        showTerms: false,
        terms: "",
        showDueDate: false,
        due_date: "",
        showReference: false,
        reference: "",
        showSalesPerson: false,
        salesPerson: "",
        showProject: false,
        project: "",
        showEWayBill: false,
        eWayBill: "",
        showPlaceOfSupply: false,
        placeOfSupply: "",
        showSubject: false,
        subject: "",
        showTransactionType: false,
        transactionType: "",
        showSupplyDate: false,
        supplyDate: "",
        showShipmentDate: false,
        shipmentDateLabel: "",
        showAssociatedInvNo: false,
        showAssociatedInvDate: false,
        recieptInfo: {
          showReceiptTable: false,
          showReceiptNumber: false,
          receiptNumberLabel: "",
          showReceiptDate: false,
          receiptDateLabel: "",
          showReceiptReference: false,
          receiptReferenceLabel: "",
          showReceiptMode: false,
          receiptModeLabel: "",
          showReceiptAmount: false,
          receiptAmountLabel: "",
          amtReceivedLabel: "",
          currencySymbolPosition: "before",
          amtReceivedFontSize: 12,
          amtReceivedFontColor: "#000000",
          amtReceivedBgColor: "#FFFFFF",
        },
        accountSummary: {
          showAccountSummary: false,
          accountSummaryLabel: "",
          showOpeningBalance: false,
          openingBalanceLabel: "",
          showInvoicedAmount: false,
          invoicedAmountLabel: "",
          showAmountPaid: false,
          amountPaidLabel: "",
          showBalanceDue: false,
          balanceDueLabel: "",
        },
        customElements: {
          height: 0, elements: [], thumbImage: ""
        },

      },
      footerState: {
        notesLabel: "Notes",
        noteFontSize: 12,
      },

    },
    is_default: false,
    is_primary: true,
    voucher_type: "sales_invoice",
  },
];

export default DefaultSITemplates;
