import { DeafultTemplateProps } from "./billTemplates";

const DefaultSITemplates: DeafultTemplateProps[] = [
  {
    content: {
      /* ################  Standard Template  ################ */
      adviceTableState:{
    
        showLineItemNumber: true,
        lineItemNumberLabel: "Invoice Number",
        lineItemNumberWidth: "",

        showDate: true,
        DateLabel: "Date",
        DateWidth: "",
      
        // Amount Fields
        showAmount: true,
        AmountLabel: "Amount",
        AmountWidth: "",
      
        // Due Amount Fields
        showDueAmount: true,
        DueAmountLabel: "Due Amount",
        DueAmountWidth: "",
      
        // Payment Fields
        showPayment: true,
        PaymentLabel: "Payment",
        PaymentWidth: "",
      
        // Balance Fields
        showBalance: true,
        BalanceLabel: "Balance",
        BalanceWidth: "",
      
        // Paid Statement Fields
        showPaidStatement: true,
        PaidStatementLabel: "Full Paid",
        PaidStatementWidth: "",
      },
      accTableState:{
        showLineItemNumber: true,
        lineItemNumberLabel: "SiNo",
        lineItemNumberWidth: "10%",
  
        showLedgerCode: true,
        ledgerCodeLabel: "Ledger code",
        ledgerCodeWidth: "",
  
        showLedger: true,
        ledgerLabel: "Ledger",
        ledgerWidth: "",
  
        showAmount: true,
        amountLabel: "Amount",
        amountWidth: "",
  
        showNarration: false,
        narrationLabel: "Narration",
        narrationWidth: "",
  
        showBillwiseDetails: false,
        billwiseDetailsLabel: "Bill wise details",
        billwiseDetailsWidth: "",
  
        showDiscount: true,
        discountLabel: "Discount",
        discountWidth: "",
  
        showCostCenter: false,
        costCenterLabel: "Cost Center",
        costCenterWidth: "",
  
        showAmountFc: false,
        amountFcLabel: "AmountFc",
        amountFcWidth: "",
  
        showBankCharge: true,
        bankChargeLabel: "BankCharge",
        bankChargeWidth: "",
      },
      totalState: {
        showTotalSection: true,
        showSubTotalLabel: true,
        showDicount: true,
        showTax: true,
        showQuantity: true,
        showPaymentDetail: true,
        showAmoutInWords: true,
        subTotalLabel: "Sub Total",
        shippingLabel: "Shipping",
      },
      propertiesState: {
        bg_color: "#ffffff",
        font_family: "Poppins",
        font_size: 12,
        font_color: "#000000",
        font_weight: 400,

        label_font_size: 12,
        label_font_color: "#000000",
        label_font_weight: 400,
        pageSize: "A4",
        height:500,
        width:500,
        padding: {
          top: 0,
          bottom: 0,
          left: 0,
          right: 0,
        },
        templateName: "Standard Template (INV)",
        template_type: "standard",
        template_kind: "standard",
      },
         headerState: {
      showLogo: false,
      logo: "",
      logoSize: 50,
      showOrgName: true,
      showOrgAddress: true,
      showDocTitle: true,
      docTitle: "",
      showBalanceDue: false,
      hasPhoneField: false,
      phoneLabel: "",
      hasfaxField: false,
      faxLabel: "",
      hasEmailField: false,
      emailLabel: "",
      bgColor: "#FFFFFF",
      isFirstOnly: false,
      bg_image_header_position: "center",
      headerHeight: 50,
      showHeader: true,
      docTitleFontSize: 16,
      docTitleFontColor: "#000000",
      OrganizationFontSize: 12,
      OrganizationFontColor: "#000000",
      show_balance_due: false,
      showStatusStamp: false,
      showReceivedFrom: false,
      showVender: false,
      venderNameFontSize: 11,
      venderNameFontColor: "#000000",
      receivedFromLabel: "",
      customerNameFontSize: 12,
      customerNameFontColor: "#000000",
      hasBillTo: false,
      billTo: "",
      hasShipTo: false,
      shipTo: "",
      orgNameFontSize: 12,
      orgNameFontColor: "#000000",
      showNumberField: false,
      numberField: "",
      showReasonField: false,
      reasonLabel: "",
      showAccountField: false,
      accountLabel: "",
      showAdjTypeField: false,
      adjTypeLabel: "",
      showCreateUserField: false,
      createUserLabel: "",
      showBranchField: false,
      branchLabel: "",
      showNotesLabel: false,
      notesLabel: "",
      showAmount: false,
      amountLabel: "",
      showDateField: false,
      dateField: "",
      showTerms: false,
      terms: "",
      showDueDate: false,
      due_date: "",
      showReference: false,
      reference: "",
      showSalesPerson: false,
      salesPerson: "",
      showProject: false,
      project: "",
      showEWayBill: false,
      eWayBill: "",
      showPlaceOfSupply: false,
      placeOfSupply: "",
      showSubject: false,
      subject: "",
      showTransactionType: false,
      transactionType: "",
      showSupplyDate: false,
      supplyDate: "",
      showShipmentDate: false,
      shipmentDateLabel: "",
      showAssociatedInvNo: false,
      showAssociatedInvDate: false,
      recieptInfo: {
        showReceiptTable: false,
        showReceiptNumber: false,
        receiptNumberLabel: "",
        showReceiptDate: false,
        receiptDateLabel: "",
        showReceiptReference: false,
        receiptReferenceLabel: "",
        showReceiptMode: false,
        receiptModeLabel: "",
        showReceiptAmount: false,
        receiptAmountLabel: "",
        amtReceivedLabel: "",
        currencySymbolPosition: "before",
        amtReceivedFontSize: 12,
        amtReceivedFontColor: "#000000",
        amtReceivedBgColor: "#FFFFFF",
      },
      accountSummary: {
        showAccountSummary: false,
        accountSummaryLabel: "",
        showOpeningBalance: false,
        openingBalanceLabel: "",
        showInvoicedAmount: false,
        invoicedAmountLabel: "",
        showAmountPaid: false,
        amountPaidLabel: "",
        showBalanceDue: false,
        balanceDueLabel: "",
      },
      customTop: {
      height: 0,customElements: [],
     },
      customBottom: {
      height: 0,customElements: [],
     },
    },
      footerState: {
        notesLabel: "Notes",
        noteFontSize: 12,
      },
      itemTableState: {
        amountLabel: "Amount",
        amountWidth: "10%",
        discountLabel: "Discount",
        discountWidth: "10%",
        discriptionLabel: "Description",
        headerFontColor: "#ffffff",
        headerFontSize: 11,
        hsnSacLabel: "HSN/SAC",
        hsnSacWidth: "10%",
        itemRowBgColor: "#ffffff",
        itemRowFontSize: 12,
        lineItemLabel: "Item",
        lineItemNumberLabel: "S.No.",
        lineItemNumberWidth: "10%",
        lineItemWidth: "30%",
        quantityLabel: "Qty",
        quantityWidth: "10%",
        rateLabel: "Rate",
        rateWidth: "10%",
        showAmount: true,
        showDiscount: true,
        showDiscription: true,
        showHsnSac: true,
        showLineItem: true,
        showLineItemNumber: true,
        showQuantity: true,
        showRate: true,
        showTableRowBorder: true,
        showTableHeaderBg: true,
        showTax: true,
        tableRowBorderColor: "#a3a3a3",
        tableHeaderBgColor: "#3b3b3b",
        taxLabel: "Tax",
        taxWidth: "10%",
      },
   
    },
    is_default: true,
    is_primary: true,
    voucher_type: "sales_invoice",
  },
  {
    content: {
      /* ################  Retail- Standard Template  ################ */
      adviceTableState:{
    
        showLineItemNumber: true,
        lineItemNumberLabel: "Invoice Number",
        lineItemNumberWidth: "",

        showDate: true,
        DateLabel: "Date",
        DateWidth: "",
      
        // Amount Fields
        showAmount: true,
        AmountLabel: "Amount",
        AmountWidth: "",
      
        // Due Amount Fields
        showDueAmount: true,
        DueAmountLabel: "Due Amount",
        DueAmountWidth: "",
      
        // Payment Fields
        showPayment: true,
        PaymentLabel: "Payment",
        PaymentWidth: "",
      
        // Balance Fields
        showBalance: true,
        BalanceLabel: "Balance",
        BalanceWidth: "",
      
        // Paid Statement Fields
        showPaidStatement: true,
        PaidStatementLabel: "Full Paid",
        PaidStatementWidth: "",
      },
      accTableState:{
        showLineItemNumber: true,
        lineItemNumberLabel: "SiNo",
        lineItemNumberWidth: "10%",
  
        showLedgerCode: true,
        ledgerCodeLabel: "Ledger code",
        ledgerCodeWidth: "",
  
        showLedger: true,
        ledgerLabel: "Ledger",
        ledgerWidth: "",
  
        showAmount: true,
        amountLabel: "Amount",
        amountWidth: "",
  
        showNarration: false,
        narrationLabel: "Narration",
        narrationWidth: "",
  
        showBillwiseDetails: false,
        billwiseDetailsLabel: "Bill wise details",
        billwiseDetailsWidth: "",
  
        showDiscount: true,
        discountLabel: "Discount",
        discountWidth: "",
  
        showCostCenter: false,
        costCenterLabel: "Cost Center",
        costCenterWidth: "",
  
        showAmountFc: false,
        amountFcLabel: "AmountFc",
        amountFcWidth: "",
  
        showBankCharge: true,
        bankChargeLabel: "BankCharge",
        bankChargeWidth: "",
      },
      totalState: {
        balanceFontSize: 8,
        shippingLabel: "Shipping",
        showAmoutInWords: true,
        showDicount: false,
        showPaymentDetail: true,
        showQuantity: true,
        showSubTotalLabel: true,
        showTax: true,
        showTotalSection: true,
        subTotalLabel: "Sub Total",
        totalFontSize: 8,
      },
      propertiesState: {
        bg_color: "#ffffff",
        font_family: "Poppins",
        font_color: "#000000",
        font_size: 8,
        font_weight: 400,
        label_font_color: "#000000",
        label_font_size: 8,
        label_font_weight: 600,
        pageSize: "3Inch",
        padding: {
          top: 20,
          bottom: 20,
          left: 10,
          right: 10,
        },
        templateName: "Retail Standard",
        template_kind: "standard",
        template_type: "standard",
      },
      headerState: {
      showLogo: false,
      logo: "",
      logoSize: 50,
      showOrgName: true,
      showOrgAddress: true,
      showDocTitle: true,
      docTitle: "",
      showBalanceDue: false,
      hasPhoneField: false,
      phoneLabel: "",
      hasfaxField: false,
      faxLabel: "",
      hasEmailField: false,
      emailLabel: "",
      bgColor: "#FFFFFF",
      isFirstOnly: false,
      bg_image_header_position: "center",
      headerHeight: 50,
      showHeader: true,
      docTitleFontSize: 16,
      docTitleFontColor: "#000000",
      OrganizationFontSize: 12,
      OrganizationFontColor: "#000000",
      show_balance_due: false,
      showStatusStamp: false,
      showReceivedFrom: false,
      showVender: false,
      venderNameFontSize: 11,
      venderNameFontColor: "#000000",
      receivedFromLabel: "",
      customerNameFontSize: 12,
      customerNameFontColor: "#000000",
      hasBillTo: false,
      billTo: "",
      hasShipTo: false,
      shipTo: "",
      orgNameFontSize: 12,
      orgNameFontColor: "#000000",
      showNumberField: false,
      numberField: "",
      showReasonField: false,
      reasonLabel: "",
      showAccountField: false,
      accountLabel: "",
      showAdjTypeField: false,
      adjTypeLabel: "",
      showCreateUserField: false,
      createUserLabel: "",
      showBranchField: false,
      branchLabel: "",
      showNotesLabel: false,
      notesLabel: "",
      showAmount: false,
      amountLabel: "",
      showDateField: false,
      dateField: "",
      showTerms: false,
      terms: "",
      showDueDate: false,
      due_date: "",
      showReference: false,
      reference: "",
      showSalesPerson: false,
      salesPerson: "",
      showProject: false,
      project: "",
      showEWayBill: false,
      eWayBill: "",
      showPlaceOfSupply: false,
      placeOfSupply: "",
      showSubject: false,
      subject: "",
      showTransactionType: false,
      transactionType: "",
      showSupplyDate: false,
      supplyDate: "",
      showShipmentDate: false,
      shipmentDateLabel: "",
      showAssociatedInvNo: false,
      showAssociatedInvDate: false,
      recieptInfo: {
        showReceiptTable: false,
        showReceiptNumber: false,
        receiptNumberLabel: "",
        showReceiptDate: false,
        receiptDateLabel: "",
        showReceiptReference: false,
        receiptReferenceLabel: "",
        showReceiptMode: false,
        receiptModeLabel: "",
        showReceiptAmount: false,
        receiptAmountLabel: "",
        amtReceivedLabel: "",
        currencySymbolPosition: "before",
        amtReceivedFontSize: 12,
        amtReceivedFontColor: "#000000",
        amtReceivedBgColor: "#FFFFFF",
      },
      accountSummary: {
        showAccountSummary: false,
        accountSummaryLabel: "",
        showOpeningBalance: false,
        openingBalanceLabel: "",
        showInvoicedAmount: false,
        invoicedAmountLabel: "",
        showAmountPaid: false,
        amountPaidLabel: "",
        showBalanceDue: false,
        balanceDueLabel: "",
      },
      customTop: {
      height: 0,customElements: [],
     },
      customBottom: {
      height: 0,customElements: [],
     },
    },
      footerState: {
        notesLabel: "Notes",
        noteFontSize: 12,
      },
      itemTableState: {
        amountLabel: "Amount",
        amountWidth: "10%",
        discountLabel: "Discount",
        discountWidth: "10%",
        discriptionLabel: "Description",
        headerFontColor: "#000000",
        headerFontSize: 8,
        hsnSacLabel: "HSN/SAC",
        hsnSacWidth: "10%",
        itemRowBgColor: "#ffffff",
        itemRowFontSize: 8,
        lineItemLabel: "Item",
        lineItemNumberLabel: "S.No.",
        lineItemNumberWidth: "10%",
        lineItemWidth: "30%",
        quantityLabel: "Qty",
        quantityWidth: "10%",
        rateLabel: "Rate",
        rateWidth: "10%",
        showAmount: true,
        showDiscount: true,
        showDiscription: false,
        showHsnSac: false,
        showLineItem: true,
        showLineItemNumber: true,
        showQuantity: true,
        showRate: true,
        showTableRowBorder: true,
        showTableHeaderBg: true,
        showTax: true,
        tableRowBorderColor: "#000000",
        tableHeaderBgColor: "#ffffff",
        taxLabel: "Tax",
        taxWidth: "10%",
      },
    },
    is_default: false,
    is_primary: true,
    voucher_type: "sales_invoice",
  },
];

export default DefaultSITemplates;
