import { DeafultTemplateProps } from "./billTemplates";

const DefaultSITemplates: DeafultTemplateProps[] = [
  {
    content: {
      /* ################  Standard Template  ################ */
      accTableState:{
        showInvoiceNumber: true,
        InvoiceNumberLabel: "Invoice Number",
        InvoiceNumberWidth: "15%",
      
        // Invoice Date Fields
        showInvoiceDate: true,
        InvoiceDateLabel: "Invoice Date",
        InvoiceDateWidth: "15%",
      
        // Invoice Amount Fields
        showInvoiceAmount: true,
        InvoiceAmountLabel: "Invoice Amount",
        InvoiceAmountWidth: "20%",
      
        // Withholding Tax Fields
        showWithholdingTax: true,
        WithholdingTaxLabel: "Withholding Tax",
        WithholdingTaxWidth: "15%",
      
        // TCS Amount Fields
        showTCSAmount: true,
        TCSAmountLabel: "TCS Amount",
        TCSAmountWidth: "15%",
      
        // Payment Amount Fields
        showPaymentAmount: true,
        PaymentAmountLabel: "Payment Amount",
        PaymentAmountWidth: "20%",
      },
      totalState: {
        showTotalSection: true,
        showSubTotalLabel: true,
        showDicount: true,
        showTax: true,
        showQuantity: true,
        showPaymentDetail: true,
        showAmoutInWords: true,
        subTotalLabel: "Sub Total",
        shippingLabel: "Shipping",
      },
      propertiesState: {
        bg_color: "#ffffff",
        font_family: "Poppins",
        font_size: 12,
        font_color: "#000000",
        font_weight: 400,

        label_font_size: 12,
        label_font_color: "#000000",
        label_font_weight: 400,
        pageSize: "A4",
        padding: {
          top: 40,
          bottom: 40,
          left: 30,
          right: 30,
        },
        templateName: "Standard Template (INV)",
        template_type: "standard",
        template_kind: "standard",
      },
      headerState: {
        showDocTitle: true,
        docTitle: "Invoice",
        showLogo: true,
        logoSize: 60,
        showOrgName: true,
        showOrgAddress: true,
        showBalanceDue: true,
        showNumberField: true,
        numberField: "Invoice #",
        showDateField: true,
        dateField: "Date",
        showTerms: true,
        terms: "Terms",
        showDueDate: true,
        due_date: "Due Date",
        showReference: true,
        reference: "P.O.#",
        showSalesPerson: true,
        salesPerson: "Sales Person",
        showProject: true,
        project: "Project 1",
        showEWayBill: true,
        eWayBill: "E-Way Bill#",
        showPlaceOfSupply: true,
        placeOfSupply: "Place of Supply",
        showSubject: true,
        subject: "Subject",
        showStatusStamp: true,
      },
      footerState: {
        notesLabel: "Notes",
        noteFontSize: 12,
      },
      itemTableState: {
        amountLabel: "Amount",
        amountWidth: "10%",
        discountLabel: "Discount",
        discountWidth: "10%",
        discriptionLabel: "Description",
        headerFontColor: "#ffffff",
        headerFontSize: 11,
        hsnSacLabel: "HSN/SAC",
        hsnSacWidth: "10%",
        itemRowBgColor: "#ffffff",
        itemRowFontSize: 12,
        lineItemLabel: "Item",
        lineItemNumberLabel: "S.No.",
        lineItemNumberWidth: "10%",
        lineItemWidth: "30%",
        quantityLabel: "Qty",
        quantityWidth: "10%",
        rateLabel: "Rate",
        rateWidth: "10%",
        showAmount: true,
        showDiscount: true,
        showDiscription: true,
        showHsnSac: true,
        showLineItem: true,
        showLineItemNumber: true,
        showQuantity: true,
        showRate: true,
        showTableBorder: true,
        showTableHeaderBg: true,
        showTax: true,
        tableBorderColor: "#a3a3a3",
        tableHeaderBgColor: "#3b3b3b",
        taxLabel: "Tax",
        taxWidth: "10%",
      },
   
    },
    is_default: true,
    is_primary: true,
    voucher_type: "sales_invoice",
  },
  {
    content: {
      /* ################  Retail- Standard Template  ################ */
      accTableState:{
        showInvoiceNumber: true,
        InvoiceNumberLabel: "Invoice Number",
        InvoiceNumberWidth: "15%",
      
        // Invoice Date Fields
        showInvoiceDate: true,
        InvoiceDateLabel: "Invoice Date",
        InvoiceDateWidth: "15%",
      
        // Invoice Amount Fields
        showInvoiceAmount: true,
        InvoiceAmountLabel: "Invoice Amount",
        InvoiceAmountWidth: "20%",
      
        // Withholding Tax Fields
        showWithholdingTax: true,
        WithholdingTaxLabel: "Withholding Tax",
        WithholdingTaxWidth: "15%",
      
        // TCS Amount Fields
        showTCSAmount: true,
        TCSAmountLabel: "TCS Amount",
        TCSAmountWidth: "15%",
      
        // Payment Amount Fields
        showPaymentAmount: true,
        PaymentAmountLabel: "Payment Amount",
        PaymentAmountWidth: "20%",
      },
      totalState: {
        balanceFontSize: 8,
        shippingLabel: "Shipping",
        showAmoutInWords: true,
        showDicount: false,
        showPaymentDetail: true,
        showQuantity: true,
        showSubTotalLabel: true,
        showTax: true,
        showTotalSection: true,
        subTotalLabel: "Sub Total",
        totalFontSize: 8,
      },
      propertiesState: {
        bg_color: "#ffffff",
        font_family: "Poppins",
        font_color: "#000000",
        font_size: 8,
        font_weight: 400,
        label_font_color: "#000000",
        label_font_size: 8,
        label_font_weight: 600,
        pageSize: "3Inch",
        padding: {
          top: 20,
          bottom: 20,
          left: 10,
          right: 10,
        },
        templateName: "Retail Standard",
        template_kind: "standard",
        template_type: "standard",
      },
      headerState: {
        dateField: "Date",
        docTitle: "Invoice",
        due_date: "Due Date",
        eWayBill: "E-Way Bill#",
        logoSize: 60,
        numberField: "Invoice #",
        placeOfSupply: "Place of Supply",
        project: "Project 1",
        reference: "P.O.#",
        salesPerson: "Sales Person",
        showBalanceDue: false,
        showDateField: true,
        showDocTitle: true,
        showDueDate: true,
        showEWayBill: true,
        showLogo: true,
        showNumberField: true,
        showOrgAddress: true,
        showOrgName: true,
        showPlaceOfSupply: true,
        showProject: true,
        showReference: true,
        showSalesPerson: true,
        showStatusStamp: true,
        showSubject: true,
        showTerms: true,
        subject: "Subject",
        terms: "Terms",
      },
      footerState: {
        notesLabel: "Notes",
        noteFontSize: 12,
      },
      itemTableState: {
        amountLabel: "Amount",
        amountWidth: "10%",
        discountLabel: "Discount",
        discountWidth: "10%",
        discriptionLabel: "Description",
        headerFontColor: "#000000",
        headerFontSize: 8,
        hsnSacLabel: "HSN/SAC",
        hsnSacWidth: "10%",
        itemRowBgColor: "#ffffff",
        itemRowFontSize: 8,
        lineItemLabel: "Item",
        lineItemNumberLabel: "S.No.",
        lineItemNumberWidth: "10%",
        lineItemWidth: "30%",
        quantityLabel: "Qty",
        quantityWidth: "10%",
        rateLabel: "Rate",
        rateWidth: "10%",
        showAmount: true,
        showDiscount: true,
        showDiscription: false,
        showHsnSac: false,
        showLineItem: true,
        showLineItemNumber: true,
        showQuantity: true,
        showRate: true,
        showTableBorder: true,
        showTableHeaderBg: true,
        showTax: true,
        tableBorderColor: "#000000",
        tableHeaderBgColor: "#ffffff",
        taxLabel: "Tax",
        taxWidth: "10%",
      },
    },
    is_default: false,
    is_primary: true,
    voucher_type: "sales_invoice",
  },
];

export default DefaultSITemplates;
