import VoucherType from "../../../../enums/voucher-types";
import {
  Countries,
  UserModel,
} from "../../../../redux/slices/user-session/reducer";
import { ApplicationSettingsType } from "../../../settings/system/application-settings-types/application-settings-types";
import { ColumnModel, TransactionFormState } from "../transaction-types";
export const purchaseGridCol = (
  applicationSettings: ApplicationSettingsType,
  userSession: UserModel,
  voucherType: string,
  formType: string,
  t: any,
  formState: TransactionFormState
) =>
  (
    [
      {
        dataField: "slNo",
        caption: "",
        dataType: "number",
        width: 40,
        isLocked: true,
        alignment: "center",
      },
      {
        dataField: "barCode",
        caption: t("barcode"),
        dataType: "string",
        allowEditing: true,
        width: 150,
        alignment: "left",
      },
      {
        dataField: "pCode",
        caption: t("code"),
        dataType: "string",
        allowEditing: true,
        width: 150,
        alignment: "left",
        visible: false,
      },
      {
        dataField: "productBatchID",
        caption: t("item_batch_id"),
        dataType: "number",
        width: 200,
        alignment: "right",
        visible: false,
      },
      {
        dataField: "product",
        caption: t("service"),
        dataType: "string",
        allowEditing: true,
        width: 250,
        alignment: "left",
      },
      {
        dataField: "productID",
        caption: t("product_id"),
        dataType: "number",
        width: 100,
        alignment: "right",
        visible: false,
      },
      {
        dataField: "brand",
        caption: t("brand"),
        idField: "brand",
        dataType: "cb",
        field: { valueKey: "name", labelKey: "name" },
        width: 150,
        alignment: "left",
        visible: false,
        allowEditing: true,
      },
      {
        dataField: "brandID",
        field: { valueKey: "id", labelKey: "name" },
        caption: t("brand_id"),
        dataType: "number",
        width: 100,
        readOnly: false,
        allowEditing: true,
        alignment: "right",
        visible: false,
      },
      {
        dataField: "qty",
        caption: t("qty"),
        dataType: "number",
        allowEditing: true,
        width: 100,
        alignment: "right",
      },
      {
        dataField: "unit",
        idField: "unitID",
        caption: t("unit"),
        dataType: "cb",
        width: 150,
        alignment: "left",
        allowEditing: true,
        readOnly: true,
      },
      {
        dataField: "free",
        caption: t("free"),
        dataType: "number",
        allowEditing: true,
        width: 100,
        alignment: "right",
        visible: false,
      },
      {
        dataField: "unitID",
        caption: t("unit_id"),
        detailsOptionKey: "units",
        allowEditing: true,
        visible: false,
        width: 100,
        alignment: "right",
      },
      {
        dataField: "ratePlusTax",
        caption: t("rate_plus_tax"),
        dataType: "number",
        visible: false,
        width: 130,
        alignment: "right",
        // decimalPoint: applicationSettings.mainSettings.decimalPoints,
      },
      {
        dataField: "unitPrice",
        caption: t("unit_price"),
        dataType: "number",
        allowEditing: true,
        width: 130,
        alignment: "right",
      },
      {
        dataField: "gross",
        caption: t("gross"),
        dataType: "number",
        decimalPoint: 4,
        readOnly: true,
        width: 100,
        alignment: "right",
        allowEditing: true,
      },
      {
        dataField: "discPerc",
        caption: t("disc_perc"),
        dataType: "number",
        decimalPoint: 3,
        allowEditing: true,
        width: 100,
        alignment: "right",
      },
      {
        dataField: "discount",
        caption: t("discount"),
        dataType: "number",
        decimalPoint: 4,
        allowEditing: true,
        width: 100,
        alignment: "right",
      },
      {
        dataField: "netValue",
        caption: t("net_value"),
        dataType: "number",
        decimalPoint: 4,
        width: 100,
        alignment: "right",
        readOnly: true,
        visible: false,
      },
      {
        dataField: "vatPerc",
        caption: t("vat_perc"),
        dataType: "number",
        readOnly: true,
        allowEditing: true,
        width: 100,
        alignment: "right",
      },
      {
        dataField: "vatAmount",
        caption: t("vat"),
        dataType: "number",
        readOnly: true,
        width: 100,
        alignment: "right",
        decimalPoint: applicationSettings.mainSettings.decimalPoints,
      },

      {
        dataField: "total",
        caption: t("total"),
        dataType: "number",
        width: 100,
        alignment: "right",
        readOnly: true,
        decimalPoint: applicationSettings.mainSettings.decimalPoints,
      },
      {
        dataField: "margin",
        caption: t("margin"),
        dataType: "number",
        visible: false,
        width: 100,
        allowEditing: true,
        alignment: "right",
        decimalPoint: 4,
      },
      {
        dataField: "salesPrice",
        caption: t("sales_price"),
        dataType: "number",
        visible: false,
        allowEditing: true,
        width: 200,
        alignment: "right",
        decimalPoint: applicationSettings.mainSettings.decimalPoints,
      },
      {
        dataField: "size",
        caption: t("size"),
        dataType: "string",
        visible: false,
        readOnly: true,
        width: 150,
        alignment: "left",
      },
      {
        dataField: "stickerQty",
        caption: t("sticker"),
        dataType: "number",
        visible: false,
        width: 130,
        alignment: "right",
        allowEditing: true,
      },
      {
        dataField: "cost",
        caption: t("cost"),
        dataType: "number",
        decimalPoint: applicationSettings.mainSettings.decimalPoints,
        readOnly: true,
        visible: false,
        width: 100,
        alignment: "right",
      },
      {
        dataField: "batchCreated",
        caption: t("batch_created"),
        dataType: "chk",
        visible: false,
        width: 150,
        alignment: "center",
      },
      {
        dataField: "barcodePrinted",
        caption: t("barcode_printed"),
        dataType: "chk",
        visible: false,
        width: 50,
        alignment: "center",
      },
      {
        dataField: "productDescription",
        caption: t("product_description"),
        dataType: "string",
        width: 250,
        alignment: "left",
        visible: false,
      },
      {
        dataField: "stockDetails",
        caption: t("stock_details"),
        dataType: "string",
        readOnly: true,
        visible: false,
        width: 200,
        alignment: "left",
      },
      {
        dataField: "adjQty",
        caption: t("adj_qty"),
        dataType: "number",
        visible: false,
        width: 100,
        alignment: "right",
        decimalPoint: 4,
      },
      {
        dataField: "stdPurchasePrice",
        caption: t("purchase_price"),
        dataType: "number",
        width: 55,
        alignment: "center",
        decimalPoint: applicationSettings.mainSettings.decimalPoints,
      },
      {
        dataField: "batchNo",
        caption: t("batch_no"),
        dataType: "string",
        visible: false,
        width: 150,
        alignment: "left",
      },
      {
        dataField: "sgstPerc",
        caption: t("sgst_perc"),
        dataType: "number",
        width: 100,
        allowEditing: true,
        alignment: "right",
      },
      {
        dataField: "sgst",
        caption: t("sgst"),
        dataType: "number",
        width: 100,
        alignment: "right",
        decimalPoint: applicationSettings.mainSettings.decimalPoints,
      },
      {
        dataField: "cgstPerc",
        caption: t("cgst_perc"),
        dataType: "number",
        width: 100,
        alignment: "right",
      },
      {
        dataField: "cgst",
        caption: t("cgst"),
        dataType: "number",
        width: 100,
        alignment: "right",
        decimalPoint: applicationSettings.mainSettings.decimalPoints,
      },

      {
        dataField: "igstPerc",
        caption: t("igst_perc"),
        dataType: "number",
        width: 100,
        allowEditing: true,
        alignment: "right",
      },
      {
        dataField: "igst",
        caption: t("igst"),
        dataType: "number",
        width: 100,
        allowEditing: true,
        decimalPoint: applicationSettings.mainSettings.decimalPoints,
        alignment: "right",
      },
      {
        dataField: "cessPerc",
        caption: t("cess_perc"),
        dataType: "number",
        width: 100,
        allowEditing: true,
        alignment: "right",
      },
      {
        dataField: "cessAmt",
        caption: t("cess_amt"),
        dataType: "number",
        decimalPoint: applicationSettings.mainSettings.decimalPoints,
        width: 100,
        allowEditing: true,
        alignment: "right",
      },
      {
        dataField: "additionalCessPerc",
        caption: t("additional_cess_perc"),
        dataType: "number",
        width: 100,
        allowEditing: true,
        alignment: "right",
      },
      {
        dataField: "additionalCess",
        caption: t("additional_cess"),
        decimalPoint: applicationSettings.mainSettings.decimalPoints,
        dataType: "number",
        width: 100,
        allowEditing: true,
        alignment: "right",
      },
      {
        dataField: "mrp",
        decimalPoint: applicationSettings.mainSettings?.decimalPoints,
        caption: t("mrp"),
        dataType: "number",
        allowEditing: true,
        width: 100,
        readOnly: false,
        alignment: "right",
      },
      {
        dataField: "actionCol",
        caption: "",
        dataType: "boolean",
        width: 55,
        readOnly: true,
        isLocked: true,
        alignment: "center",
      },
    ] as ColumnModel[]
  )
    .filter((gc: ColumnModel) => {
      const field = gc.dataField ?? "";

      // ---------------- SERVICE INVOICE ----------------
      if (
        userSession.countryId != Countries.India &&
        voucherType == VoucherType.ServiceInvoice
      ) {
        return ![
          "cgst",
          "cgstPerc",
          "sgstPerc",
          "sgst",
          "igstPerc",
          "igst",
          "cessPerc",
          "cessAmt",
          "additionalCessPerc",
          "additionalCess",
          "mrp",
        ].includes(field);
      } 
      return true;
    });
