export const DummyInvoiceData = {
  created_at: "2023-01-21T08:36:41.448190Z",
  payment_terms: { name: "Payment term 2", id: 2, number_of_days: 2 },
  sales_person: { id: 2, name: "John Doe" },
  sub_total: "214890.0",
  balance_due: "40269.400",
  status: "send",
  due_date: "2023-01-29T08:36:41.448190Z",
  paid_amount: "0.000",
  sales_invoice_no: "001",
  discount_price: "0.000",
  total_price: "214890.0",
  total_tax_amount: "23735",
  notes: "Thanks for your business.",
  terms_and_conditions: "Your company's Terms and Conditions will be displayed here.",
  description: "Sample description will be displayed here.",
  qr_code: "https://i.ibb.co/G98LJNx/test-dummy.png",
  qr_description: "Scan the QR & Find whats inside",

  // INV Adjustments
  reason: { name: "Reason Name" },
  account_name: "Account name",
  mode_adjustment: "Quantity",
  created_by: "John Doe",
  ref_number: "Ref Numbers",
  // Journal Entries
  debit_sub_total: "20.00",
  credit_sub_total: "20.00",
  debit_total: "20.00",
  credit_total: "20.00",
  //Receipt Information
  reference_number: "reference id",
  payment_mode: { name: "Bank" },
  total_amount: "2279",
  voucher_number: "RV007",
  //sales_return Dummy data
  invoice: {
    id: 76027,
    name: "SI1",
    date: "2024-06-11T11:25:01Z",
  },
  transaction_type: "Others",
  // Customer and vendor statement
  statementData: [
    { opening_balance: 50000.0 },
    { invoice_amount: 21000.0 },
    { payment_received: 12000.0 },
    {
      transactions: [
        {
          amount: 4000,
          balance: 4000,
          company: null,
          created_at: null,
          credit_account_code: null,
          credit_ref_id: null,
          currency: null,
          date: null,
          debit_account_code: null,
          debit_ref_id: null,
          exchange_rate: null,
          fiscal_year: null,
          id: null,
          transaction_locked: false,
          updated_at: null,
          voucher_code: "Opening Balance",
          voucher_number: "",
        },
        {
          amount: 4000,
          balance: 0,
          company: 17,
          created_at: "2023-11-01T05:05:53.470537Z",
          credit_account_code: "332301301",
          credit_ref_id: 1092,
          currency: null,
          date: "2023-10-30T08:22:13Z",
          debit_account_code: "110100103",
          debit_ref_id: 240,
          exchange_rate: "1.00",
          fiscal_year: 2,
          id: 11460,
          transaction_locked: false,
          updated_at: "2023-11-01T05:05:53.470552Z",
          voucher_code: "Sales Invoice",
          voucher_number: "SI68",
        },
      ],
    },
  ],
  //
  customer: {
    name: "Boss & Co",
    billing_address: {
      address: "Mushrifah Dist., P.O.Box: 30376",
      city: "Jeddah",
      country: "Saudi Arabia",
    },
    shipping_address: {
      address: "Ship Mushrifah Dist., P.O.Box: 30376",
      city: "Jeddah",
      country: "Saudi Arabia",
    },
  },
  addresses: [
    {
      address: {
        address_type: {
          is_for: "customer",
        },
      },
    },
  ],
  items: [
    {
      item_name: "Apple iPhone 13 Pro Max (128GB, Gold)",
      qty: "1.000",
      account: "110100100",
      account_name: "Sales",
      item_rate: "129900.00",
      total_price: "129900.00",
      discount_price: "0.00",
      hsn_code: "482050",
      description: "Mesmerising pictures with immaculate clarity.",
      contact: { name: "Steve" },
      item_unit: { id: 411, name: "NOS" },
      quantity_adjusted: "47.00",
      adjusted_value: "21.00",
      debit: "20.00",
      credit: "0.00",
      amount: "21000",
      item_tax_category: {
        code: "rate-15",
        delete: false,
        id: 832,
        is_default: true,
        is_exempt: false,
        is_out_of_scope: false,
        is_registered: true,
        is_visible: true,
        member_states: "KSA",
        name: "Standard Rate (15%)",
        tax_split: [{ id: 831, input_tax_account: null, is_registered: true, name: "VAT", output_tax_account: null, percentage: 15 }],
        total_percentage: 15,
      },
    },
    {
      item_name: "Apple Mac Mini (16GB RAM, 256GB SSD)",
      qty: "1.000",
      account: "110100101100",
      account_name: "Undeposited Funds",
      item_rate: "84990.00",
      total_price: "84990.00",
      discount_price: "0.00",
      hsn_code: "482090",
      description: "supercharged by the M2 chip",
      contact: { name: "Rogers" },
      quantity_adjusted: "25.00",
      item_unit: { id: 411, name: "NOS" },
      adjusted_value: "38.00",
      debit: "0.00",
      credit: "20.00",
      amount: "52000",
      item_tax_category: {
        code: "rate-5",
        delete: false,
        id: 833,
        is_default: true,
        is_exempt: false,
        is_out_of_scope: false,
        is_registered: true,
        is_visible: true,
        member_states: "KSA",
        name: "Standard Rate (5%)",
        tax_split: [{ id: 832, input_tax_account: null, is_registered: true, name: "VAT", output_tax_account: null, percentage: 5 }],
        total_percentage: 5,
      },
    },
  ],
};

// export const DummyVoucherData ={
// asOnDate : 
// "2025-06-03T00:00:00",
// balance
// : 
// 6561.98,
// code
// : 
// 10977,
// customerAccName
// : 
// "  MUASSASA  ALGHILAL ALDHAHABIA",
// ledgerID
// : 
// 10063
// }



export const DummyVoucherData ={

    "master": {
        "invTransactionMasterID": 0,
        "branchID": 1,
        "financialYearID": 1,
        "counterID": 0,
        "salesMan": 0,
        "inventoryLedgerID": 0,
        "ledgerID": 0,
        "referalAgentID": null,
        "address1": null,
        "address2": null,
        "address3": null,
        "address4": null,
        "voucherPrefix": "CP",
        "voucherNumber": "23835",
        "dailyVoucherNumber": null,
        "transactionDate": "2025-09-08T00:00:00",
        "remarks": "",
        "fromWarehouseID": null,
        "toWarehouseID": null,
        "createdUserID": 1,
        "modifiedUserID": 1,
        "systemDateTime": "2025-09-08T10:34:17.757",
        "voucherType": "CP",
        "voucherForm": null,
        "purchaseInvoiceNumber": null,
        "purchaseInvoiceDate": null,
        "quotationNumber": null,
        "quotationDate": null,
        "dueDate": "2025-09-08T00:00:00",
        "deliveryNoteNumber": null,
        "refNoSales": null,
        "deliveryDate": null,
        "refDateSales": null,
        "despatchDocumentNumber": null,
        "despatchDate": null,
        "vehicelID": null,
        "salesManID": null,
        "deliveryManID": null,
        "driverID": null,
        "vatAmount": 0,
        "totalVat": 0,
        "vatPercentage": 0,
        "totalGross": 0,
        "privRedeem": 0,
        "privAddAmount": 0,
        "privCardID": null,
        "netTotal": 0,
        "totalDiscount": 0,
        "sumofDiscount": 0,
        "totItemDiscPlusBillDisc": 0,
        "billDiscount": 0,
        "adjustmentAmount": 0,
        "grandTotal": 0,
        "totalProfit": 0,
        "roundAmount": 0,
        "cashReceived": 0,
        "advanceAmt": 0,
        "cashReturned": 0,
        "shortageAmount": 0,
        "salesManIncentive": 0,
        "gatePassNo": null,
        "displayOrderNumber": "600001191909",
        "cashAmt": 0,
        "bankAmt": 0,
        "creditAmt": 0,
        "oldInvTransactionID": null,
        "createdDate": "2025-09-08T10:34:17.62",
        "modifiedDate": "2025-09-08T10:34:17.757",
        "isActive": true,
        "tokenNumber": null,
        "inout": null,
        "fcAmount": 0,
        "customerType": null,
        "taxOnDiscount": false,
        "counterName": "",
        "salesManCode": null,
        "salesManName": null,
        "costCentreName": null,
        "projectName": null,
        "projectAddress1": null,
        "projectAddress2": null,
        "projectAddress3": null,
        "privCardNumber": null,
        "userName": null,
        "orderNumber": null,
        "orderDate": null,
        "srAmount": 0,
        "warehouseName": null,
        "fromWarehouseName": null,
        "toWarehouseName": null,
        "salesManEmail": null,
        "salesManMobile": null,
        "referenceNumber": "",
        "mannualInvoiceNumber": null,
        "transactionDateWithTime": "0001-01-01T00:00:00",
        "couponAmt": 0,
        "noofItems": 0,
        "tableLocation": null,
        "tableNo": null,
        "seatNumber": null,
        "exchangeRate": 0,
        "grandTotalFC": 0,
        "totalDiscountFC": 0,
        "priceCategoryName": null,
        "master2Data": null,
        "master3Data": null,
        "vehicleData": null,
        "partyData": null,
        "oP_DVData": null,
        "oP_ADDData": null,
        "oP_CLData": null,
        "eInvoiceData": null,
        "multiPaymentData": null,
        "accTransactionMasterID": 600001191909,
        "departmentID": 0,
        "costCentreID": 0,
        "billwiseMasterID": 0,
        "employeeID": 2,
        "invTransactionID": 0,
        "prevTransDate": null,
        "bankDate": "2025-09-08T00:00:00",
        "referenceDate": "2025-09-08T00:00:00",
        "particulars": "Main Cash Head Office - الحساب النقدي الرئيسي",
        "totalDebit": 500.0000,
        "billwiseTotalAdjAmt": null,
        "billwiseAdjAmt": null,
        "totalCredit": 0.0000,
        "totDiscount": 0.0000,
        "empIncentive": 0.0000,
        "commonNarration": "",
        "formType": "",
        "debitNoteTransID": 0,
        "creditNoteTransID": 0,
        "currencyID": 11,
        "accTransDetailID": 0,
        "adjustedTransDetailID": 0,
        "currencyRate": 1.000000,
        "isPosted": false,
        "randomKey": 113181,
        "onlineTrans": "",
        "isEdit": false,
        "chequeStatus": null,
        "checkBouncedDate": "2025-09-08T00:00:00+05:30",
        "drCr": "Dr",
        "isSalesView": false,
        "refBranchID": 0,
        "uuid": "546b99a1-d47f-4302-b686-f8efdeeafe01",
        "oldAccTransactionMasterID": 0,
        "actionStatus": "A",
        "counterShiftID": 0,
        "isLocked": false,
        "editId": null,
        "notes": "",
        "masterAccount": "Main Cash Head Office - الحساب النقدي الرئيسي",
        "employeeName": "RAZAK CHOLAYIL  ",
        "employeeCode": "02",
        "branch": "",
        "netAmount": 0,
        "returnAmount": 0
    },
    "details": [
        {
            "slNo": 0,
            "invTransactionDetailID": 0,
            "invTransactionMasterID": 0,
            "productBatchID": 0,
            "productDescription": null,
            "quantity": 0,
            "qtyInBaseUnit": 0,
            "baseUnitUnitPrice": 0,
            "taxIncludedBasePrice": 0,
            "baseQty": 0,
            "free": 0,
            "qtyInNumbers": 0,
            "unitID": 0,
            "totalQty": 0,
            "barcodeQty": 0,
            "unitPrice": 0,
            "valuationPrice": 0,
            "rateWithTax": 0,
            "grossValue": 0,
            "discountPer1": 0,
            "discountAmt1": 0,
            "totalDiscount": 0,
            "vatPercentage": 0,
            "vat": 0,
            "netValue": 0,
            "taxIncludedPrice": 0,
            "cstPerc": 0,
            "cst": 0,
            "netAmount": 0,
            "costPerItem": 0,
            "totalProfit": 0,
            "marginPer": 0,
            "marginAmt": 0,
            "stdSalesPrice": 0,
            "mrp": 0,
            "invStatus": null,
            "salesManID": 0,
            "qtyIn": 0,
            "qtyOut": 0,
            "qtyNosIn": 0,
            "qtyNosOut": 0,
            "adjQty": 0,
            "adjQtyNos": 0,
            "modelNo": null,
            "specification": null,
            "color": null,
            "autoBarcode": null,
            "mannualBarcode": null,
            "mfgDate": null,
            "brandName": null,
            "brandID": 0,
            "brandShortName": null,
            "sVatPerc": 0,
            "pVatPerc": 0,
            "taxCategoryName": null,
            "productCode": null,
            "productName": null,
            "hsnCode": null,
            "commodityCode": null,
            "itemAliasCode": null,
            "itemAlias": null,
            "itemNameinSecondLanguage": null,
            "arabicName": null,
            "batchStdSalesPrice": 0,
            "stdPurchasePrice": 0,
            "batchMRP": 0,
            "modelNumber": null,
            "batchSpecification": null,
            "upcCode": null,
            "packing": null,
            "partNumber": null,
            "productColour": null,
            "warranty": null,
            "productCategoryCode": null,
            "productCategoryName": null,
            "unitCode": null,
            "unitName": null,
            "unitRemarks": null,
            "groupName": null,
            "serialNumber": null,
            "location": null,
            "salesValue": 0,
            "unitSalesValue": 0,
            "unitQty": 0,
            "additionalExpense": 0,
            "scannedBarcode": null,
            "unitPriceFC": 0,
            "grossFC": 0,
            "netValueFC": 0,
            "netAmountFC": 0,
            "totalDiscountFC": 0,
            "exchangeRate": 0,
            "productUnitRemarks": null,
            "warehouseID": 0,
            "warehouse": null,
            "supplierReferenceProductCode": null,
            "batchNo": null,
            "expiryDate": null,
            "schemeDiscAmt": 0,
            "schemeDiscPerc": 0,
            "memo": null,
            "stock": 0,
            "netWeight": 0,
            "netWeightUnitName": null,
            "productNotes1": null,
            "productNotes2": null,
            "productNotes3": null,
            "productNotes4": null,
            "itemType": null,
            "gatePass": 0,
            "stockDetails": null,
            "voucherNumber": "",
            "dailyVoucherNumber": "",
            "voucherType": "",
            "branchID": 0,
            "counterID": 0,
            "partyName": "",
            "vatAmount": 0,
            "billDiscount": 0,
            "grandTotal": 0,
            "roundAmount": 0,
            "cashReceived": 0,
            "advanceAmt": 0,
            "cashReturned": 0,
            "salesManIncentive": 0,
            "adjustmentAmount": 0,
            "branch": "",
            "siNo": 1,
            "accTransactionDetailID": 600004727306,
            "ledgerCode": "6189",
            "accountName": "MAJESTIC SWEETS FACTORY",
            "relatedLedgerCode": "CS",
            "particulars": "Main Cash Head Office - الحساب النقدي الرئيسي",
            "particularLedgerCode": "CS",
            "ledgerID": 5272,
            "relatedLedgerID": 1,
            "debit": 500.0000,
            "credit": 0.0000,
            "amount": 500.0000,
            "narration": "",
            "discount": 0.0000,
            "incentives": 0.0000,
            "adjAmount": 0.0000,
            "bankDate": "2000-01-01T00:00:00",
            "chequeNumber": "",
            "checkStatus": "C",
            "checkBouncedDate": "2000-01-01T00:00:00",
            "chequeDate": "2000-01-01T00:00:00",
            "billwiseDetails": "",
            "ledgerNameArabic": "مؤسسة سعيد عبدالله بلقاسم البردي الشيخي",
            "relatedLedgerNameArabic": "الحساب النقدي الرئيسي",
            "costCentreName": "SAMA PLASTICS",
            "txp_PartyName": null,
            "txp_TaxNo": null,
            "txp_TaxPercentage": null,
            "txp_TaxAmount": null,
            "txp_TaxableAmount": null,
            "txp_RefNo": null,
            "txp_RefDate": null,
            "detail2Data": null
        }
    ],
    "companyDetails": {
        "registeredName": "SAMA UNITED TRADING COMPANY",
        "registeredNameArabic": "شركة سماءشركة سماء المتحدة التجارية",
        "taxRegNo": "310434406200003",
        "crNumber": "4030185693",
        "buildingNo": "2790",
        "streetName": "Ashamah Bin Abjar Al Najashi",
        "district": "Al Mahjar",
        "city": "Jeddah",
        "postalCode": "22421",
        "additionalNo": "7804",
        "country": "Saudi Arabia",
        "emailAddress": "info@unitedsama.com",
        "telephone": "",
        "mobile": "",
        "companyLogo": ""
    },
    "headerFooter": {
        "heading1": "Sama United Trading Company",
        "heading2": "Star Center - Po Box 10042 - Al Mahajar Industrial Area - Jeddah 21311 - KSA.",
        "heading3": "VAT No : 310434406200003",
        "heading4": "Phone  12 6362230",
        "heading5": "www.unitedsama.com",
        "heading6": "gasdgfdg",
        "heading7": "Sama United Trading Company",
        "heading8": "VAT No : 310434406200003",
        "heading9": "Star Center - Po Box 10042 - Al Mahajar Industrial Area - Jeddah 21311 - KSA.",
        "heading10": "asdgf",
        "footer1": "",
        "footer2": "",
        "footer3": "",
        "footer4": "",
        "footer5": "",
        "footer6": "",
        "footer7": "liswdfglk askdgjdfg l';kjasdg lkj ;l'asgfsgfdgkikuujikkkkkji  ;aljg 65453132421544",
        "footer8": "",
        "footer9": "",
        "footer10": ""
    },
    "ledgerBalance": 0,
    "previousLedgerBalance": 0,
    "loyaltyCardBalance": 0,
    "totalTaxableValue0Percent": 0,
    "totalTaxableValue5Percent": 0,
    "totalTaxableValue15Percent": 0,
    "totalTaxValue5Percent": 0,
    "totalTaxValue15Percent": 0,
    "printCount": 0,
    "isCashInHandLedger": false,
    "isLedgerUnderBank": false,
    "isLedgerUnderCashOrBank": false,
    "productionReqId": false,
    "salesBillNumbers": null,
    "salesBillAmounts": null,
    "salesRetBillNumbers": null,
    "salesRetBillAmounts": null
}
